SELECT AGE.COD_AGENDAMENTO CODAGENDAMENTO,
       CAN.NOMCAN AS "Candidato",
       CAN.DATNASCAN,
       CAN.CODCAN,
       (SELECT CUR.NOMCUR || ' / ' || CAM.NOMCAM || ' / ' || TUR.DSCTUR
          FROM DBVESTIB.CURSO          CUR,
               DBVESTIB.TURNO          TUR,
               DBVESTIB.CAMPUS         CAM,
               DBVESTIB.RCANDCURTUROPC OPC
         WHERE CUR.CODCONC = CAN.CODCONC
               AND CUR.CODCUR = OPC.CODCUR
               AND TUR.CODTUR = OPC.CODTUR
               AND OPC.CODCONC = CAN.CODCONC
               AND OPC.CODCAN = CAN.CODCAN
               AND OPC.NROOPC = '1'
               AND CAM.CODCAM = OPC.CODCAM) AS "Curso",
       CON.NOMCONC,
       CAN.IDECAN,
       TO_CHAR(DIP.DAT_HORA_INICIO,
               'DD/MM/YYYY - HH24:MI') AS DATINICIO,
       TRUNC(DIP.DAT_HORA_INICIO) DATAOR,
       :P_HORA AS HORA_INICIO,
       EST.DSC_ESTRUTURA "NOME PESSOA",
       CID.NOM_CIDADE,
       TEM.NOM_TEMA_REDACAO,
       TEM.DSC_TEMA_REDACAO, PEP.COD_PESSOA_PROCESSO
  FROM DBVESTIB.CONCURSO              CON
  INNER JOIN DBVESTIB.CANDIDATO             CAN ON CAN.CODCONC = CON.CODCONC
  INNER JOIN DBSAG.MAPEAMENTO_CLI_INSCRICAO CIN ON CIN.CODCONC = CAN.CODCONC AND CIN.CODINSC = CAN.CODCAN  AND CAN.CODFORMAPROVA = 1
  INNER JOIN DBVESTIB.TEMA_REDACAO          TEM ON TEM.CODCONC = CAN.CODCONC AND TEM.CODCONC = CAN.CODCONC
  INNER JOIN DBSAG.AGENDAMENTO              AGE ON AGE.COD_MAPEAMENTO_CLIENTE = CIN.COD_MAPEAMENTO_CLIENTE
  INNER JOIN DBSAG.DISPONIBILIDADE_PESSOA   DIP ON DIP.COD_DISPONIBILIDADE = AGE.COD_DISPONIBILIDADE
  INNER JOIN DBSAG.PESSOA_PROCESSO           PEP ON PEP.COD_PESSOA_PROCESSO = DIP.COD_PESSOA_PROCESSO
  INNER JOIN DBSAG.MAPEAMENTO_PES_PESSOA     MPP ON MPP.COD_MAPEAMENTO_PESSOA = PEP.COD_MAPEAMENTO_PESSOA
  INNER JOIN DBSIAF.ESTRUTURA_PESSOA         PES ON PES.COD_PESSOA = MPP.COD_PESSOA
  INNER JOIN DBSIAF.ESTRUTURA_ORGANIZACIONAL EST ON EST.COD_ESTRUTURA = PES.COD_ESTRUTURA
  INNER JOIN DBSIAF.TIPO_ESTRUTURA_ORGANIZACIONAL TEO ON TEO.COD_TPO_ESTRUTURA = EST.COD_TPO_ESTRUTURA
  INNER JOIN DBSIAF.ENDERECO_ESTRUTURA       EED ON EED.COD_ESTRUTURA = EST.COD_ESTRUTURA
  INNER JOIN DBSIAF.CIDADE                   CID ON CID.COD_CIDADE = EED.COD_CIDADE
  INNER JOIN DBSIAF.ESTADO                   ETD ON ETD.COD_ESTADO = CID.COD_ESTADO
  INNER JOIN DBSIAF.PAIS                     PAI ON PAI.COD_PAIS = ETD.COD_PAIS
  INNER JOIN DBSAG.LOCAL_PROCESSO           LOC ON LOC.COD_LOCAL_PROCESSO = DIP.COD_LOCAL_PROCESSO   AND DIP.COD_TEMA_REDACAO_ATUAL = TEM.COD_TEMA_REDACAO
  INNER JOIN DBSAG.MAPEAMENTO_LOC_ESTRUTURA MLE ON MLE.COD_MAPEAMENTO_LOCAL = LOC.COD_MAPEAMENTO_LOCAL
 WHERE CON.CODCONC = SUBSTR( :P_CONCURSO_USUARIO  ,1,4)
  AND PEP.COD_PESSOA_PROCESSO = :P_COD_PESSOA_PROCESSO
  AND :P_COD_USUARIO = :P_COD_USUARIO
       

UNION ALL
SELECT NULL CODAGENDAMENTO,
       'TESTE COPE' AS "CANDIDATO",
       NULL DATNASCAN,
       '123456' CODCAN,
       NULL AS "CURSO",
       CON.NOMCONC,
       NULL IDECAN,
       NULL AS DATINICIO,
       NULL DATAOR,
       NULL AS HORA_INICIO,
       NULL "NOME PESSOA",
       NULL NOM_CIDADE,
       TEM.NOM_TEMA_REDACAO,
       TEM.DSC_TEMA_REDACAO,
       NULL COD_PESSOA_PROCESSO
FROM  DBVESTIB.TEMA_REDACAO              TEM,
      DBVESTIB.CONCURSO                  CON
WHERE TEM.CODCONC = CON.CODCONC
  AND CON.CODCONC = SUBSTR( :P_CONCURSO_USUARIO  ,1,4)
  AND EXISTS(
SELECT 1 
  FROM 
    DBADM.USUARIO USU,
     DBADM.USUARIO_GRUPO USG,
     DBADM.GRP_USUARIO UGR    
 WHERE UGR.COD_GRP_USUARIO IN (235,294,2)
     AND UGR.COD_GRP_USUARIO = USG.COD_GRP_USUARIO
     AND USU.COD_USUARIO = USG.COD_USUARIO
     AND TEM.COD_TEMA_REDACAO = :P_COD_PESSOA_PROCESSO)
