SELECT EST.COD_ESTRUTURA "CODIGO",
       EST.DSC_COD_LOCALIZADOR "CODIGO LOCALIZADOR",
       EST.DSC_ESTRUTURA "NOME",
       (SELECT EOR.DSC_ESTRUTURA
       FROM DBSIAF.ESTRUTURA_ORGANIZACIONAL EOR
       WHERE EOR.COD_ESTRUTURA = EST.COD_ESTRUTURA_PAI) "EMPRESA CONTRATANTE",
       EST.EML_ESTRUTURA "EMAIL",
       EST.DATA_CADASTRO "DATA CADASTRO",
       EPE.NUM_CPF "CPF",
       epe.num_cnpj "CNPJ",
       TEO.NOM_TPO_ESTRUTURA "TIPO ESTRUTURA",
       EDE.NOM_LOGRADOURO "LOGRADOURO",
       EDE.NOM_COMPLEMENTO "COMPLEMENTO",
       EDE.NOM_BAIRRO "BAIRRO",
       EDE.CEP_ENDERECO "CEP",
       EDE.TEL_ENDERECO "TELEFONE",
       TEL_CELULAR "CELULAR",
       CID.NOM_CIDADE "CIDADE",
       ETD.SGL_ESTADO "UF",
       PAI.NOM_PAIS "PAÍS",
       EPE.COD_PESSOA,
       EPE.SEXO,
       ETD.COD_ESTADO,
       ESC.CODCONC "CONCURSO ASSOCIADO"
     FROM DBSIAF.ESTRUTURA_ORGANIZACIONAL EST
 LEFT JOIN DBSIAF.ENDERECO_ESTRUTURA EDE ON EDE.COD_ESTRUTURA = EST.COD_ESTRUTURA
 LEFT JOIN DBSIAF.CIDADE CID ON CID.COD_CIDADE = EDE.COD_CIDADE
 LEFT JOIN DBSIAF.ESTADO ETD ON ETD.COD_ESTADO = CID.COD_ESTADO
 LEFT JOIN DBSIAF.PAIS PAI     ON PAI.COD_PAIS = ETD.COD_PAIS
 LEFT JOIN DBSIAF.ESTRUTURA_PESSOA EPE ON EPE.COD_ESTRUTURA = EST.COD_ESTRUTURA
 INNER JOIN DBSIAF.TIPO_ESTRUTURA_ORGANIZACIONAL TEO ON TEO.COD_TPO_ESTRUTURA = EST.COD_TPO_ESTRUTURA
 LEFT JOIN DBSIAF.ESTRUTURA_CONCURSO ESC ON ESC.COD_ESTRUTURA = EST.COD_ESTRUTURA AND ESC.IND_ASSOCIADO = 'S'
ORDER BY EST.COD_ESTRUTURA DESC 
