
 INSERT INTO DBSIAF.TIPO_CONCURSO_ANO_SEMESTRE
     (COD_TIPO_CONCURSO_ANO_SEMESTRE,
      COD_TPO_CONCURSO,
                  ANOCONC,
                  SEMCONC)
 VALUES
     ( :COD_TIPO_CONCURSO_ANO_SEMESTRE,
      :COD_TPO_CONCURSO,
                  :ANOCONC,
                  :SEMCONC );
                  
                  

 INSERT INTO DBSIAF.HORARIO_TPO_CONCURSO_ANO_SEM
	 (COD_HORARIO_TPO_CONC_ANO_SEM,
                  COD_TIPO_CONCURSO_ANO_SEMESTRE,
	  HOR_INICIO,
	  HOR_FIM)
 VALUES
	  ( :COD_HORARIO_TPO_CONC_ANO_SEM,
                    :COD_TIPO_CONCURSO_ANO_SEMESTRE,          
	   TO_DATE( :HOR_INICIO, 'HH24:MI') ,
	   TO_DATE( :HOR_FIM , 'HH24:MI') 
                 );


INSERT INTO DBSIAF.CONCURSO_ANO_SEMESTRE
	(COD_CONCURSO_ANO_SEMESTRE,
	 COD_TIPO_CONCURSO_ANO_SEMESTRE,
	 CODCONC)
VALUES
	( :COD_CONCURSO_ANO_SEMESTRE,
	  :COD_TIPO_CONCURSO_ANO_SEMESTRE,
	  :CODCONC);


 INSERT INTO DBSIAF.HORARIO_CONCURSO_ANO_SEM
	 (COD_HORARIO_CONCURSO_ANO_SEM,
	  COD_CONCURSO_ANO_SEMESTRE,
        HOR_INICIO,
	  HOR_FIM)
 VALUES
	 (:COD_HORARIO_CONCURSO_ANO_SEM,
	  :COD_CONCURSO_ANO_SEMESTRE,
                  TO_DATE( :HOR_INICIO, 'HH24:MI') ,
	  TO_DATE( :HOR_FIM , 'HH24:MI') );
      
      
      
      INSERT INTO DBSIAF.PROCESSO_TPO_CONCURSO_ANO_SEM(NUM_PRAZO_MIN_HORAS_MARCACAO,
       NUM_PRAZO_MAX_DIAS_MARCACAO,      
       NUM_PRAZO_HORAS_DESMARCACAO,
       IND_PERMITE_SUGERIR_HORARIO,
       NUM_MINUTOS_ENTREVISTA,
       IND_AGENDAMENTO_OBRIGATORIO,
       IND_PERMITE_ESCOLHER_LOCAL,
       IND_CONCLUIR_INSCRICAO_VESTIB,
       IND_EXIBIR_MOTIVO_AGENDAMENTO,
       NUM_PRAZO_MIN_DIAS_UTEIS_MARC,
       NUM_PRAZO_VENC_BOLETO_UTEIS,
       COD_TIPO_CONCURSO_ANO_SEMESTRE,
       EMAIL_NOTIFICACAO,
       TITULO_EMAIL,
       REMETENTE_EMAIL)
VALUES (  :NUM_PRAZO_MIN_HORAS_MARCACAO,
	   :NUM_PRAZO_MAX_DIAS_MARCACAO,
	   :NUM_PRAZO_HORAS_DESMARCACAO,
	   decode( :IND_PERMITE_SUGERIR_HORARIO,'Sim', 'S', 'N'),
           :NUM_MINUTOS_ENTREVISTA,
	   decode( :IND_AGENDAMENTO_OBRIGATORIO,'Sim', 'S', 'N'),
	   decode( :IND_PERMITE_ESCOLHER_LOCAL,'Sim', 'S', 'N'),
	   decode( :IND_CONCLUIR_INSCRICAO_VESTIB,'Sim', 'S', 'N'),
	   decode( :IND_EXIBIR_MOTIVO_AGENDAMENTO,'Sim', 'S', 'N'),
	   :NUM_PRAZO_MIN_DIAS_UTEIS_MARC,
	   :NUM_PRAZO_VENC_BOLETO_UTEIS,
	   :COD_TIPO_CONCURSO_ANO_SEMESTRE,
	   :EMAIL_NOTIFICACAO,
	   :TITULO_EMAIL,
	   :REMETENTE_EMAIL);

                  
