DECLARE

	CURSOR C_FUNC IS
	
		SELECT INSCRICAO_FUNC.CODCONC CODCONC,
			   INSCRICAO_FUNC.CODFUNC CODFUNC,
			   INSCRICAO_FUNC.DATINSC DATINSC
		  FROM DBVESTIB.INSCRICAO_FUNC INSCRICAO_FUNC
		 WHERE INSCRICAO_FUNC.CODCONC = '3147'
			  AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.INSCRICAO_FUNC FUNC
				 WHERE FUNC.CODCONC = '3215'
					   AND FUNC.CODFUNC = INSCRICAO_FUNC.CODFUNC);

BEGIN
	FOR R_FUNC IN C_FUNC LOOP
	
		INSERT INTO DBVESTIB.INSCRICAO_FUNC
			(CODCONC,
			 CODFUNC,
			 DATINSC)
		VALUES
			('3215',
			 R_FUNC.CODFUNC,
			 SYSDATE);
		COMMIT;
	END LOOP;
END;
/*
DELETE FROM DBVESTIB.INSCRICAO_FUNC
 WHERE CODCONC = '3215'

	SELECT INSCRICAO_FUNC.CODCONC CODCONC,
		   INSCRICAO_FUNC.CODFUNC CODFUNC,
		   INSCRICAO_FUNC.DATINSC DATINSC
			FROM DBVESTIB.INSCRICAO_FUNC INSCRICAO_FUNC
		   WHERE INSCRICAO_FUNC.CODCONC = '3215'
				 AND EXISTS (SELECT 1
					FROM DBVESTIB.INSCRICAO_FUNC FUNC
				   WHERE FUNC.CODCONC IN ('3146',
										  '3147')
						 AND FUNC.CODFUNC = INSCRICAO_FUNC.CODFUNC);


SELECT count (INSCRICAO_FUNC.codfunc), codfunc
  FROM DBVESTIB.INSCRICAO_FUNC INSCRICAO_FUNC
 WHERE INSCRICAO_FUNC.CODCONC = '3215'
	   AND NOT EXISTS (SELECT 1
		  FROM DBVESTIB.INSCRICAO_FUNC FUNC
		 WHERE FUNC.CODCONC = '3146'
			   AND FUNC.CODFUNC = INSCRICAO_FUNC.CODFUNC)
               group by INSCRICAO_FUNC.codfunc
               having count (INSCRICAO_FUNC.codfunc)>1*/
               /*
               select count(f.codfunc) , codfunc
               from DBVESTIB.INSCRICAO_FUNC f
               where f.codconc = '3215'
               group by codfunc
               having count(f.codfunc)>1*/
