DECLARE
	CURSOR C_FOTO IS
		SELECT ALU.COD_ALUNO,
			   ALU.COD_PESSOA,
			   ALU.NUM_MATRICULA,
			   FOT.IND_VALIDADA, FOT.COD_USUARIO_LOG
		  FROM DBSIAF.ALUNO ALU
		 INNER JOIN DBSIAF.FOTO_PESSOA FOT
			ON FOT.COD_PESSOA = ALU.COD_PESSOA
			   AND FOT.COD_USUARIO_LOG IS NULL-- 
              AND FOT.IND_VALIDADA IS NULL
		 WHERE ALU.COD_INSTITUICAO = 8
			  -- AND ALU.COD_STA_ALUNO = 1
              -- AND ALU.COD_ALUNO= 1325590
               ;
BEGIN
	FOR R_FOTO IN C_FOTO LOOP
		UPDATE DBSIAF.FOTO_PESSOA FTP
		   SET FTP.IND_VALIDADA = 'S'
		 WHERE FTP.COD_PESSOA = R_FOTO.COD_PESSOA;
		COMMIT;
	END LOOP;
END;
