DECLARE
	CURSOR C_ALUNO IS
		SELECT COD_ALUNO,
			   CEP_ENDERECO,
			   ENA.COD_TPO_ENDERECO,
			   ENA.DAT_OPERACAO_LOG,
			   DECODE(CEP_ENDERECO,
					  NULL,
					  RPAD('X',
						   10,
						   'X'),
					  SUBSTR(F_CHAR_ESPECIAL(CEP_ENDERECO),
							 1,
							 2) || '.' || SUBSTR(F_CHAR_ESPECIAL(CEP_ENDERECO),
												 3,
												 3) || '-' || SUBSTR(F_CHAR_ESPECIAL(CEP_ENDERECO),
																	 6,
																	 3)) CEP_CERTO
		  FROM DBSIAF.END_ALUNO ENA
		 WHERE LENGTH(TRIM(ENA.CEP_ENDERECO)) = 8
			   AND TO_CHAR(DAT_OPERACAO_LOG,
						   'YYYY') = '2016';	

BEGIN
	FOR R_ALUNO IN C_ALUNO LOOP
		UPDATE DBSIAF.END_ALUNO ENA
		   SET ENA.CEP_ENDERECO = R_ALUNO.CEP_CERTO
		 WHERE ENA.COD_ALUNO = R_ALUNO.COD_ALUNO
			   AND ENA.COD_TPO_ENDERECO = R_ALUNO.COD_TPO_ENDERECO;               		
			COMMIT;
	END LOOP;
END;


