UPDATE DBVESTIB.PASSOS_INSCRICAO PAS
   SET PAS.COD_CNF_CONSULTA = 4396
 WHERE PAS.COD_TPO_CONCURSO = '72'
	   AND PAS.COD_PASSO_INSCRICAO = 273;

UPDATE DBVESTIB.TIPO_CONCURSO TIP
   SET TIP.COD_CNF_REL_COMPROVANTE = 137
 WHERE TIP.COD_TPO_CONCURSO = 72;

UPDATE DBVESTIB.PARAMETROS_CONCURSO PAC
   SET PAC.INDALTERADADOSINSCPAGA = 'S'
 WHERE PAC.CODCONC = '3150';
