DECLARE
	CURSOR C_DELETADOS IS
		SELECT *
		  FROM DBVESTIB.CLASSIFICACAO_CANDIDATO_LOG CLA
		 WHERE CLA.CODCONC = '3405'
			   AND CLA.IDT_OPERACAO_LOG = 'D'			   
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.CLASSIFICACAO_CANDIDATO CCC
				 WHERE CCC.CODCONC = CLA.CODCONC
					   AND CCC.CODCAN = CLA.CODCAN);
BEGIN
	FOR R_DELETADOS IN C_DELETADOS LOOP
	
		INSERT INTO DBVESTIB.CLASSIFICACAO_CANDIDATO
			(COD_CLASSIFICACAO,
			 COD_TPO_CLASSIFICACAO,
			 CODCONC,
			 CODCAN,
			 COD_ETAPA,
			 COD_STA_CLASSIFICACAO,
			 NROOPC,
			 NUM_POSICAO,
			 NUM_PONTOS,
			 IND_INCLUI_TREINANTES,
			 CODINSTITUICAO)
		VALUES
			(DBVESTIB.CLASSIFICACAO_CANDIDATO_S.NEXTVAL,
			 R_DELETADOS.COD_TPO_CLASSIFICACAO,
			 R_DELETADOS.CODCONC,
			 R_DELETADOS.CODCAN,
			 R_DELETADOS.COD_ETAPA,
			 R_DELETADOS.COD_STA_CLASSIFICACAO,
			 R_DELETADOS.NROOPC,
			 R_DELETADOS.NUM_POSICAO,
			 R_DELETADOS.NUM_PONTOS,
			 R_DELETADOS.IND_INCLUI_TREINANTES,
			 R_DELETADOS.CODINSTITUICAO);
             
		COMMIT;
	END LOOP;
     INSERT INTO DBVESTIB.CLASSIFICACAO_CANDIDATO
			(COD_CLASSIFICACAO,
			 COD_TPO_CLASSIFICACAO,
			 CODCONC,
			 CODCAN,
			 COD_ETAPA,
			 COD_STA_CLASSIFICACAO,
			 NROOPC,
			 NUM_POSICAO,
			 NUM_PONTOS,
			 IND_INCLUI_TREINANTES,
			 CODINSTITUICAO)
		VALUES
			(DBVESTIB.CLASSIFICACAO_CANDIDATO_S.NEXTVAL,
			 1,
			 '3405',
			 '167356',
			 1,
			 9,
			 '1',
			 1,
			 1,
			 'N',
			 9);
END;
