SELECT INS.CODINSC,
       INS.CODCONC,
	   INS.VALPAGO,
	   INS.COD_STATUS_INSCRICAO,
	   INS.DATINSCAN,
	   INS.DATPGTO,
	   INS.FORMA_INGRESSO
  FROM DBVESTIB.INSCRICAO INS
 WHERE INS.CODCONC = '1967'
	   AND INS.COD_STATUS_INSCRICAO <> 2
	   AND /*(EXISTS((SELECT 1
					FROM DBSIAF.MAPEAMENTO_INSCRICAO MI,
						 DBSIAF.MAPEAMENTO_TITULO    MT,
						 DBSIAF.TITULO_RECEBER       TR
				   WHERE MI.CODCONC = INS.CODCONC
						 AND MI.CODINSC = INS.CODINSC
						 AND MT.COD_MAPEAMENTO = MI.COD_MAPEAMENTO
						 AND MT.COD_TITULO_RECEBER = TR.COD_TITULO_RECEBER
						 AND TR.COD_STA_TITULO IN (3,
												   6))))
	   OR*/ EXISTS (SELECT 1
		  FROM DBSIAF.MAPEAMENTO_INSCRICAO MII
		 WHERE MII.CODCONC = INS.CODCONC
			   AND MII.CODINSC = INS.CODINSC
			   AND NOT EXISTS (SELECT 1
				  FROM DBSIAF.MAPEAMENTO_TITULO MTT
				 WHERE MTT.COD_MAPEAMENTO = MII.COD_MAPEAMENTO)
			   AND EXISTS (SELECT 1
				  FROM DBSIAF.TITULO_RECEBER           TRR,
					   DBVESTIB.DADOS_BOLETO_INSCRICAO DBI
				 WHERE TRR.NUM_NOSSO_NUMERO = DBI.NUMNOSSONUMERO
					   AND DBI.CODCONC = INS.CODCONC
					   AND DBI.CODINSC = INS.CODINSC))

/*
SELECT * FROM DBVESTIB.INSCRICAO I
WHERE I.CODINSC = '147721'                       */
