SELECT ALU.CODCONC "CONCURSO",
			   ALU.CODCAN ||'-'||UPPER(ALU.NOM_ALUNO) "CANDIDATO",
			   TIP.DSC_TPO_ENTRADA  "FORMA INGRESSO",
			   STA.DSC_STA_ALUNO "STATUS"
		  FROM DBSIAF.ALUNO ALU
		 INNER JOIN DBVESTIB.CONCURSO CON
			ON CON.CODCONC = ALU.CODCONC
         INNER JOIN DBSIAF.TIPO_ENTRADA TIP ON TIP.COD_TPO_ENTRADA = ALU.COD_TPO_ENTRADA
         INNER JOIN DBSIAF.STATUS_ALUNO STA ON STA.COD_STA_ALUNO = ALU.COD_STA_ALUNO
		 INNER JOIN DBVESTIB.PARAMETROS_CONCURSO PAR
			ON PAR.CODCONC = CON.CODCONC
			   AND PAR.IND_CONTRATO_INTERNO = 'S'
			   AND (PAR.INDENTREGACONTRATO = 'N' OR PAR.INDENTREGACONTRATO IS NULL)
			   AND NOT EXISTS (SELECT 1
				  FROM DBSIAF.ASS_CONTRATO ASS
				 INNER JOIN DBSIAF.ASS_DOCUMENTO ASD
					ON ASD.COD_ASS_CONTRATO = ASS.COD_ASS_CONTRATO
				 INNER JOIN DBSIAF.TIPO_DOCUMENTO TIP
					ON TIP.COD_TPO_DOCUMENTO = ASD.COD_TPO_DOCUMENTO
					   AND TIP.IND_LIBERA_CONTRATO = 'S'
					   AND TIP.COD_TPO_DOCUMENTO = 215
				 WHERE ASS.COD_ALUNO = ALU.COD_ALUNO)
			   AND ALU.COD_TPO_ENTRADA NOT IN (8,
											   67,
											   88,
											   3,
											   89,
											   62)
		 WHERE ALU.CODCONC = CON.CODCONC
			   AND CON.ANOCONC = 2016
			   AND CON.SEMCONC = 2
