DECLARE
	CURSOR C_CORRETO IS
		SELECT CAN.NOMCAN,
			   CAN.CODCONC,
			   CAN.CODCAN,
               (SELECT ins.nomcan
                  FROM DBVESTIB.INSCRICAO INS
                 WHERE INS.CPFCAN = CAN.CPFCAN
					   AND INS.CODINSC = CAN.CODCAN
					   AND UPPER(INS.NOMCAN) <> UPPER(CAN.NOMCAN))
		  FROM DBVESTIB.CANDIDATO CAN,
			   DBVESTIB.CONCURSO  CON
		 WHERE EXISTS (SELECT 1
				  FROM DBVESTIB.INSCRICAO INS
				 WHERE INS.CPFCAN = CAN.CPFCAN
					   AND INS.CODINSC = CAN.CODCAN
					   AND UPPER(INS.NOMCAN) <> UPPER(CAN.NOMCAN))
			   AND CON.CODCONC = CAN.CODCONC
			   AND CON.ANOCONC = 2013
			   AND CON.SEMCONC = 2;
BEGIN
	FOR R_CORRETO IN C_CORRETO LOOP
		DBVESTIB.SP_ATUALIZA_INSCRICAO(R_CORRETO.CODCONC,
									   R_CORRETO.CODCAN);
	END LOOP ;
    END;
