SELECT TAB.COD_CIDADE COD_CIDADE_MIN,
       TAB.NOM_CIDADE NOM_CIDADE_MIN,
       CID.COD_CIDADE,
       CID.NOM_CIDADE
  FROM (SELECT CID.COD_ESTADO,
       COD_MUNICIPIO,
       TRIM(UPPER(CID.NOM_CIDADE)) NOM_CIDADE,
       MIN(COD_CIDADE) COD_CIDADE,
       COUNT(1)
  FROM DBSIAF.CIDADE CID
 GROUP BY CID.COD_ESTADO,
       COD_MUNICIPIO,
       TRIM(UPPER(CID.NOM_CIDADE))
HAVING COUNT(1) > 1) TAB
JOIN DBSIAF.CIDADE CID ON (CID.COD_ESTADO = TAB.COD_ESTADO
                           AND CID.COD_MUNICIPIO = TAB.COD_MUNICIPIO
                           AND TRIM(UPPER(CID.NOM_CIDADE)) = TRIM(UPPER(TAB.NOM_CIDADE))
                           AND CID.COD_CIDADE <> TAB.COD_CIDADE)
