DECLARE
	CURSOR C_ALUNO IS
	
		SELECT A.COD_ALUNO
		-- count(a.cod_aluno) 
		  FROM DBSIAF.ALUNO A
		 WHERE A.COD_CTR_CUSTO_CAMPUS IS NULL;

BEGIN
	FOR R_ALUNO IN C_ALUNO LOOP
		DBINTEGRACAO.PC_MOV_CONTABIL.SP_ATUALIZA_CENTRO_CUSTO(R_ALUNO.COD_ALUNO);
	END LOOP;
END;
