DECLARE
	CURSOR C_CAN IS
		SELECT INS.CODCONC,
			   INS.CODINSC,
			   INS.COD_STATUS_INSCRICAO,
			   TR.COD_STA_TITULO,
			   MI.COD_MAPEAMENTO,
			   TR.COD_ALUNO,
			   TR.COD_TITULO_RECEBER
		  FROM DBVESTIB.INSCRICAO INS
		  JOIN DBVESTIB.CONCURSO CON
			ON INS.CODCONC = CON.CODCONC
		  JOIN DBSIAF.MAPEAMENTO_INSCRICAO MI
			ON MI.CODCONC = INS.CODCONC
			   AND MI.CODINSC = INS.CODINSC 
		  JOIN DBSIAF.MAPEAMENTO_TITULO MT
			ON MT.COD_MAPEAMENTO = MI.COD_MAPEAMENTO
		  JOIN DBSIAF.TITULO_RECEBER TR
			ON TR.COD_TITULO_RECEBER = MT.COD_TITULO_RECEBER
		 WHERE CON.ANOCONC = '2017'
			   AND INS.COD_STATUS_INSCRICAO = 2
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.CANDIDATO CAN
				 WHERE CAN.CODCONC = INS.CODCONC
					   AND CAN.CODCAN = INS.CODINSC);
             
               
	S_MSG_ERRO VARCHAR2(500);

BEGIN
	FOR R_CAN IN C_CAN LOOP
		IF R_CAN.COD_STA_TITULO <> 6 THEN
			DBVESTIB.SP_CONFIRMA_INSC_INTERNET(R_CAN.CODCONC,   
											   R_CAN.CODINSC);
			COMMIT;
		
		ELSE
		
			DBSIAF.PC_OPERACAO_TITULO.SP_OPERACAO_TITULO(R_CAN.COD_ALUNO,
														 R_CAN.COD_TITULO_RECEBER,
														 1,
														 408,
														 'N',
														 'S',
														 S_MSG_ERRO,
														 'S');
			COMMIT;
			DBVESTIB.SP_CONFIRMA_INSC_INTERNET(R_CAN.CODCONC,
											   R_CAN.CODINSC);
			COMMIT;
		END IF;
	END LOOP;
delete from dbvestib.tipo_informacao t
where t.cod_tipo_informacao in (
173, 174, 177, 178, 187, 188, 191, 192                    );
commit;
END;
