DECLARE
	CURSOR C_CANDIDATO_ORIGINAL IS
	
		SELECT &CONCURSO_DESTINO CONCURSO_DESTINO,
			   CAN.*,
			   RCA.CODCUR,
			   RCA.CODTUR,
			   RCA.OPCLIN,
			   RCA.CODCAM,
			   RCA.CODINSTITUICAO,
			   RCA.INDPRINCIPAL,
			   RCA.INDFORMACAOAMPLIADA,
			   RCA.INDPROUNI,
			   RCA.INDFIES,
			   RCA.IND_DESEJA_FIES,
			   RCA.IND_DESEJA_PROUNI,
			   RCA.NROOPC
		  FROM DBVESTIB.CANDIDATO CAN
		  JOIN DBVESTIB.RCANDCURTUROPC RCA
			ON CAN.CODCONC = RCA.CODCONC
			   AND CAN.CODCAN = RCA.CODCAN
			   AND RCA.NROOPC = '1'
		  JOIN DBVESTIB.CLASSIFICACAO_CANDIDATO CLA
			ON CAN.CODCONC = CLA.CODCONC
			   AND CAN.CODCAN = CLA.CODCAN
			   AND CLA.COD_STA_CLASSIFICACAO = 9
			   AND CLA.COD_ETAPA = 1
			   AND CLA.NROOPC = '1'
		 WHERE CAN.CODCONC IN (&CONCURSO_ORIGINAL)
			   AND CAN.CODCAN = NVL(NULL,
									CAN.CODCAN)
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.CANDIDATO CCC
				 WHERE CCC.CODCONC =  &CONCURSO_DESTINO
					   AND CCC.CODCAN = CAN.CODCAN)
			   AND EXISTS (SELECT 1
				  FROM DBVESTIB.RCURTUR RCU
				  JOIN DBVESTIB.CURSO_CAMPUS CCA
					ON CCA.CODCONC = RCU.CODCONC
					   AND CCA.CODCUR = RCA.CODCUR
				 WHERE RCU.CODCONC = &CONCURSO_DESTINO
					   AND RCU.CODCUR = RCA.CODCUR
					   AND RCU.CODTUR = RCA.CODTUR
					   AND CCA.CODCAM = RCA.CODCAM)
		
		UNION
		
		SELECT &CONCURSO_DESTINO CONCURSO_DESTINO,
			   CAN.*,
			   RCD.CODCUR,
			   RCA.CODTUR,
			   RCA.OPCLIN,
			   RCA.CODCAM,
			   RCA.CODINSTITUICAO,
			   RCA.INDPRINCIPAL,
			   RCA.INDFORMACAOAMPLIADA,
			   RCA.INDPROUNI,
			   RCA.INDFIES,
			   RCA.IND_DESEJA_FIES,
			   RCA.IND_DESEJA_PROUNI,
			   RCA.NROOPC
		  FROM DBVESTIB.CANDIDATO CAN
		  JOIN DBVESTIB.RCANDCURTUROPC RCA
			ON CAN.CODCONC = RCA.CODCONC
			   AND CAN.CODCAN = RCA.CODCAN
			   AND RCA.NROOPC = '1'
		  JOIN (SELECT DISTINCT RCU.CODCUR,
								OPC.CODCONC,
								OPC.CODCAN,
								OPC.INDPRINCIPAL,
								OPC.NROOPC,
								RCU.CODTUR,
								RCU.IND_DESEJA_PROUNI,
								RCU.IND_DESEJA_FIES,
								RCU.INDFIES,
								RCU.INDPROUNI,
								RCU.INDFORMACAOAMPLIADA,
								CCA.CODCAM,
								OPC.OPCLIN,
								OPC.CODINSTITUICAO
				  FROM DBVESTIB.RCANDCURTUROPC OPC
				  JOIN DBVESTIB.CURSO CUR
					ON OPC.CODCONC = CUR.CODCONC
					   AND OPC.CODCUR = CUR.CODCUR
				  JOIN DBVESTIB.RCURTUR RCU
					ON RCU.CODCONC = &CONCURSO_DESTINO
					   AND RCU.CODCUR <> OPC.CODCUR
					   AND RCU.CODTUR = OPC.CODTUR
				  JOIN DBVESTIB.CURSO_CAMPUS CCA
					ON CCA.CODCONC = RCU.CODCONC
					   AND CCA.CODCUR = RCU.CODCUR
					   AND CCA.CODCAM = OPC.CODCAM
				  JOIN DBVESTIB.CURSO CR2
					ON CR2.CODCONC = RCU.CODCONC
					   AND CR2.CODCUR = RCU.CODCUR
					   AND CR2.NOMCUR = CUR.NOMCUR) RCD
			ON CAN.CODCONC = RCD.CODCONC
			   AND CAN.CODCAN = RCD.CODCAN
			   AND RCD.NROOPC = '1'
		  JOIN DBVESTIB.CLASSIFICACAO_CANDIDATO CLA
			ON CAN.CODCONC = CLA.CODCONC
			   AND CAN.CODCAN = CLA.CODCAN
			   AND CLA.COD_STA_CLASSIFICACAO = 9
			   AND CLA.COD_ETAPA = 1
			   AND CLA.NROOPC = '1'
		 WHERE CAN.CODCONC IN (&CONCURSO_ORIGINAL)
			   AND CAN.CODCAN = NVL(NULL,
									CAN.CODCAN)
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.CANDIDATO CCC
				 WHERE CCC.CODCONC =  &CONCURSO_DESTINO
					   AND CCC.CODCAN = CAN.CODCAN)
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.RCURTUR RCU
				  JOIN DBVESTIB.CURSO_CAMPUS CCA
					ON CCA.CODCONC = RCU.CODCONC
					   AND CCA.CODCUR = RCA.CODCUR
				 WHERE RCU.CODCONC = &CONCURSO_DESTINO
					   AND RCU.CODCUR = RCA.CODCUR
					   AND RCU.CODTUR = RCA.CODTUR
					   AND CCA.CODCAM = RCA.CODCAM);
	MENSAGEM VARCHAR2(400);
BEGIN
	DELETE FROM DBVESTIB.LOG_ERROS_IMPORTACAO LOI
	 WHERE LOI.CODCONC = &CONCURSO_DESTINO;
     
	COMMIT;

	FOR R_CAN IN C_CANDIDATO_ORIGINAL LOOP
	
		BEGIN
		dbms_output.put_line(R_CAN.CODCONC ||' - '|| R_CAN.CODCAN||' - '|| R_CAN.NOMCAN ||' - '|| R_CAN.CPFCAN);
			INSERT INTO DBVESTIB.CANDIDATO
				(CODCONC,
				 CODCAN,
				 NOMCAN,
				 SEXCAN,
				 DATNASCAN,
				 IDECAN,
				 NOMIDECAN,
				 EXPIDECAN,
				 TELCAN,
				 ENDCAN,
				 BAICAN,
				 CIDCAN,
				 ESTCAN,
				 CEPCAN,
				 DATINSCAN,
				 DATPAGCAN,
				 CODLOCPAG,
				 EMAIL,
				 CANHOTO,
				 TAG,
				 CODCANANT,
				 REGFCH,
				 FLGMAT,
				 DATINCCAN,
				 str_SOCECO,
				 CODTPODEF,
				 IND_TREINANTE,
				 CODDIS,
				 NOM_PAI,
				 NOM_MAE,
				 IND_ALUNO_FUNCESI,
				 TIP_ESCOLA,
				 REG_EMPREGADO,
				 NOM_EMPREGADO,
				 LOC_TRABALHO,
				 CODCIDPROVA,
				 CODCIDESCOLHA,
				 CELCAN,
				 CPFCAN,
				 SERIECAN,
				 NOMEESC,
				 RAMAL,
				 NUMERO,
				 MATRICULA,
				 FORMA_INGRESSO,
				 ESCOLA_ORIGEM,
				 SENCAN,
				 TELESC,
				 NUMCRESP,
				 DSCCRESP,
				 NUMEQUIPE,
				 DSCEQUIPE,
				 INDUSATRANS,
				 INDQUANTPASSAGEM,
				 INDITIESCOLHIDO,
				 CODEMP,
				 INDLEESCREVE,
				 ENDESC,
				 COMPLEMENTO,
				 NUMEND,
				 COD_LOC_INSCRICAO,
				 COD_FIS_INSCRICAO,
				 NOM_SETOR,
				 VALPAGO,
				 INDCONFIRMADO,
				 BAIESC,
				 CEPESC,
				 CIDESC,
				 NUM_ESCOLA,
				 COMPLEMENTO_ESCOLA,
				 COD_INSTIT_EXTERNA,
				 CODCAMPROXRESIDENCIA,
				 CODFORMAPROVA,
				 ANOENEM,
				 NUMINSCENEM,
				 DATPROVAAGENDADA,
				 CODESTADOCIVIL,
				 CODPAISNC,
				 CODCIDADENAT,
				 TELCOMERCIAL,
				 INDTRABALHA,
				 CODESCOLA,
				 EMAIL_ALTERNATIVO,
				 NOMCURSOGRADUACAO,
				 ANOCONCLUSAOEM,
				 COD_ESCOLA_ORIGEM,
				 COD_CURSINHO,
				 NOMCURSINHOOUTRO,
				 COD_EMP_CONVENIADAS,
				 CODBARRAS,
				 COD_GRD_CURRICULAR,
				 COD_GRD_QUALIFICACAO,
				 COD_OCORRENCIA,
				 COD_INSTITUICAO_PSVS)
			VALUES
				(R_CAN.CONCURSO_DESTINO,
				 R_CAN.CODCAN,
				 R_CAN.NOMCAN,
				 R_CAN.SEXCAN,
				 R_CAN.DATNASCAN,
				 R_CAN.IDECAN,
				 R_CAN.NOMIDECAN,
				 R_CAN.EXPIDECAN,
				 R_CAN.TELCAN,
				 R_CAN.ENDCAN,
				 R_CAN.BAICAN,
				 R_CAN.CIDCAN,
				 R_CAN.ESTCAN,
				 R_CAN.CEPCAN,
				 R_CAN.DATINSCAN,
				 R_CAN.DATPAGCAN,
				 R_CAN.CODLOCPAG,
				 R_CAN.EMAIL,
				 R_CAN.CANHOTO,
				 R_CAN.TAG,
				 R_CAN.CODCANANT,
				 R_CAN.REGFCH,
				 R_CAN.FLGMAT,
				 R_CAN.DATINCCAN,
				 R_CAN.STR_SOCECO,
				 R_CAN.CODTPODEF,
				 R_CAN.IND_TREINANTE,
				 R_CAN.CODDIS,
				 R_CAN.NOM_PAI,
				 R_CAN.NOM_MAE,
				 R_CAN.IND_ALUNO_FUNCESI,
				 R_CAN.TIP_ESCOLA,
				 R_CAN.REG_EMPREGADO,
				 R_CAN.NOM_EMPREGADO,
				 R_CAN.LOC_TRABALHO,
				 R_CAN.CODCIDPROVA,
				 R_CAN.CODCIDESCOLHA,
				 R_CAN.CELCAN,
				 R_CAN.CPFCAN,
				 R_CAN.SERIECAN,
				 R_CAN.NOMEESC,
				 R_CAN.RAMAL,
				 R_CAN.NUMERO,
				 R_CAN.MATRICULA,
				 R_CAN.FORMA_INGRESSO,
				 R_CAN.ESCOLA_ORIGEM,
				 R_CAN.SENCAN,
				 R_CAN.TELESC,
				 R_CAN.NUMCRESP,
				 R_CAN.DSCCRESP,
				 R_CAN.NUMEQUIPE,
				 R_CAN.DSCEQUIPE,
				 R_CAN.INDUSATRANS,
				 R_CAN.INDQUANTPASSAGEM,
				 R_CAN.INDITIESCOLHIDO,
				 R_CAN.CODEMP,
				 R_CAN.INDLEESCREVE,
				 R_CAN.ENDESC,
				 R_CAN.COMPLEMENTO,
				 R_CAN.NUMEND,
				 R_CAN.COD_LOC_INSCRICAO,
				 NULL, --R_CAN.COD_FIS_INSCRICAO,
				 R_CAN.NOM_SETOR,
				 R_CAN.VALPAGO,
				 R_CAN.INDCONFIRMADO,
				 R_CAN.BAIESC,
				 R_CAN.CEPESC,
				 R_CAN.CIDESC,
				 R_CAN.NUM_ESCOLA,
				 R_CAN.COMPLEMENTO_ESCOLA,
				 R_CAN.COD_INSTIT_EXTERNA,
				 R_CAN.CODCAMPROXRESIDENCIA,
				 R_CAN.CODFORMAPROVA,
				 R_CAN.ANOENEM,
				 R_CAN.NUMINSCENEM,
				 R_CAN.DATPROVAAGENDADA,
				 R_CAN.CODESTADOCIVIL,
				 R_CAN.CODPAISNC,
				 R_CAN.CODCIDADENAT,
				 R_CAN.TELCOMERCIAL,
				 R_CAN.INDTRABALHA,
				 R_CAN.CODESCOLA,
				 R_CAN.EMAIL_ALTERNATIVO,
				 R_CAN.NOMCURSOGRADUACAO,
				 R_CAN.ANOCONCLUSAOEM,
				 R_CAN.COD_ESCOLA_ORIGEM,
				 R_CAN.COD_CURSINHO,
				 R_CAN.NOMCURSINHOOUTRO,
				 R_CAN.COD_EMP_CONVENIADAS,
				 R_CAN.CODBARRAS,
				 R_CAN.COD_GRD_CURRICULAR,
				 R_CAN.COD_GRD_QUALIFICACAO,
				 R_CAN.COD_OCORRENCIA,
				 R_CAN.COD_INSTITUICAO_PSVS);
		
			INSERT INTO DBVESTIB.RCANDCURTUROPC
				(CODCONC,
				 CODCAN,
				 CODCUR,
				 CODTUR,
				 NROOPC,
				 OPCLIN,
				 INDFORMACAOAMPLIADA,
				 INDPROUNI,
				 INDFIES,
				 CODCAM,
				 CODINSTITUICAO,
				 IND_DESEJA_PROUNI,
				 IND_DESEJA_FIES)
			VALUES
				(R_CAN.CONCURSO_DESTINO,
				 R_CAN.CODCAN,
				 R_CAN.CODCUR,
				 R_CAN.CODTUR,
				 R_CAN.NROOPC,
				 R_CAN.OPCLIN,
				 R_CAN.INDFORMACAOAMPLIADA,
				 R_CAN.INDPROUNI,
				 R_CAN.INDFIES,
				 R_CAN.CODCAM,
				 R_CAN.CODINSTITUICAO,
				 R_CAN.IND_DESEJA_PROUNI,
				 R_CAN.IND_DESEJA_FIES);
			COMMIT;
		
			IF R_CAN.CODFORMAPROVA = 1 THEN
				INSERT INTO DBVESTIB.NOTA_PROVA
					(CODNOTAPROVA,
					 CODCONC,
					 CODCAN,
					 NROOPC,
					 COD_ETAPA,
					 CODPRO,
					 NOTAPARCIAL,
					 NOTAFINAL)
					SELECT DBVESTIB.NOTA_PROVA_S.NEXTVAL,
						   R_CAN.CONCURSO_DESTINO,
						   NPR.CODCAN,
						   NPR.NROOPC,
						   1,
						   NPR.CODPRO,
						   NPR.NOTAPARCIAL,
						   NPR.NOTAFINAL
					  FROM DBVESTIB.NOTA_PROVA NPR
					 WHERE NPR.CODCONC = R_CAN.CODCONC
						   AND NPR.CODCAN = R_CAN.CODCAN
						   AND NPR.NROOPC = '1';
				COMMIT;
			
			ELSE
			
				INSERT INTO DBVESTIB.NOTAENEM
					(CODCONC,
					 CODCAN,
					 CODPRO,
					 VALNOTA)
					SELECT R_CAN.CONCURSO_DESTINO,
						   R_CAN.CODCAN,
						   NOE.CODPRO,
						   NOE.VALNOTA
					  FROM DBVESTIB.NOTAENEM NOE
					 WHERE NOE.CODCONC = R_CAN.CODCONC
						   AND NOE.CODCAN = R_CAN.CODCAN;
			
				COMMIT;
			
			END IF;
		
		EXCEPTION
			WHEN OTHERS THEN
				MENSAGEM := SQLERRM;
				INSERT INTO DBVESTIB.LOG_ERROS_IMPORTACAO
					(CODCONC,
					 CODCAN,
					 COD_ERRO,
					 DSC_ERRO)
				VALUES
					(R_CAN.CONCURSO_DESTINO,
					 R_CAN.CODCAN,
					 1,
					 MENSAGEM);
				COMMIT;
		END;
	END LOOP;
    /*
    DBVESTIB.PC_CLASSIFICACAO.SP_CLASSIFICAR_INSTITUICOES(&P_CODCONC_DES,
                                                          1, -- tpo_classificação
                                                          '1', -- opcao de curso
                                                          1, -- etapa
                                                          'N', --inclui treinantes
                                                          'S', --processa resultado
                                                          'S', --processa desistente
                                                          NULL, --codcan
                                                          'S' -- ind_commit
                                                          );*/


END;
