DECLARE

    CURSOR C_IES IS
        SELECT IES.COD_INSTITUICAO
          FROM DBSIAF.INSTITUICAO_ENSINO IES;

    CURSOR C_CAM(P_CODIES DBSIAF.INSTITUICAO_ENSINO.COD_INSTITUICAO%TYPE) IS
        SELECT CAM.COD_CAMPUS
          FROM DBSIAF.CAMPUS CAM
         WHERE CAM.COD_INSTITUICAO = P_CODIES
         AND CAM.IND_ATIVO = 'S';

    CURSOR C_USUARIO(P_CODIES DBSIAF.INSTITUICAO_ENSINO.COD_INSTITUICAO%TYPE) IS
        SELECT USU.COD_USUARIO
          FROM DBADM.USUARIO_INSTITUICAO USU,
               DBSIAF.BASE_FUNCIONARIO   BAS,
               DBADM.USUARIO             UUU
         WHERE BAS.CPF_FUNCIONARIO = UUU.CPF_USUARIO
               AND BAS.IND_ATIVO = 'S'
               AND USU.COD_INSTITUICAO = P_CODIES
               AND UUU.COD_USUARIO = USU.COD_USUARIO;
               
    VALIDA NUMBER;
BEGIN
    FOR R_IES IN C_IES LOOP
        FOR R_USU IN C_USUARIO(R_IES.COD_INSTITUICAO) LOOP
            FOR R_CAM IN C_CAM(R_IES.COD_INSTITUICAO) LOOP
                VALIDA := 0;
                SELECT COUNT(1)
                  INTO VALIDA
                  FROM DBSIAF.CAMPUS_FUNCIONARIO CAM
                 WHERE CAM.COD_FUNCIONARIO = R_USU.COD_USUARIO
                       AND CAM.COD_CAMPUS = R_CAM.COD_CAMPUS;
                IF VALIDA = 0 THEN
                    INSERT INTO DBSIAF.CAMPUS_FUNCIONARIO
                        (COD_FUNCIONARIO,
                         COD_CAMPUS)
                    VALUES
                        (R_USU.COD_USUARIO,
                         R_CAM.COD_CAMPUS);
                END IF;
            END LOOP;
        END LOOP;
    END LOOP;
END;
