insert into dbvestib.tipo_concurso(cod_tpo_concurso,dsc_concurso,sgl_concurso,ind_gerar_financeiro,ind_gerar_matricula,ind_insc_web,ind_verifica_qualif,ind_solicita_reserva,ind_verifica_nat_disciplina,end_web_inscricao,end_web_insc_teste,end_web_insc_func,end_web_insc_func_teste,cod_cnf_rel_comprovante,codgru,codformalogin,end_segunda_via_boleto,indformaingressoobrig,indativo,ind_centro_custo_curso,cod_tpo_lancamento,ind_permite_mult_insc,ind_aproveita_dados_aluno,ind_possui_turma,
ind_aproveita_dados_aluno_cpf,ind_forma_parcelamento,cod_tpo_aluno,num_chamado_hd,cod_tpo_login)

select dbvestib.tipo_concurso_s.nextval,'Processo Seletivo Pós-graduação - EAD EBRADI',sgl_concurso,ind_gerar_financeiro,ind_gerar_matricula,ind_insc_web,ind_verifica_qualif,ind_solicita_reserva,ind_verifica_nat_disciplina,end_web_inscricao,end_web_insc_teste,end_web_insc_func,end_web_insc_func_teste,cod_cnf_rel_comprovante,codgru,codformalogin,end_segunda_via_boleto,indformaingressoobrig,indativo,ind_centro_custo_curso,cod_tpo_lancamento,ind_permite_mult_insc,ind_aproveita_dados_aluno,ind_possui_turma,
ind_aproveita_dados_aluno_cpf,ind_forma_parcelamento,cod_tpo_aluno,num_chamado_hd,cod_tpo_login
 from dbvestib.tipo_concurso tpo
 where tpo.cod_tpo_concurso = '76' ;
 
 insert into dbvestib.passos_inscricao(cod_passo_inscricao,cod_tpo_concurso,end_tela,dsc_tela,ord_passo,cod_cnf_consulta,ind_exibir,dsc_funcao_before,dsc_funcao_after)
 select dbvestib.passos_inscricao_s.nextval,'99',end_tela,dsc_tela,ord_passo,cod_cnf_consulta,ind_exibir,dsc_funcao_before,dsc_funcao_after from dbvestib.passos_inscricao pas
 where pas.cod_tpo_concurso= '76';
 
