
             
INSERT INTO DBVESTIB.CONFIG_IMPORTA_GABARITO CC (CODCONC,NOMCAMPO,ORDCAMPO,INDATIVO,VLRDEFAULT,DSC_CAMPO)
VALUES --('1588', 'CODCONC', 1, 'S', NULL, 'CÓDIGO DO CONCURSO') 
-- ('1588', 'CODCAD', 2, 'S', NULL, 'CADERNO')
-- ('1588', 'OPCLIN', 3, 'S', NULL, 'OPÇÃO DE LÍNGUA')
 ('1588', 'RESPGAB', 4, 'S', NULL, 'GABARITO')
