SELECT 
       INS.COD_INSTITUICAO,
       ENS.sglinstituicao Instituicao,
       INS.COD_TPO_CONCURSO ,
       TIC.DSC_CONCURSO "Tipo concurso", 
       INS.COD_PASSO_INSCRICAO,
       PIN.DSC_TELA Passo,
       INS.CODCONC,
       CON.NOMCONC Concurso,
       INS.DSC_SCRIPT Script,
       INS.COD_LOCAL_HTML "local"
  FROM DBVESTIB.SCRIPT_PASSOS_INSCRICAO INS
  INNER JOIN DBVESTIB.INSTITUICAO_ENSINO ENS ON INS.COD_INSTITUICAO = ENS.CODINSTITUICAO
  LEFT JOIN DBVESTIB.TIPO_CONCURSO TIC ON INS.COD_TPO_CONCURSO = TIC.COD_TPO_CONCURSO
  LEFT JOIN DBVESTIB.PASSOS_INSCRICAO PIN ON INS.COD_PASSO_INSCRICAO = PIN.COD_PASSO_INSCRICAO
  LEFT JOIN DBVESTIB.CONCURSO CON ON INS.CODCONC = CON.CODCONC
  
  
select * from   dbvestib.vw_concursos_web

 -- dbsiaf.pc_processamento_deferimento.SP_PROCESSA_CANDIDATO(           
