-- Query do Sol Funcionário -  Verifica se o Vestib encontra o atendente call-center
SELECT TEL.CODTEL,
		 TEL.NOMTEL,
		 TEL.SENHA,
		 TEL.COD_USUARIO,
		 SUBSTR(DBSIAF.F_NOM_FUNCIONARIO(TEL.COD_USUARIO),
				1,
				200) FUNCIONARIO,
		 TEL.CODINSTITUICAO,
		 INS.DSCINSTITUICAO,
		 INS.SGLINSTITUICAO,
		 TEL.IND_ATIVO,
		 TEL.IND_PERM_DEL_CLIENTE,
		 SUBSTR(DBSIAF.F_NOM_FUNCIONARIO(TEL.COD_USUARIO_LOG),
				1,
				200) NOM_FUNCIONARIO_LOG,
		 TEL.DAT_OPERACAO_LOG
	FROM DBTELEMAR.TELEFONISTA       TEL,
		 DBVESTIB.INSTITUICAO_ENSINO INS
   WHERE TEL.CODINSTITUICAO = INS.CODINSTITUICAO
		 AND UPPER(TEL.NOMTEL) LIKE 'FABIA%'
   ORDER BY TEL.NOMTEL;
   
   -- Verifica se o fiscal foi cadastrado , conferir os dados do CODTEL e COD_USUARIO
   SELECT * FROM DBVESTIB.FISCAL_INSCRICAO FIS
   WHERE /*FIS.CODTEL = 16020 
   AND*/ CODCONC = '2178';
   
   -- Verifica se o CODTEL e COD_USUARIO é o mesmo do fiscal do vestib
   SELECT * FROM DBTELEMAR.TELEFONISTA TEL
   WHERE TEL.CODTEL = 5417;
   
   
   
   	SELECT COD_FIS_INSCRICAO,
				   NOMFISCAL,
				   CPFFISCAL,
				   CODTPOFISCAL,
				   '2179',
				   COD_USUARIO
			  FROM DBVESTIB.FISCAL_INSCRICAO FIN
			 WHERE FIN.CODCONC = '2160'
				   AND NOT EXISTS (SELECT 1
					  FROM DBVESTIB.FISCAL_INSCRICAO FIN1
					 WHERE FIN.COD_FIS_INSCRICAO = FIN1.COD_FIS_INSCRICAO
						   AND FIN1.CODCONC = '2179');
                           
		   
		   SELECT TEL.CODTEL,
				  USU.COD_USUARIO
			 FROM DBTELEMAR.TELEFONISTA TEL,
				  DBADM.USUARIO         USU
			WHERE TEL.IND_ATIVO = 'S'
				  AND TEL.COD_USUARIO = USU.COD_USUARIO
				  AND LPAD(DBSIAF.F_SO_NUMERO(USU.CPF_USUARIO),
						   11,
						   0) = '09994478664'
				  AND ROWNUM = 1;                
                
                
                
                
                
				
				SELECT TEL.CODTEL,
					   TEL.NOMTEL,
					   TEL.SENHA,
					   TEL.COD_USUARIO,
					   SUBSTR(DBSIAF.F_NOM_FUNCIONARIO(TEL.COD_USUARIO),
							  1,
							  200) FUNCIONARIO,
					   TEL.CODINSTITUICAO,
					   INS.DSCINSTITUICAO,
					   INS.SGLINSTITUICAO,
					   TEL.IND_ATIVO,
					   TEL.IND_PERM_DEL_CLIENTE,
					   SUBSTR(DBSIAF.F_NOM_FUNCIONARIO(TEL.COD_USUARIO_LOG),
							  1,
							  200) NOM_FUNCIONARIO_LOG,
					   TEL.DAT_OPERACAO_LOG
				  FROM DBTELEMAR.TELEFONISTA       TEL,
					   DBVESTIB.INSTITUICAO_ENSINO INS
				 WHERE TEL.CODINSTITUICAO = INS.CODINSTITUICAO
					   AND UPPER(DBSIAF.F_NOM_FUNCIONARIO(TEL.COD_USUARIO)) LIKE 'THAY%'
					   AND UPPER(TEL.SENHA) LIKE '%'
				 ORDER BY TEL.NOMTEL
