
INSERT INTO DBSAG.HIST_AGENDAMENTO
(COD_HIST_AGENDAMENTO, COD_MAPEAMENTO_CLIENTE, COD_DISPONIBILIDADE, COD_STATUS)
SELECT /*DBSAG.HIST_AGENDAMENTO_S.NEXTVAL,*/ AG.COD_MAPEAMENTO_CLIENTE, AG.COD_DISPONIBILIDADE, AG.COD_STATUS
FROM
    DBSAG.AGENDAMENTO AG,
    DBSAG.STATUS_AGENDAMENTO ST,
    DBSAG.DISPONIBILIDADE_PESSOA DP,
    DBSAG.PESSOA_PROCESSO PP
WHERE
     AG.COD_STATUS = ST.COD_STATUS
     AND AG.COD_DISPONIBILIDADE = DP.COD_DISPONIBILIDADE
     AND DP.COD_PESSOA_PROCESSO = PP.COD_PESSOA_PROCESSO
     AND ST.IND_PODE_REAGENDAR = 'S'
     AND PP.COD_PROCESSO = 80
    -- AND AG.COD_MAPEAMENTO_CLIENTE = 90245
     and st.cod_status = 2;


DELETE FROM
    DBSAG.AGENDAMENTO AG
WHERE
AG.COD_AGENDAMENTO IN
(
    SELECT AG2.COD_AGENDAMENTO
    FROM
      DBSAG.AGENDAMENTO AG2,
      DBSAG.STATUS_AGENDAMENTO ST,
      DBSAG.DISPONIBILIDADE_PESSOA DP,
      DBSAG.PESSOA_PROCESSO PP
    WHERE
         AG2.COD_STATUS = ST.COD_STATUS
         AND AG2.COD_DISPONIBILIDADE = DP.COD_DISPONIBILIDADE
         AND DP.COD_PESSOA_PROCESSO = PP.COD_PESSOA_PROCESSO
         AND ST.IND_PODE_REAGENDAR = 'S'
         AND PP.COD_PROCESSO = 80
         and st.cod_status = 2
        -- AND AG2.COD_MAPEAMENTO_CLIENTE = 90245
);


GRANT EXECUTE ON DBSAG.PC_AGENDAMENTO TO DESENV
