DECLARE
	CURSOR C_ALUNO IS
	
		SELECT C.NOM_CIDADE,
			   A.CODCONC, 
			   A.CODCAN,
			   A.COD_CIDADE,
			   I.CODCIDADE,               
			   A.NUM_MATRICULA,
			   A.COD_ALUNO,
               a.cod_
		  FROM DBSIAF.ALUNO       A,
			   DBSIAF.CIDADE      C,
			   DBVESTIB.INSCRICAO I,
			   DBVESTIB.CONCURSO  CON
		 WHERE C.COD_CIDADE = A.COD_CIDADE
			   AND I.CODCONC = A.CODCONC
			   AND I.CODINSC = A.CODCAN
			   AND A.COD_CIDADE = 1
			   AND CON.CODCONC = A.CODCONC
			   AND CON.COD_TPO_CONCURSO = 1
			   AND CON.ANOCONC BETWEEN 2011 AND 2014;

BEGIN
	FOR R_ALUNO IN C_ALUNO LOOP
		IF R_ALUNO.CODCIDADE <> 1 THEN
			UPDATE DBSIAF.ALUNO A
			   SET A.COD_CIDADE = R_ALUNO.CODCIDADE
			 WHERE A.COD_ALUNO = R_ALUNO.COD_ALUNO;
		END IF;
	END LOOP;
END;
