DECLARE
	CURSOR C_PAGO IS
		SELECT distinct(INS.CODINSC),
			   INS.CODCONC,
			   INS.COD_STATUS_INSCRICAO
		  FROM DBSIAF.MAPEAMENTO_INSCRICAO MIS,
			   DBSIAF.MAPEAMENTO_TITULO    A,
			   DBSIAF.TITULO_RECEBER       T,
			   DBVESTIB.INSCRICAO          INS
		 WHERE MIS.COD_MAPEAMENTO = A.COD_MAPEAMENTO
			   AND T.COD_TITULO_RECEBER = A.COD_TITULO_RECEBER
			   AND T.COD_STA_TITULO = 6
			   AND INS.CODCONC = MIS.CODCONC
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.CANDIDATO CAN
				 WHERE CAN.CODCONC = INS.CODCONC
					   AND CAN.CODCAN = INS.CODINSC);

	CURSOR C_INSCRICAO IS
		SELECT DISTINCT INS.FORMA_INGRESSO,
						INS.CODINSC,
						INS.CODCONC,
						INS.COD_STATUS_INSCRICAO,
						IL.FORMA_INGRESSO FORMA_CORRETA,
						INS.DAT_OPERACAO_LOG,
						INS.DATPGTO,
						INS.VALPAGO
		  FROM DBVESTIB.INSCRICAO     INS,
			   DBVESTIB.INSCRICAO_LOG IL
		 WHERE INS.FORMA_INGRESSO = 0
			   AND IL.CODCONC = INS.CODCONC
			   AND IL.CODINSC = INS.CODINSC
			   AND IL.DAT_OPERACAO_LOG = (SELECT DISTINCT MAX(IL.DAT_OPERACAO_LOG)
											FROM DBVESTIB.INSCRICAO_LOG LL
										   WHERE LL.CODCONC = INS.CODCONC
												 AND IL.CODINSC = INS.CODINSC
												 AND IL.FORMA_INGRESSO <> INS.FORMA_INGRESSO);
	CONTA integer;
BEGIN
	CONTA := 0;
	FOR R_PAGO IN C_PAGO LOOP
	
		DELETE DBSIAF.MAPEAMENTO_INSCRICAO M
		 WHERE M.CODCONC = R_PAGO.CODCONC
			   AND M.CODINSC = R_PAGO.CODINSC;
		CONTA := CONTA + 1;
		IF CONTA = 10 THEN
			COMMIT;
		END IF;
	END LOOP;

	CONTA := 0;
	FOR R_INSCRICAO IN C_INSCRICAO LOOP
		IF R_INSCRICAO.FORMA_CORRETA <> 0 THEN
			UPDATE DBVESTIB.INSCRICAO INS
			   SET INS.FORMA_INGRESSO = R_INSCRICAO.FORMA_CORRETA
			 WHERE INS.CODCONC = R_INSCRICAO.CODCONC
				   AND INS.CODINSC = R_INSCRICAO.CODINSC;
			CONTA := CONTA + 1;
			IF CONTA = 10 THEN
				COMMIT;
			END IF;
		END IF;
	END LOOP;
	COMMIT;
END;
