SELECT DC.COD_DIARIO_CLASSE CODDIARIOCLASSE,
	   DI.COD_DISCIPLINA CODDISCIPLINA,
	   DC.COD_GRD_HORARIO AS CODGRDHORARIO,
	   DI.NOM_DISCIPLINA NOMDISCIPLINA,
	   DC.IDT_TURMA IDTTURMA,
	   TO_CHAR(PL.DAT_INI_PERIODO,
			   'DD/MM/YYYY') DATINIPERIODO,
	   TO_CHAR(PL.DAT_FIM_PERIODO,
			   'DD/MM/YYYY') DATFIMPERIODO,
	   DI.NOM_DISCIPLINA || ' - ' || DC.IDT_TURMA NOMDISCIPLINATURMA,
	   DC.IDT_TURMA || ' - ' || DI.NOM_DISCIPLINA NOMTURMADISCIPLINA,
	   DECODE(DC.COD_STA_DIARIO,
			  1,
			  'S',
			  2,
			  'S',
			  6,
			  'S',
			  3,
			  NULL,
			  5,
			  NULL) AS INDSTATUSDISPONIVEL,
	   PL.SGL_PERIODO_LETIVO SGLPERIODOLETIVO,
	   PL.COD_PERIODO_LETIVO CODPERIODOLETIVO,
	   PL.IND_FECHADO AS INDFECHADO,
	   (SELECT SUM(1)
		  FROM DBSIAF.FORMA_AVALIACAO FAV,
			   DBSIAF.PLANO_AVALIACAO PAV,
			   DBSIAF.AVAL_PLANO_AULA APA
		 WHERE PAV.COD_PERIODO_LETIVO = DC.COD_PERIODO_LETIVO
			   AND FAV.COD_PLANO_AVALIACAO = PAV.COD_PLANO_AVALIACAO
			   AND FAV.IND_LIBERACAO_PROFESSOR = 'N'
			   AND PAV.COD_PLANO_AVALIACAO = DBSIAF.PC_PLANO_AVALIACAO.F_PLANO_AVALIACAO_DIARIO(DC.COD_DIARIO_CLASSE)
			   AND 0 <= (SELECT SUM(VAL_AVALIACAO)
						   FROM DBSIAF.AVAL_ALUNO AVA
						  WHERE AVA.COD_DIARIO_CLASSE = DC.COD_DIARIO_CLASSE
								AND APA.COD_DIARIO_CLASSE = DC.COD_DIARIO_CLASSE
								AND AVA.COD_AVAL_PLANO = APA.COD_AVAL_PLANO
								AND APA.COD_TPO_AVALIACAO = FAV.COD_TPO_AVALIACAO
                                AND FAV.COD_TPO_AVALIACAO <> 77)) AS INDMUDARSTATUS

  FROM DBSIAF.DIARIO_CLASSE      DC,
	   DBSIAF.DISCIPLINA         DI,
	   DBSIAF.PROFESSOR          PR,
	   DBSIAF.PERIODO_LETIVO     PL,
	   DBSIAF.TIPO_CARGA_HORARIA TC,
	   DBSIAF.STATUS_DIARIO      SD,
	   DBSIAF.GRADE_HORARIO      GH
 WHERE DC.COD_DISCIPLINA = DI.COD_DISCIPLINA
	   AND DC.COD_GRD_HORARIO = GH.COD_GRD_HORARIO
	   AND GH.IND_ATIVO = 'S'
	   AND DC.COD_PROFESSOR = PR.COD_PROFESSOR
	   AND DC.COD_PERIODO_LETIVO = PL.COD_PERIODO_LETIVO
	   AND ((PL.IND_FECHADO = 'N' AND PL.IND_LIBERADO = 'S') OR EXISTS (SELECT 1
																		  FROM PARAMETRO_AVAL_DIARIO PAV
																		 WHERE PAV.COD_DIARIO_CLASSE = DC.COD_DIARIO_CLASSE
																			   AND PAV.DAT_LIMITE_ENTREGA > SYSDATE))
	   AND DC.COD_TPO_CHORARIA = TC.COD_TPO_CHORARIA
	   AND PR.COD_PROFESSOR = 61507
	   AND SD.COD_STA_DIARIO = DC.COD_STA_DIARIO
	   AND SD.IND_PUBLICACAO = 'S'
 ORDER BY PL.COD_PERIODO_LETIVO DESC;
