SELECT *
  FROM ALL_CONS_COLUMNS A
  JOIN ALL_CONSTRAINTS C
	ON A.CONSTRAINT_NAME = C.CONSTRAINT_NAME
 WHERE /*C.CONSTRAINT_TYPE = 'R'
	   AND*/ UPPER(A.CONSTRAINT_NAME) LIKE UPPER('IX_PESSOA_CPF%')
SELECT *
  FROM ALL_CONS_COLUMNS A
  WHERE/* A.OWNER = 'DBSIAF'
  --AND A.COLUMN_NAME = 'COD_CIDADE'
  AND */UPPER(A.CONSTRAINT_NAME) LIKE UPPER('IX_PESSOA_CPF%')
  
  
  SELECT *FROM DBCEP.LOCALIDADE L

SELECT *
  FROM ALL_CONS_COLUMNS A
  WHERE A.OWNER = 'DBINSCPOS'
  AND A.COLUMN_NAME = 'COD_CIDADE';
  
  
  SELECT * FROM DBSIAF.MUTANTE_TABLE
