DECLARE
	CURSOR C_ALUNO IS
	
		SELECT A.NUM_MATRICULA,
			   A.COD_ALUNO,
			   A.CODCONC,
			   A.CODCAN
		  FROM DBSIAF.ALUNO A
		 WHERE A.CODCONC = '1766';
BEGIN
	FOR R_ALUNO IN C_ALUNO LOOP
		BEGIN
			DBVESTIB.PC_CONCURSO.SP_EXCLUIR_ALUNO(R_ALUNO.CODCONC,
												  R_ALUNO.COD_ALUNO);
		END;
	END LOOP;
END;

