DECLARE
	CURSOR C_CURSO IS
		SELECT  RCU.CODCONC, RCU.CODCUR, RCU.CODTUR, RCU.CODCAM
		  FROM DBVESTIB.RCURTUR            RCU,
			   DBVESTIB.CURSO_CAMPUS       CCA,
			   DBVESTIB.CAMPUS             CAM,
			  DBVESTIB.INSTITUICAO_ENSINO IES
		 WHERE RCU.CODCONC = '2189'
			   AND CCA.CODCONC = RCU.CODCONC
			   AND CCA.CODCUR = RCU.CODcur
			   AND CAM.CODCAM = CCA.CODCAM
			   --AND RCU.INDINSCRICAO = 'S'
			   AND IES.CODINSTITUICAO = CAM.CODINSTITUICAO;
			  /* AND IES.CODINSTITUICAO =1IN (7,
										  5,
										  9);*/
BEGIN

	FOR R_CURSO IN C_CURSO LOOP
      BEGIN
		UPDATE DBVESTIB.RCURTUR R
		   SET R.Valins = 0
		 WHERE R.CODCONC = R_CURSO.CODCONC
			   AND R.CODCUR = R_CURSO.CODCUR
			   AND R.CODTUR = R_CURSO.CODTUR
			   AND R.CODCAM = R_CURSO.CODCAM;
       EXCEPTION
       WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR (-20500, R_CURSO.CODCUR)  ;
               END;
	END LOOP;
END;
