
INSERT INTO DBSIAF.TIPO_PARAMETRO_INST
	(COD_TPO_PARAMETRO,
	 NOM_TPO_PARAMETRO,
	 DSC_TPO_PARAMETRO,
	 IND_USUARIO)
VALUES
	(DBSIAF.TIPO_PARAMETRO_INST_S.NEXTVAL,
	 'LINK_DESENV_VESTIB',
	 'Utilizado no VESTIB (qualquer instituicao)em casos que é solicitado exibição de arquivos on line',
	 'S');

COMMIT;

INSERT INTO DBSIAF.PARAMETRO_INST
	(COD_TPO_PARAMETRO,
	 COD_INSTITUICAO,
	 VAL_PARAMETRO)
VALUES
	((SELECT MAX(COD_TPO_PARAMETRO)
	   FROM DBSIAF.TIPO_PARAMETRO_INST),
	 1,
	 'http://desenv.animaeducacao.com.br');
COMMIT;
