DECLARE

	CURSOR C_TITULO IS
	
		SELECT MIT.COD_MAPEAMENTO,
			   MIT.COD_TITULO_RECEBER,
			   MIS.CODCONC,
			   MIS.CODINSC
		  FROM DBSIAF.MAPEAMENTO_TITULO_LOG MIT,
			   DBSIAF.MAPEAMENTO_INSCRICAO  MIS,
			   DBVESTIB.CONCURSO            CON
		 WHERE CON.CODCONC = MIS.CODCONC
			   AND MIT.COD_MAPEAMENTO = MIS.COD_MAPEAMENTO
			   AND MIT.IDT_OPERACAO_LOG = 'I'
			   AND CON.ANOCONC = 2014
			   AND NOT EXISTS (SELECT 1
				  FROM DBSIAF.MAPEAMENTO_TITULO MTI
				 WHERE MTI.COD_MAPEAMENTO = MIT.COD_MAPEAMENTO
					   AND MTI.COD_TITULO_RECEBER = MIT.COD_TITULO_RECEBER)
			   AND NOT EXISTS (SELECT 1
				  FROM DBSIAF.HIST_MAPEAMENTO_TITULO HIT
				 WHERE HIT.CODCONC = MIS.CODCONC
					   AND HIT.CODINSC = MIS.CODINSC
					   AND HIT.COD_TITULO_RECEBER = MIT.COD_TITULO_RECEBER
					   AND HIT.COD_MAPEAMENTO = MIT.COD_MAPEAMENTO);
BEGIN
	FOR R_TIT IN C_TITULO LOOP
		INSERT INTO DBSIAF.HIST_MAPEAMENTO_TITULO
			(COD_HIST_MAPEAMENTO_TITULO,
			 COD_MAPEAMENTO,
			 COD_TITULO_RECEBER,
			 CODCONC,
			 CODINSC)
		VALUES
			(DBSIAF.HIST_MAPEAMENTO_TITULO_S.NEXTVAL,
			 R_TIT.COD_MAPEAMENTO,
			 R_TIT.COD_TITULO_RECEBER,
			 R_TIT.CODCONC,
			 R_TIT.CODINSC);
             commit;
	END LOOP;
END;
