DECLARE
	NOTA DBVESTIB.NOTA_PROVA.CODNOTAPROVA%TYPE;

	CURSOR C_CANDIDATO IS
		SELECT *
		  FROM DBVESTIB.CANDIDATO CAN
		 WHERE CAN.CODCONC = 2222
			   AND NOT EXISTS (SELECT *
				  FROM DBVESTIB.NOTA_PROVA N
				 WHERE N.CODCONC = CAN.CODCONC
					   AND CAN.CODCAN = N.CODCAN);

BEGIN


	
	FOR R_CANDIDATO IN C_CANDIDATO LOOP
      
    SELECT DBVESTIB.NOTA_PROVA_S.NEXTVAL
	  INTO NOTA
	  FROM DUAL;

		INSERT INTO DBVESTIB.NOTA_PROVA
			(CODNOTAPROVA,
			 CODCONC,
			 CODCAN,
			 COD_ETAPA,
			 NROOPC,
			 CODPRO,
			 NOTAPARCIAL,
			 NOTAFINAL)
		VALUES
			(NOTA,
			 R_CANDIDATO.CODCONC,
			 R_CANDIDATO.CODCAN,
			 1,
			 1,
			 14,
			 1,
			 NULL);
	
	END LOOP;

END;
