INSERT INTO DBVESTIB.NOTA_PROVA
    (CODNOTAPROVA,
     CODCONC,
     CODCAN,
     NROOPC,
     COD_ETAPA,
     CODPRO,
     NOTAPARCIAL,
     NOTAFINAL)
     
    
    SELECT DBVESTIB.NOTA_PROVA_S.NEXTVAL,
     NPR.CODCONC,
     NPR.CODCAN,
     NPR.NROOPC,
     2,
     CODPRO,
     NOTAPARCIAL,
     NOTAFINAL
      FROM DBVESTIB.CLASSIFICACAO_CANDIDATO CLA
     INNER JOIN DBVESTIB.NOTA_PROVA NPR
        ON (NPR.CODCONC = CLA.CODCONC AND NPR.CODCAN = CLA.CODCAN AND NPR.COD_ETAPA = 1)
     WHERE CLA.CODCONC = '2559'
           AND CLA.COD_STA_CLASSIFICACAO = 13;
