UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2010-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2644    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2012-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2645    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2646    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2003    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2003     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2647    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2648    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2011-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2649    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2002     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2650    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2651    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2652    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2653    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2654    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2003    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2003     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2655    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1991    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1991     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2656    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2003    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2003     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2657    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 10-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2658    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2008-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2659    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1998    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 1998     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2660    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2661    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2662    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 11-2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2663    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1982    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1982     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2664    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2665    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1998    , SEMCONC =     1    , NOMCONC = '    Transferência - 09-1998     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2666    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1998    , SEMCONC =     1    , NOMCONC = '    Transferência - 10-1998     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2667    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1999    , SEMCONC =     1    , NOMCONC = '    Vestibular - 1999     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2668    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1992    , SEMCONC =     1    , NOMCONC = '    Vestibular - 1992     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2669    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Transferência - 02-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2670    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2671    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2672    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Transferência - 05-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2673    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Transferência - 02-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2674    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2013-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2675    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2676    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2677    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2678    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2015-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2679    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2680    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2681    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2682    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2683    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2684    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2006-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2685    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2011-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2686    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2687    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2015-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2688    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1997    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-1997     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2689    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1998    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-1998     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2690    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 11-2008-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2691    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1983    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1983     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2692    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Transferência - 02-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2693    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2003    , SEMCONC =     1    , NOMCONC = '    Transferência - 2003     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2694    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2695    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1979    , SEMCONC =     1    , NOMCONC = '    Transferência - 1979     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2696    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1979    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1979     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2697    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1999    , SEMCONC =     1    , NOMCONC = '    Transferência - 1999     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2698    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2002     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2699    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1998    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-1998     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2700    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 11-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2701    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1992    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-1992     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2702    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2703    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2704    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2705    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1991    , SEMCONC =     1    , NOMCONC = '    Vestibular - 1991     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2706    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1989    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-1989     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2707    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Transferência - 06-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2708    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2709    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2710    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2010-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2711    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1984    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1984     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2712    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2713    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2714    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2715    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2716    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2014-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2717    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2718    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2008-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2719    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2720    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1997    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1997     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2721    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2008-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2722    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2723    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1987    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1987     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2724    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2725    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2726    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2727    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2728    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2729    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1975    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-1975     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2730    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2731    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2003    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-2003     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2732    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2733    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1999    , SEMCONC =     1    , NOMCONC = '    Transferência - 10-1999     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2734    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1995    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-1995     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2735    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1997    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-1997     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2736    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 06-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2737    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1989    , SEMCONC =     1    , NOMCONC = '    Vestibular - 1989     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2738    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2015     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2739    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Vestibular - 09-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2740    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2741    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2742    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2743    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2744    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2013-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2745    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2746    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2010-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2747    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2012-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2748    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2749    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1990    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1990     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2750    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2009-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2751    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2007-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2752    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2753    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2009-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2754    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Transferência - 10-2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2755    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1986    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1986     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2756    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1989    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1989     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2757    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2758    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1968    , SEMCONC =     1    , NOMCONC = '    Transferência - 1968     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2759    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2760    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 10-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2761    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2006-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2762    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Transferência - 2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2763    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Transferência - 10-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2764    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2001    , SEMCONC =     1    , NOMCONC = '    Transferência - 2001     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2765    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2766    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2014-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2767    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2011-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2768    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2769    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2010-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2770    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2771    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2772    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2012-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2773    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2774    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2775    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2776    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1993    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1993     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2777    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2009-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2778    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2014-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2779    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2780    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1996    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1996     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2781    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1988    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1988     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2782    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2009-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2783    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2784    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2785    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2007-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2786    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2787    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2015     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2788    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Transferência - 2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2789    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2790    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2011-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2791    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2792    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2005-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2793    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 06-2002     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2794    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2001    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2001     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2795    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Transferência - 2001     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2796    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1998    , SEMCONC =     1    , NOMCONC = '    Transferência - 06-1998     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2797    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1998    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-1998     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2798    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1990    , SEMCONC =     1    , NOMCONC = '    Vestibular - 1990     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2799    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1993    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-1993     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2800    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2801    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 05-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2802    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2803    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2804    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2013-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2805    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2012-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2806    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2807    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2013-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2808    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Vestibular - 09-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2809    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2810    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2001    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2001     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2811    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1999    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 1999     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2812    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1985    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1985     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2813    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2013-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2814    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2815    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2010-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2816    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1995    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1995     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2817    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1992    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1992     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2818    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 11-2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2819    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2009     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2820    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2007-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2821    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2008     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2822    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2823    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2824    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2007-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2825    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2002     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2826    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1981    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1981     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2827    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 11-2007-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2828    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2003    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2003     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2829    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2830    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2005-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2831    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-2002     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2832    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1991    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-1991     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2833    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Transferência - 02-2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2834    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2835    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1986    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-1986     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2836    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2837    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Transferência - 10-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2838    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Transferência - 03-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2839    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2840    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Vestibular - 09-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2841    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Vestibular - 09-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2842    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2012-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2843    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2014-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2844    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2845    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2015-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2846    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2847    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2848    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1980    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1980     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2849    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1971    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-1971     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2850    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1977    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1977     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2851    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2009    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2009-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2852    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2853    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2854    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2855    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2007-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2856    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2008-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2857    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2858    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Vestibular - 2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2859    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2006     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2860    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2006    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2006-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2861    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2004    , SEMCONC =     1    , NOMCONC = '    Transferência - 10-2004     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2862    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    #NOME?     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2863    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Transferência - 11-2002     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2864    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2865    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2001    , SEMCONC =     1    , NOMCONC = '    Transferência - 10-2001     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2866    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1983    , SEMCONC =     1    , NOMCONC = '    Transferência - 08-1983     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2867    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1993    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-1993     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2868    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1993    , SEMCONC =     1    , NOMCONC = '    Vestibular - 1993     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2869    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1984    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-1984     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2870    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1992    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-1992     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2871    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1990    , SEMCONC =     1    , NOMCONC = '    Transferência - 08-1990     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2872    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2873    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1992    , SEMCONC =     1    , NOMCONC = '    Transferência - 1992     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2874    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Transferência - 2014     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2875    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2010    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2010     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2876    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2015     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2877    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 02-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2878    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2011     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2879    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2880    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2881    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2011    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2011-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2882    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2012    , SEMCONC =     1    , NOMCONC = '    Transferência - 08-2012     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2883    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2884    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Vestibular - 10-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2885    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2001    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2001     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2886    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1994    , SEMCONC =     1    , NOMCONC = '    Vestibular - 01-1994     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2887    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1999    , SEMCONC =     1    , NOMCONC = '    Vestibular - 11-1999     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2888    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2005    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-2005     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2889    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2008    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 01-2008-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2890    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2007    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 11-2007     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2891    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1973    , SEMCONC =     1    , NOMCONC = '    Vestibular - 12-1973     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2892    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2002    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-2002     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2893    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2001    , SEMCONC =     1    , NOMCONC = '    Transferência - 12-2001     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2894    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2000    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-2000     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2895    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1999    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-1999     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2896    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1987    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-1987     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2897    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1994    , SEMCONC =     1    , NOMCONC = '    Transferência - 01-1994     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2898    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2014    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 12-2014-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2899    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 2015     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2900    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    1990    , SEMCONC =     1    , NOMCONC = '    Transferência - 07-1990     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2901    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2015    , SEMCONC =     1    , NOMCONC = '    Processo Seletivo - 03-2015-ENEM     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2902    ;
UPDATE DBVESTIB.CONCURSO    SET ANOCONC =    2013    , SEMCONC =     1    , NOMCONC = '    Transferência - 2013     ', COD_TPO_CONCURSO =    1    WHERE CODCONC =     2903    ;
commit;
