DECLARE
	CURSOR C_NOTA IS
	
		SELECT CAN.CODCONC,
			   CAN.CODCAN,
			   CAN.NOMCAN,
			   NPR.CODPRO,
			   (SELECT P.NOMPRO
				  FROM DBVESTIB.PROVA P
				 WHERE P.CODPRO = NPR.CODPRO) "prova",
			   NPR.COD_ETAPA,
			   NPR.NROOPC,
			   NPR.NOTAPARCIAL,
			   NPR.NOTAFINAL,
			   CAST((NPR.NOTAFINAL / 2) AS NUMBER(5,
						   2)) CORRETA
		
		  FROM DBVESTIB.NOTA_PROVA NPR,
			   DBVESTIB.CANDIDATO  CAN
		 WHERE NPR.CODCONC = '1940'
			   AND NPR.CODPRO = '03'
			   AND NPR.COD_ETAPA = 1
			  --    and npr.nroopc =  '2'
			   AND NPR.NOTAFINAL <> 0
			   AND NPR.NOTAFINAL / 2 = NPR.NOTAPARCIAL
			   AND CAN.CODCONC = NPR.CODCONC
			   AND CAN.CODCAN = NPR.CODCAN
--			   AND CAN.CODCAN = '128912'
		 ORDER BY CAN.NOMCAN,
				  NPR.NROOPC;
BEGIN
	FOR R_NOTA IN C_NOTA LOOP
		UPDATE DBVESTIB.NOTA_PROVA N
		   SET N.NOTAFINAL = R_NOTA.CORRETA
		 WHERE N.CODCONC = R_NOTA.CODCONC
			   AND N.CODCAN = R_NOTA.CODCAN
			   AND N.COD_ETAPA = R_NOTA.COD_ETAPA
			   AND N.CODPRO = R_NOTA.CODPRO
			   AND N.NROOPC = R_NOTA.NROOPC;
	END LOOP;
END;
