
DECLARE

	CURSOR C_CANDIDATO IS
		SELECT RCC.CODCAN,
			   RCC.CODCAM,
			   RCC.CODTUR,
			   RCC.CODCUR,
			   RCC.CODCONC,
			   RCC.NROOPC
		  FROM DBVESTIB.CANDIDATO CAN
		 INNER JOIN DBVESTIB.RCANDCURTUROPC RCC
			ON (CAN.CODCONC = RCC.CODCONC AND CAN.CODCAN = RCC.CODCAN)
		 INNER JOIN DBVESTIB.CAMPUS CAM
			ON (CAM.CODCAM = RCC.CODCAM)
		 INNER JOIN DBVESTIB.TURNO TUR
			ON (TUR.CODTUR = RCC.CODTUR)
		 WHERE CAN.CODCONC = &P_CODCONC_ORIGEM
			   AND RCC.CODCUR = &P_CODCUR_ORIGEM
               AND RCC.CODCAM = &P_CODCAM_ORIGEM
			   AND RCC.CODTUR = &P_CODTUR_ORIGEM;

	CURSOR C_INSCRICAO IS
		SELECT OPC.CODINSC CODCAN,
			   OPC.CODCAM,
			   OPC.CODTUR,
			   OPC.CODCUR,
			   OPC.CODCONC,
			   OPC.NROOPC
		  FROM DBVESTIB.INSCRICAO INS
		 INNER JOIN DBVESTIB.OPCAOCANDIDATO OPC
			ON (INS.CODCONC = OPC.CODCONC AND INS.CODINSC = OPC.CODINSC)
		 INNER JOIN DBVESTIB.CAMPUS CAM
			ON (CAM.CODCAM = OPC.CODCAM)
		 INNER JOIN DBVESTIB.TURNO TUR
			ON (TUR.CODTUR = OPC.CODTUR)
		 WHERE INS.CODCONC = &P_CODCONC_ORIGEM
			   AND OPC.CODCUR = &P_CODCUR_ORIGEM
			   AND OPC.CODTUR = &P_CODTUR_ORIGEM
			   AND OPC.CODCAM = &P_CODCAM_ORIGEM
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.CANDIDATO C
				 WHERE C.CODCONC = INS.CODCONC
					   AND C.CODCAN = INS.CODINSC);
	NVALIDA_O NUMBER;
	NVALIDA_D NUMBER;
BEGIN
	-- verifica o curso origem
	SELECT COUNT(1)
	  INTO NVALIDA_O
	  FROM DBVESTIB.RCURTUR CCC
	 WHERE CCC.CODCONC = &P_CODCONC_ORIGEM
		   AND CCC.CODCUR = &P_CODCUR_ORIGEM
		   AND CCC.CODCAM = &P_CODCAM_ORIGEM
		   AND CCC.CODTUR = &P_CODTUR_ORIGEM
		   AND CCC.INDINSCRICAO = 'N'
		   AND CCC.INDCANCELADO = 'S';

	IF NVALIDA_O > 0 THEN
		UPDATE DBVESTIB.RCURTUR RRR
		   SET RRR.INDINSCRICAO = 'S',
			   RRR.INDCANCELADO = 'N'
		 WHERE RRR.CODCONC = &P_CODCONC_ORIGEM
			   AND RRR.CODCUR = &P_CODCUR_ORIGEM
			   AND RRR.CODCAM = &P_CODCAM_ORIGEM
			   AND RRR.CODTUR = &P_CODTUR_ORIGEM;
	END IF;

	SELECT COUNT(1)
	  INTO NVALIDA_D
	  FROM DBVESTIB.RCURTUR CCC
	 WHERE CCC.CODCONC = &P_CODCONC_ORIGEM
		   AND CCC.CODCUR = &P_CODCUR_ORIGEM
		   AND CCC.CODCAM = &U_CODCAM_DESTINO
		   AND CCC.CODTUR = &U_CODTUR_DESTINO
		   AND CCC.INDINSCRICAO = 'N';

	IF NVALIDA_D > 0 THEN
		UPDATE DBVESTIB.RCURTUR RRR
		   SET RRR.INDINSCRICAO = 'S',
			   RRR.INDCANCELADO = 'N'
		 WHERE RRR.CODCONC = &P_CODCONC_ORIGEM
			   AND RRR.CODCUR = &P_CODCUR_ORIGEM
			   AND RRR.CODCAM = &U_CODCAM_DESTINO
			   AND RRR.CODTUR = &U_CODTUR_DESTINO;
	END IF;

	FOR R_CANDIDATO IN C_CANDIDATO LOOP
    
		UPDATE DBVESTIB.RCANDCURTUROPC RCC
		   SET CODCUR = R_CANDIDATO.CODCUR,
			   CODCAM =  &U_CODCAM_DESTINO,
			   CODTUR =  &U_CODTUR_DESTINO
		 WHERE RCC.CODCONC = R_CANDIDATO.CODCONC
			   AND RCC.CODCAN = R_CANDIDATO.CODCAN
			   AND RCC.NROOPC = R_CANDIDATO.NROOPC;
	
	END LOOP;

	FOR R_INSCRICAO IN C_INSCRICAO LOOP
		UPDATE DBVESTIB.OPCAOCANDIDATO OPC
		   SET CODCUR = R_INSCRICAO.CODCUR,
			   CODCAM = &U_CODCAM_DESTINO,
			   CODTUR = &U_CODTUR_DESTINO
		 WHERE OPC.CODCONC = R_INSCRICAO.CODCONC
			   AND OPC.CODINSC = R_INSCRICAO.CODCAN
			   AND OPC.NROOPC = R_INSCRICAO.NROOPC;
	END LOOP;

	IF NVALIDA_O > 0 THEN
		UPDATE DBVESTIB.RCURTUR RRR
		   SET RRR.INDINSCRICAO = 'N',
			   RRR.INDCANCELADO = 'S'
		 WHERE RRR.CODCONC = &P_CODCONC_ORIGEM
			   AND RRR.CODCUR = &P_CODCUR_ORIGEM
			   AND RRR.CODCAM =&P_CODCAM_ORIGEM
			   AND RRR.CODTUR = &P_CODTUR_ORIGEM;
	END IF;

	COMMIT;         

END;

/*

SELECT RCC.CODCAN,
               RCC.CODCAM,
               RCC.CODTUR,
               RCC.CODCUR,
               RCC.CODCONC
          FROM DBVESTIB.CANDIDATO CAN
         INNER JOIN DBVESTIB.RCANDCURTUROPC RCC
            ON (CAN.CODCONC = RCC.CODCONC AND CAN.CODCAN = RCC.CODCAN)
         INNER JOIN DBVESTIB.CAMPUS CAM
            ON (CAM.CODCAM = RCC.CODCAM)
         INNER JOIN DBVESTIB.TURNO TUR
            ON (TUR.CODTUR = RCC.CODTUR)
         WHERE CAN.CODCONC = &P_CODCONC
               AND RCC.CODCUR = &P_CODCUR         
               AND RCC.CODCAM = &P_CODCAM
               AND RCC.CODTUR = &P_CODTUR
union
        SELECT OPC.CODINSC CODCAN,
               OPC.CODCAM,
               OPC.CODTUR,
               OPC.CODCUR,
               OPC.CODCONC
          FROM DBVESTIB.INSCRICAO INS
         INNER JOIN DBVESTIB.OPCAOCANDIDATO OPC
            ON (INS.CODCONC = OPC.CODCONC AND INS.CODINSC = OPC.CODINSC)
         INNER JOIN DBVESTIB.CAMPUS CAM
            ON (CAM.CODCAM = OPC.CODCAM)
         INNER JOIN DBVESTIB.TURNO TUR
            ON (TUR.CODTUR = OPC.CODTUR)
         WHERE INS.CODCONC = &P_CODCONC
               AND OPC.CODCUR = &P_CODCUR
               AND OPC.CODTUR = &P_CODTUR
               AND OPC.CODCAM = &P_CODCAM
               and not exists (select 1 from dbvestib.candidato c
               where c.codconc = ins.codconc
               and c.codcan = ins.codinsc)*/
