DECLARE
	CURSOR C_PROVA IS
		SELECT *
		  FROM DBVESTIB.PROVASCADERNO PRO
		 WHERE PRO.CODCONC = '1629'
			   AND PRO.CODPRO = 99;
BEGIN
	FOR R_PROVA IN C_PROVA LOOP
		UPDATE DBVESTIB.PROVASCADERNO P
		   SET P.CODPRO = 16
		 WHERE P.CODCONC = R_PROVA.CODCONC
			   AND P.CODCAD = R_PROVA.CODCAD
			   AND P.CODPRO = 99;
	END LOOP;        
END;


