DECLARE
	NVALIDA NUMBER;
	CURSOR C_CAN IS
		SELECT o.codconc, o.codcan, o.codcur, o.codtur, o.codcam, o.nroopc, otc.cod_grd_horario
		  FROM DBVESTIB.RCANDCURTUROPC        O,
			   DBVESTIB.OPCAO_TURMA_CANDIDATO OTC
		 WHERE O.CODCONC = '3037'
			   AND O.CODCUR = '89'
			   AND CODCAM = '38'
			   AND CODTUR = '77'
			   AND OTC.CODCONC = O.CODCONC
			   AND OTC.CODINSC = O.CODCAN;

BEGIN
	FOR R_CAN IN C_CAN LOOP
	
		SELECT COUNT(1)
		  INTO NVALIDA
		  FROM DBVESTIB.CLASSIFICACAO_CANDIDATO C
		 WHERE CODCONC = R_CAN.CODCONC
			   AND CODCAN = R_CAN.CODCAN;
	
		IF NVALIDA = 1 THEN
		
			DELETE FROM DBVESTIB.CLASSIFICACAO_CANDIDATO
			 WHERE CODCONC = R_CAN.CODCONC
				   AND CODCAN = R_CAN.CODCAN;
		END IF;
	
		SELECT COUNT(1)
		  INTO NVALIDA
		  FROM DBVESTIB.REGISTRO_DEFERIMENTO D
		 WHERE CODCONC = R_CAN.CODCONC
			   AND CODINSC = R_CAN.CODCAN;
	
		IF NVALIDA = 1 THEN
			DELETE FROM DBVESTIB.REGISTRO_DEFERIMENTO
			 WHERE CODCONC = R_CAN.CODCONC
				   AND CODINSC = R_CAN.CODCAN;
		END IF;
        
		UPDATE DBVESTIB.RCANDCURTUROPC RCC
			   SET CODCUR = R_CAN.CODCUR,
				   CODCAM = '19',
				   CODTUR = '01'
			 WHERE RCC.CODCONC = '3037'
				   AND RCC.CODCAN = R_CAN.CODCAN
				   AND RCC.NROOPC = R_CAN.NROOPC
				   AND RCC.CODCUR = R_CAN.CODCUR
				   AND RCC.CODCAM = R_CAN.CODCAM;
                   
		IF R_CAN.COD_GRD_HORARIO = 474098 THEN
		
			UPDATE DBVESTIB.OPCAO_TURMA_CANDIDATO OTC
			   SET OTC.COD_GRD_HORARIO = 479726
			 WHERE OTC.CODCONC = R_CAN.CODCONC
				   AND OTC.CODINSC = R_CAN.CODCAN
				   AND OTC.COD_GRD_HORARIO = 474098; -- portugues;
		
		ELSE
			IF R_CAN.COD_GRD_HORARIO = 474099 THEN
				UPDATE DBVESTIB.OPCAO_TURMA_CANDIDATO OTC
				   SET OTC.COD_GRD_HORARIO = 479727
				 WHERE OTC.CODCONC = R_CAN.CODCONC
					   AND OTC.CODINSC = R_CAN.CODCAN
					   AND OTC.COD_GRD_HORARIO = 474099; -- matematica;
			END IF;            		
		
		END IF;
	
         
  END LOOP;
END;
