GRANT SELECT, INSERT, UPDATE, DELETE ON DBVESTIB.ACERTOS_ERROS_QUESTAO TO user_dbvestib;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBVESTIB.ACERTOS_ERROS_QUESTAO TO USER_dbvestib;
GRANT EXECUTE ON DBVESTIB.ACERTOS_ERROS_QUESTAO TO USER_SIAF;

/*with grant option: para usar quando em consultas o Vestib tiver tabela Siaf
