DECLARE

	CURSOR C_DESTRANCA IS
	--destrancamento
		SELECT CAN.NOMCAN,
			   CAN.CODCONC,
			   CAN.CODCAN,
			   CAN.MATRICULA,
			   CAN.CPFCAN,
			   (SELECT COD_ALUNO
				  FROM DBSIAF.ALUNO ALU
				 WHERE TRIM(ALU.NUM_MATRICULA) = TRIM(CAN.MATRICULA)
					   AND ALU.COD_INSTITUICAO = 8) COD_ALUNO,
			   (SELECT RC.COD_GRD_CURRICULAR_SIAF
				  FROM DBVESTIB.RCANDCURTUROPC RCA,
					   DBVESTIB.RCURTUR        RC,
					   DBVESTIB.CAMPUS         CAM
				 WHERE RCA.CODCONC = CAN.CODCONC
					   AND RCA.CODCAN = CAN.CODCAN
					   AND RC.CODCONC = RCA.CODCONC
					   AND RC.CODCUR = RCA.CODCUR
					   AND RC.CODTUR = RCA.CODTUR
					   AND CAM.CODCAM = RCA.CODCAM
					   AND RCA.NROOPC = '1'
					   AND RC.CODCAM = RCA.CODCAM) GRADE_DESTINO,
			   (SELECT GRD.COD_PERIODICIDADE
				  FROM DBSIAF.ALUNO            ALU,
					   DBSIAF.GRADE_CURRICULAR GRD
				 WHERE TRIM(ALU.NUM_MATRICULA) = TRIM(CAN.MATRICULA)
					   AND ALU.COD_INSTITUICAO = 8
					   AND GRD.COD_GRD_CURRICULAR = ALU.COD_GRD_CURRICULAR) PERIODICIDADE
		  FROM DBVESTIB.CANDIDATO            CAN,
			   DBVESTIB.REGISTRO_DEFERIMENTO REG,
			   DBSIAF.TIPO_ENTRADA           TPE,
			   DBVESTIB.PARAMETROS_CONCURSO  PAR
		 WHERE CAN.CODCONC = '2910'
			   AND REG.CODINSC = CAN.CODCAN
			   AND REG.CODCONC = CAN.CODCONC
			   AND PAR.CODCONC = CAN.CODCONC
			   AND REG.INDDEFERIDO = 'S'
			   AND NOT EXISTS (SELECT 1
				  FROM DBSIAF.ALUNO ALU
				 WHERE ALU.CODCONC = CAN.CODCONC
					   AND ALU.CODCAN = CAN.CODCAN)
			   AND (CAN.MATRICULA IS NOT NULL AND CAN.COD_INSTITUICAO_PSVS IS NOT NULL)
			   AND TPE.COD_TPO_ENTRADA = CAN.FORMA_INGRESSO
			   AND TPE.IND_DESTRANCAMENTO = 'S'
			   AND TPE.IND_NOVO_ALUNO = 'N'
			   AND TPE.IND_REMANEJAMENTO = 'N'
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.AUSENTEDESIS AUS
				 WHERE AUS.CODCONC = CAN.CODCONC
					   AND AUS.CODCAN = CAN.CODCAN);
	/* AND CAN.CODCAN NOT IN ('651661',
    '622317',
    '628811',
    '623941',
    '624121',
    '652446',
    '624542')*/

	CURSOR C_REM IS
		SELECT CAN.CODCONC,nomcan,
			   CAN.CODCAN,
			   CAN.MATRICULA,
			   (SELECT COD_ALUNO
				  FROM DBSIAF.ALUNO ALU
				 WHERE TRIM(ALU.NUM_MATRICULA) = TRIM(CAN.MATRICULA)
					   AND ALU.COD_INSTITUICAO = 8) COD_ALUNO,
			   (SELECT RC.COD_GRD_CURRICULAR_SIAF
				  FROM DBVESTIB.RCANDCURTUROPC RCA,
					   DBVESTIB.RCURTUR        RC,
					   DBVESTIB.CAMPUS         CAM
				 WHERE RCA.CODCONC = CAN.CODCONC
					   AND RCA.CODCAN = CAN.CODCAN
					   AND RC.CODCONC = RCA.CODCONC
					   AND RC.CODCUR = RCA.CODCUR
					   AND RC.CODTUR = RCA.CODTUR
					   AND CAM.CODCAM = RCA.CODCAM
					   AND RCA.NROOPC = '1'
					   AND RC.CODCAM = RCA.CODCAM) GRADE_DESTINO,
			   (SELECT GRD.COD_PERIODICIDADE
				  FROM DBSIAF.ALUNO            ALU,
					   DBSIAF.GRADE_CURRICULAR GRD
				 WHERE TRIM(ALU.NUM_MATRICULA) = TRIM(CAN.MATRICULA)
					   AND ALU.COD_INSTITUICAO = 8
					   AND GRD.COD_GRD_CURRICULAR = ALU.COD_GRD_CURRICULAR) PERIODICIDADE
		  FROM DBVESTIB.CANDIDATO            CAN,
			   DBVESTIB.REGISTRO_DEFERIMENTO REG,
			   DBSIAF.TIPO_ENTRADA           TPE,
			   DBVESTIB.PARAMETROS_CONCURSO  PAR
		 WHERE CAN.CODCONC = '2910'
			   AND REG.CODINSC = CAN.CODCAN
			   AND REG.CODCONC = CAN.CODCONC
			   AND PAR.CODCONC = CAN.CODCONC
			   AND REG.INDDEFERIDO = 'S'
			   AND NOT EXISTS (SELECT 1
				  FROM DBSIAF.ALUNO ALU
				 WHERE ALU.CODCONC = CAN.CODCONC
					   AND ALU.CODCAN = CAN.CODCAN)
			   AND (CAN.MATRICULA IS NOT NULL AND CAN.COD_INSTITUICAO_PSVS IS NOT NULL)
			   AND TPE.COD_TPO_ENTRADA = CAN.FORMA_INGRESSO
			   AND TPE.IND_DESTRANCAMENTO = 'N'
			   AND TPE.IND_NOVO_ALUNO = 'N'
			   AND TPE.IND_REMANEJAMENTO = 'S'
			   AND NOT EXISTS (SELECT 1
				  FROM DBVESTIB.AUSENTEDESIS AUS
				 WHERE AUS.CODCONC = CAN.CODCONC
					   AND AUS.CODCAN = CAN.CODCAN);
	/*AND CAN.CODCAN IN ('624898',
    '657415',
    '645139');*/

	MSG     VARCHAR2(500);
	NVALIDA NUMBER;

BEGIN
  	DELETE FROM DBVESTIB.LOG_ERROS_IMPORTACAO
			 WHERE CODCONC = '2910';
			COMMIT;
	FOR R_DESTRANCA IN C_DESTRANCA LOOP
		BEGIN
		
			DELETE FROM DBVESTIB.LOG_ERROS_IMPORTACAO
			 WHERE CODCONC = R_DESTRANCA.CODCONC
				   AND CODCAN = R_DESTRANCA.CODCAN;
			COMMIT;
		
			-- Se for destrancar um aluno de anual para semestral
			IF R_DESTRANCA.PERIODICIDADE = 2 THEN
			
				SELECT COUNT(1)
				  INTO NVALIDA
				  FROM DBSIAF.GRADE_CURRICULAR GRD
				 WHERE GRD.COD_GRD_CURRICULAR = R_DESTRANCA.GRADE_DESTINO
					   AND GRD.COD_PERIODICIDADE = 1; -- semestral
			
				IF NVALIDA > 0 THEN
					-- troca o aluno para uma grade intermediária semetral
					UPDATE DBSIAF.ALUNO A
					   SET A.COD_GRD_CURRICULAR = 15244
					 WHERE A.COD_ALUNO = R_DESTRANCA.COD_ALUNO;
				
					DBSIAF.PC_REMANEJAMENTO.BVALIDAPERIODOLETIVO := FALSE;
				END IF;
			
				DBSIAF.PC_PROCESSAMENTO_DEFERIMENTO.SP_PROCESSA_CANDIDATO(R_DESTRANCA.CODCAN,
																		  R_DESTRANCA.CODCONC,
																		  MSG);
			
				IF MSG IS NOT NULL THEN
					INSERT INTO DBVESTIB.LOG_ERROS_IMPORTACAO
						(CODCONC,
						 CODCAN,
						 COD_ERRO,
						 DSC_ERRO)
					VALUES
						(R_DESTRANCA.CODCONC,
						 R_DESTRANCA.CODCAN,
						 1,
						 MSG);
					COMMIT;
				ELSE
				
					-- coloca o aluno na grade destino correta
					UPDATE DBSIAF.ALUNO A
					   SET A.COD_GRD_CURRICULAR = R_DESTRANCA.GRADE_DESTINO
					 WHERE A.COD_ALUNO = R_DESTRANCA.COD_ALUNO;
					COMMIT;
				END IF;
			ELSE
				DBSIAF.PC_PROCESSAMENTO_DEFERIMENTO.SP_PROCESSA_CANDIDATO(R_DESTRANCA.CODCAN,
																		  R_DESTRANCA.CODCONC,
																		  MSG);
				IF MSG IS NOT NULL THEN
					INSERT INTO DBVESTIB.LOG_ERROS_IMPORTACAO
						(CODCONC,
						 CODCAN,
						 COD_ERRO,
						 DSC_ERRO)
					VALUES
						(R_DESTRANCA.CODCONC,
						 R_DESTRANCA.CODCAN,
						 1,
						 MSG);
					COMMIT;
				END IF;
			END IF;
		
		EXCEPTION
			WHEN OTHERS THEN
				INSERT INTO DBVESTIB.LOG_ERROS_IMPORTACAO
					(CODCONC,
					 CODCAN,
					 COD_ERRO,
					 DSC_ERRO)
				VALUES
					(R_DESTRANCA.CODCONC,
					 R_DESTRANCA.CODCAN,
					 1,
					 MSG);
				COMMIT;
				RAISE_APPLICATION_ERROR(-20500,
										R_DESTRANCA.CODCAN || MSG);
		END;
	END LOOP;

	FOR R_REM IN C_REM LOOP
		BEGIN
		/*	DELETE FROM DBVESTIB.LOG_ERROS_IMPORTACAO
			 WHERE CODCONC = R_REM.CODCONC
				   AND CODCAN = R_REM.CODCAN;
			COMMIT;*/
			-- Se for destrancar um aluno de anual para semestral
			IF R_REM.PERIODICIDADE = 2 THEN
			
				SELECT COUNT(1)
				  INTO NVALIDA
				  FROM DBSIAF.GRADE_CURRICULAR GRD
				 WHERE GRD.COD_GRD_CURRICULAR = R_REM.GRADE_DESTINO
					   AND GRD.COD_PERIODICIDADE = 1; -- semestral
			
				IF NVALIDA > 0 THEN
					-- troca o aluno para uma grade intermediária semetral
					UPDATE DBSIAF.ALUNO A
					   SET A.COD_GRD_CURRICULAR = 15244
					 WHERE A.COD_ALUNO = R_REM.COD_ALUNO;
				
					DBSIAF.PC_REMANEJAMENTO.BVALIDAPERIODOLETIVO := FALSE;
				END IF;
			
				DBSIAF.PC_PROCESSAMENTO_DEFERIMENTO.SP_PROCESSA_CANDIDATO(R_REM.CODCAN,
																		  R_REM.CODCONC,
																		  MSG);
			
				IF MSG IS NOT NULL THEN
					INSERT INTO DBVESTIB.LOG_ERROS_IMPORTACAO
						(CODCONC,
						 CODCAN,
						 COD_ERRO,
						 DSC_ERRO)
					VALUES
						(R_REM.CODCONC,
						 R_REM.CODCAN,
						 1,
						 MSG);
					COMMIT;
				
				END IF;
			ELSE
				DBSIAF.PC_PROCESSAMENTO_DEFERIMENTO.SP_PROCESSA_CANDIDATO(R_REM.CODCAN,
																		  R_REM.CODCONC,
																		  MSG);
				IF MSG IS NOT NULL THEN
					INSERT INTO DBVESTIB.LOG_ERROS_IMPORTACAO
						(CODCONC,
						 CODCAN,
						 COD_ERRO,
						 DSC_ERRO)
					VALUES
						(R_REM.CODCONC,
						 R_REM.CODCAN,
						 1,
						 MSG);
					COMMIT;
				END IF;
			END IF;
		
		EXCEPTION
			WHEN OTHERS THEN
			
				INSERT INTO DBVESTIB.LOG_ERROS_IMPORTACAO
					(CODCONC,
					 CODCAN,
					 COD_ERRO,
					 DSC_ERRO)
				VALUES
					(R_REM.CODCONC,
					 R_REM.CODCAN,
					 1,
					 MSG);
				COMMIT;
		END;
	END LOOP;

END;
/*

select *
from dbvestib.log_erros_importacao i
where i.codconc = '2910'
and not exists (select 1 from dbsiaf.aluno a where a.codconc = i.codconc and a.codcan = i.codcan)*/
