SELECT DISTINCT
       AA.COD_DIARIO_CLASSE,
       PRO.NOM_PROFESSOR,
       AA.NUM_AULA,
       TO_CHAR(NVL(IDD.DAT_REALIZADA, IDD.DAT_PREVISTA), 'DD/MM/YYYY') DATA_AULA,
       ALU.NOM_ALUNO,
       U.NOM_USUARIO,
       NVL(AA.DAT_OPERACAO_LOG, AA.DAT_CADASTRAMENTO) DAT_CADASTRAMENTO,
       DECODE(AA.IDT_OPERACAO_LOG, 'I', 'Inseriu', 'D', 'Removeu', 'U', 'Alterou') as ALTERACAO
  FROM DBSIAF.AUSENCIA_ALUNO_LOG AA, 
       ITEM_DIARIO_DATA IDD, 
       DBADM.USUARIO U,
       DBSIAF.ALUNO ALU,
       DBSIAF.DIARIO_CLASSE DIA,
       DBSIAF.PERIODO_LETIVO PEL,
       DBSIAF.PROFESSOR PRO
 WHERE IDD.COD_ITEM_DIARIO_DATA = AA.COD_ITEM_DIARIO_DATA
   AND PEL.COD_INSTITUICAO = :P1_COD_INSTITUICAO
   AND PEL.COD_PERIODO_LETIVO = DIA.COD_PERIODO_LETIVO
   AND DIA.COD_PERIODO_LETIVO = :P2_COD_PERIODO_LETIVO
   AND U.COD_USUARIO = AA.COD_USUARIO_LOG
   AND NUM_AULA > 0
   AND ALU.COD_ALUNO = AA.COD_ALUNO
   AND :P3_COD_PROFESSOR = :P3_COD_PROFESSOR
   AND DIA.COD_PROFESSOR = PRO.COD_PROFESSOR
   AND AA.COD_DIARIO_CLASSE = DIA.COD_DIARIO_CLASSE
   AND DIA.COD_GRD_HORARIO = :P4_COD_GRD_HORARIO
 ORDER BY NUM_AULA, 4, 8 DESC
 
