SELECT
  CGR.COD_CNF_CONSULTA CODCNFCONSULTA,
  CGR.COD_CNF_RELATORIO CODCNFRELATORIO,
  CGR.DSC_CNF_RELATORIO DSCCNFRELATORIO,
  cgr.cod_cnf_consulta
  
FROM
  DBADM.CONFIG_RELATORIO CGR
WHERE
 DBADM.PC_CONSULTAS.F_VERIFICA_PERM_RELATORIO(CGR.COD_CNF_RELATORIO,13391,4952) = 'S'

ORDER BY
  CGR.DSC_CNF_RELATORIO
  
  SELECT * FROM  DBADM.CONFIG_REL_ITEM_MENU
INSERT INTO DBADM.CONFIG_REL_ITEM_MENU(COD_CNF_RELATORIO,COD_ITEM_MENU,COD_USUARIO_LOG,DAT_OPERACAO_LOG)
VALUES (821,4952,13391,SYSDATE)

        WHERE DBADM.CONFIG_REL_ITEM_MENU.COD_ITEM_MENU = NVL(4952,NU,DBADM.CONFIG_REL_ITEM_MENU.COD_ITEM_MENU)
              AND DBADM.CONFIG_REL_ITEM_MENU.COD_CNF_RELATORIO = CGR.COD_CNF_RELATORIO
