DECLARE

	CURSOR C_MIRA IS
		SELECT COD_TITULO_RECEBER  COD_INEP,
			   DSC_TPO_SOLICITACAO NOM_INSTIT_EXTERNA,
			   DSC_TPO_SOLICITACAO NOM_RDZ_INSTITUICAO,
			   COD_INSTITUICAO     COD_TPO_INSTITUICAO,
			   COD_LOG_INTEGRACAO  COD_STA_INSTIT_EXTERNA
		  FROM DBSIAF.TITULO_MIRA2 MMM
		 WHERE NOT EXISTS (SELECT 1
				  FROM DBSIAF.INSTITUICAO_EXTERNA IES
				 WHERE IES.COD_INEP = MMM.COD_TITULO_RECEBER
					   AND IES.IND_MEC = 'S');

	CURSOR C_IES INS
		SELECT *
		  FROM DBSIAF.INSTITUICAO_EXTERNA IES
		 WHERE IES.SGL_INSTIT_EXTERNA IS NOT NULL
			   AND (IES.IND_MEC <> 'S' OR IES.IND_MEC IS NULL)
			   AND EXISTS (SELECT 1
				  FROM DBSIAF.INSTITUICAO_EXTERNA III
				 WHERE III.IND_MEC = 'S'
					   AND III.SGL_INSTIT_EXTERNA IS NULL
					   AND (III.COD_INEP = IES.COD_INEP OR III.NOM_INSTIT_EXTERNA = IES.NOM_INSTIT_EXTERNA));

BEGIN
	FOR R_MIRA IN C_MIRA LOOP
		INSERT INTO DBSIAF.INSTITUICAO_EXTERNA
			(COD_INSTIT_EXTERNA,
			 COD_TPO_INSTITUICAO,
			 NOM_INSTIT_EXTERNA,
			 NOM_RDZ_INSTITUICAO,
			 COD_INEP,
			 COD_STA_INSTIT_EXTERNA,
			 IND_MEC)
		VALUES
			(DBSIAF.INSTITUICAO_EXTERNA_S.NEXTVAL,
			 R_MIRA.COD_TPO_INSTITUICAO,
			 R_MIRA.NOM_INSTIT_EXTERNA,
			 R_MIRA.NOM_RDZ_INSTITUICAO,
			 R_MIRA.COD_INEP,
			 R_MIRA.COD_STA_INSTIT_EXTERNA,
			 'S');
	
		COMMIT;
	END LOOP;

	FOR R_IES IN C_IES LOOP
		UPDATE DBSIAF.INSTITUICAO_EXTERNA IES IES.SGL_INSTIT_EXTERNA = R_IES.SGL_INSTIT_EXTERNA
		 WHERE IES.COD_INEP = R_IES.CODINEP
			   AND IES.IND_MEC = 'S';
	END LOOP;

	DELETE FROM DBSIAF.TITULO_MIRA2 MMM;
	COMMIT;
END;
