DECLARE

	CURSOR C_ESTADO_ERRADO IS
	
		SELECT ES.COD_ESTADO ERRADO,
			   EE.COD_ESTADO CERTO
		  FROM DBSIAF.ESTADO ES
		 INNER JOIN DBSIAF.ESTADO EE
			ON ES.COD_ESTADO <> EE.COD_ESTADO
			   AND TRIM(UPPER(ES.NOM_ESTADO)) = TRIM(UPPER(EE.NOM_ESTADO))
			   AND ES.COD_PAIS = EE.COD_PAIS
			   AND EE.COD_UF IS NOT NULL
		 WHERE ES.COD_PAIS = 1
		 ORDER BY EE.COD_ESTADO;

	CURSOR C_INSCRICAO(P_COD_ESTADO DBSIAF.ESTADO.COD_ESTADO%TYPE) IS
		SELECT INS.CODCONC,
			   INS.CODINSC
		  FROM DBVESTIB.INSCRICAO INS
		 WHERE INS.CODESTADO = P_COD_ESTADO;

	CURSOR C_CIDADE IS
	
		SELECT TAB.COD_CIDADE COD_CIDADE_MIN,
			   TAB.NOM_CIDADE NOM_CIDADE_MIN,
			   CID.COD_CIDADE,
			   CID.NOM_CIDADE
		  FROM (SELECT CID.COD_ESTADO,
					   COD_MUNICIPIO,
					   UPPER(TRIM(TRANSLATE(CID.NOM_CIDADE,
											'ֱֹֽ׃ÚֲÊ־װÛְָּׂÙִֻֿײÜֳױַׁביםףתגךמפûאטלעשהכןצüדץחסA@#$%¨&*()-_+=|\/?!{},.;:"<>[]''^~`´÷°×''',
											'AEIOUAEIOUAEIOUAEIOUAOCNaeiouaeiouaeiouaeuouaocnA'))) NOM_CIDADE,
					   MIN(COD_CIDADE) COD_CIDADE,
					   COUNT(1)
				  FROM DBSIAF.CIDADE CID
				 GROUP BY CID.COD_ESTADO,
						  COD_MUNICIPIO,
						  UPPER(TRIM(TRANSLATE(CID.NOM_CIDADE,
											   'ֱֹֽ׃ÚֲÊ־װÛְָּׂÙִֻֿײÜֳױַׁביםףתגךמפûאטלעשהכןצüדץחסA@#$%¨&*()-_+=|\/?!{},.;:"<>[]''^~`´÷°×''',
											   'AEIOUAEIOUAEIOUAEIOUAOCNaeiouaeiouaeiouaeuouaocnA')))
				HAVING COUNT(1) > 1) TAB
		  JOIN DBSIAF.CIDADE CID
			ON (CID.COD_ESTADO = TAB.COD_ESTADO AND (CID.COD_MUNICIPIO = TAB.COD_MUNICIPIO OR TAB.COD_MUNICIPIO IS NULL) AND UPPER(TRIM(TRANSLATE(CID.NOM_CIDADE,
																																				  'ֱֹֽ׃ÚֲÊ־װÛְָּׂÙִֻֿײÜֳױַׁביםףתגךמפûאטלעשהכןצüדץחסA@#$%¨&*()-_+=|\/?!{},.;:"<>[]''^~`´÷°×''',
																																				  'AEIOUAEIOUAEIOUAEIOUAOCNaeiouaeiouaeiouaeuouaocnA'))) = UPPER(TRIM(TRANSLATE(TAB.NOM_CIDADE,
																																																																																			  'ֱֹֽ׃ÚֲÊ־װÛְָּׂÙִֻֿײÜֳױַׁביםףתגךמפûאטלעשהכןצüדץחסA@#$%¨&*()-_+=|\/?!{},.;:"<>[]''^~`´÷°×''',
																																																																																			  'AEIOUAEIOUAEIOUAEIOUAOCNaeiouaeiouaeiouaeuouaocnA'))) AND CID.COD_CIDADE <> TAB.COD_CIDADE)
		 ORDER BY COD_CIDADE_MIN;

	NVALIDA     NUMBER;
	MIN_CIDADE  DBSIAF.CIDADE.COD_CIDADE%TYPE;
	CIDADE_TEMP DBSIAF.CIDADE.COD_CIDADE%TYPE;
BEGIN
	/*FOR R_EST IN C_ESTADO_ERRADO LOOP
        FOR R_INSC IN C_INSCRICAO(R_EST.ERRADO) LOOP
        
            UPDATE DBVESTIB.INSCRICAO INS
               SET INS.CODESTADO = R_EST.CERTO
             WHERE INS.CODCONC = R_INSC.CODCONC
                   AND INS.CODINSC = R_INSC.CODINSC;
            COMMIT;
        END LOOP;
    
        SELECT COUNT(1)
          INTO NVALIDA
          FROM DBSIAF.CIDADE CII
         WHERE CII.COD_ESTADO = R_EST.ERRADO
               AND NOT EXISTS (SELECT 1
                  FROM DBSIAF.CIDADE CDD
                 WHERE TRIM(UPPER(CDD.NOM_CIDADE)) = TRIM(UPPER(CII.NOM_CIDADE))
                       AND CDD.COD_ESTADO = R_EST.CERTO);
    
        IF (NVALIDA = 0) THEN
        
            UPDATE DBSIAF.CIDADE CID
               SET CID.COD_ESTADO = R_EST.CERTO,
                   CID.NOM_CIDADE = UPPER(CID.NOM_CIDADE)
             WHERE CID.COD_ESTADO = R_EST.ERRADO;
            COMMIT;
        
        ELSE
            DELETE DBSIAF.CIDADE CDE
             WHERE CDE.COD_ESTADO = R_EST.ERRADO;
        END IF;
    
        DELETE FROM DBSIAF.ESTADO EEE
         WHERE EEE.COD_ESTADO = R_EST.ERRADO;
        COMMIT;
    
    END LOOP;*/

	DBSIAF.PC_PESSOA.B_ATUALIZA_PESSOA := FALSE;

	FOR R_CID IN C_CIDADE LOOP
	
		SELECT COUNT(1)
		  INTO NVALIDA
		  FROM DBCEP.LOCALIDADE LOC
		 WHERE LOC.COD_CIDADE_SIAF = R_CID.COD_CIDADE;
	
		IF NVALIDA > 0 THEN
			CIDADE_TEMP          := R_CID.COD_CIDADE_MIN;
			R_CID.COD_CIDADE_MIN := R_CID.COD_CIDADE;
			R_CID.COD_CIDADE     := CIDADE_TEMP;
		END IF;
	
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.ENDERECO_PESSOA EPE
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.ENDERECO_PESSOA EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'ENDERECO_PESSOA' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
	
		-- FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBSIAF.PESSOA_FISICA EPE
			   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
			
				RAISE_APPLICATION_ERROR(-20500,
										'PESSOA_FISICA ' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		-- END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBSIAF.END_ALUNO EPE
			   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'END_ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--  END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBSIAF.PARAMETROS_CONTRATO_MOL EPE
			   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'PARAMETROS_CONTRATO_MOL' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		-- END LOOP;
	
		-- FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBSIAF.PARAMETROS_CONTRATO_MOL EPE
			   SET EPE.COD_CIDADE_ALUNO = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE_ALUNO = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'PARAMETROS_CONTRATO_MOL2' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBSIAF.END_INSTIT_EXTERNA EPE
			   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'END_INSTIT_EXTERNA' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBSIAF.INSCRICAO_EVENTO EPE
			   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'INSCRICAO_EVENTO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBINSCPOS.END_INSCRITO EPE
			   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'END_INSCRITO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBINSCPOS.INSCRITO EPE
			   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'INSCRITO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			UPDATE DBINSCPOS.INSCRITO EPE
			   SET EPE.COD_CIDADE_TE = R_CID.COD_CIDADE_MIN
			 WHERE EPE.COD_CIDADE_TE = R_CID.COD_CIDADE;
			COMMIT;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'INSCRITO2' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.END_RESPONSAVEL EPE
			 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.END_RESPONSAVEL EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'END_RESPONSAVEL' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		-- END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.ALUNO IAE
			 WHERE IAE.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.ALUNO EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;     
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBVESTIB.ENDERECO_ESCOLA_FIAT IAE
			 WHERE IAE.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBVESTIB.ENDERECO_ESCOLA_FIAT FIA
				   SET FIA.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE FIA.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'ENDEREַO FIAT' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBVESTIB.INSCRICAO INS
			 WHERE INS.CODCIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBVESTIB.INSCRICAO INS
				   SET INS.CODCIDADE = R_CID.COD_CIDADE_MIN
				 WHERE INS.CODCIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'INSCRICAO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBEAD.ALUNO ALC
			 WHERE ALC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBEAD.ALUNO ALC
				   SET ALC.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE ALC.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'ALUNO_EAD' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		-- FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.ALUNO IAE
			 WHERE IAE.COD_CIDADE_TE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.ALUNO EPE
				   SET EPE.COD_CIDADE_TE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE_TE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'ALUNO_ELEITOR' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		/* FOR R_CID IN C_CIDADE LOOP
            BEGIN
                SELECT COUNT(1)
                  INTO NVALIDA
                  FROM DBCEP.LOCALIDADE LOC
                 WHERE LOC.COD_CIDADE_SIAF = R_CID.COD_CIDADE;
            
                IF NVALIDA > 0 THEN
                    UPDATE DBCEP.LOCALIDADE EPE
                       SET EPE.COD_CIDADE_SIAF = R_CID.COD_CIDADE_MIN
                     WHERE EPE.COD_CIDADE_SIAF = R_CID.COD_CIDADE;
                    COMMIT;
                END IF;
            EXCEPTION
                WHEN OTHERS THEN
                    RAISE_APPLICATION_ERROR(-20500,
                                            'LOCALIDADE' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
            END;
        END LOOP;*/
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSGD.PARTICIPACAO_EVENTO LOC
			 WHERE LOC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSGD.PARTICIPACAO_EVENTO EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'PARTICIPACAO EVENTO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.END_FORNECEDOR LOC
			 WHERE LOC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.END_FORNECEDOR EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'FORNECEDOR' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		-- END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.DADOS_ALUNO LOC
			 WHERE LOC.COD_CIDADE_TE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.DADOS_ALUNO EPE
				   SET EPE.COD_CIDADE_TE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE_TE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'DADOS_ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.DADOS_ALUNO LOC
			 WHERE LOC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.DADOS_ALUNO EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'DADOS_ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		-- END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBVESTIB.FUNCIONARIO LOC
			 WHERE LOC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBVESTIB.FUNCIONARIO EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'DADOS_ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		-- END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.AGENCIA_BANCARIA LOC
			 WHERE LOC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.AGENCIA_BANCARIA EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'DADOS_ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.END_CAMPUS LOC
			 WHERE LOC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.END_CAMPUS EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'DADOS_ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.END_PROFESSOR LOC
			 WHERE LOC.COD_CIDADE = R_CID.COD_CIDADE;
		
			IF NVALIDA > 0 THEN
				UPDATE DBSIAF.END_PROFESSOR EPE
				   SET EPE.COD_CIDADE = R_CID.COD_CIDADE_MIN
				 WHERE EPE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			END IF;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'DADOS_ALUNO' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
		--END LOOP;
	
		--FOR R_CID IN C_CIDADE LOOP
		BEGIN
			SELECT COUNT(1)
			  INTO NVALIDA
			  FROM DBSIAF.CIDADE IAE
			 WHERE IAE.COD_CIDADE = R_CID.COD_CIDADE;
			/*AND IAE.COD_CIDADE NOT IN (9046,
            7260,
            6966,
            5665,
            5434,
            9965,
            7542,
            10852);*/ -- estדo sendo usadas na DBCEP
		
			IF NVALIDA > 0 THEN
			
				DELETE FROM DBSIAF.CIDADE IAE
				 WHERE IAE.COD_CIDADE = R_CID.COD_CIDADE;
				COMMIT;
			
			END IF;
		
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20500,
										'CIDADE' || '-' || R_CID.COD_CIDADE_MIN || '-' || R_CID.NOM_CIDADE || '-' || R_CID.COD_CIDADE || '-' || SQLERRM);
		END;
	END LOOP;

EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-20500,
								SQLERRM);
END;


/*
ALTER TRIGGER DBSIAF.TBUID_ENDERECO_PESSOA DISABLE; ALTER TRIGGER DBSIAF.TBUID_PESSOA_FISICA DISABLE; ALTER TRIGGER DBSIAF.TBUID_END_ALUNO DISABLE; ALTER TRIGGER DBSIAF.TBUID_PARAMETROS_CONTRATO_MOL DISABLE; ALTER TRIGGER DBSIAF.TBUID_END_INSTIT_EXTERNA DISABLE; ALTER TRIGGER DBSIAF.TBUID_INSCRICAO_EVENTO DISABLE; ALTER TRIGGER DBSIAF.TBUI_END_RESPONSAVEL DISABLE; ALTER TRIGGER DBSIAF.TBUID_ALUNO DISABLE; ALTER TRIGGER DBSIAF.TBUID_CIDADE DISABLE; ALTER TRIGGER DBVESTIB.TBUID_ENDERECO_ESCOLA_FIA DISABLE; ALTER TRIGGER DBVESTIB.TBUID_INSCRICAO DISABLE;

ALTER TRIGGER DBSIAF.TBUID_ENDERECO_PESSOA ENABLE; ALTER TRIGGER DBSIAF.TBUID_PESSOA_FISICA ENABLE; ALTER TRIGGER DBSIAF.TBUID_END_ALUNO ENABLE; ALTER TRIGGER DBSIAF.TBUID_PARAMETROS_CONTRATO_MOL ENABLE; ALTER TRIGGER DBSIAF.TBUID_END_INSTIT_EXTERNA ENABLE; ALTER TRIGGER DBSIAF.TBUID_INSCRICAO_EVENTO ENABLE; ALTER TRIGGER DBSIAF.TBUI_END_RESPONSAVEL ENABLE; ALTER TRIGGER DBSIAF.TBUID_ALUNO ENABLE; ALTER TRIGGER DBSIAF.TBUID_CIDADE ENABLE; ALTER TRIGGER DBVESTIB.TBUID_ENDERECO_ESCOLA_FIA ENABLE; ALTER TRIGGER DBVESTIB.TBUID_INSCRICAO ENABLE;

ALTER TABLE DBSIAF.CIDADE UNIQUE(UPPER(TRIM(TRANSLATE(NOM_CIDADE, 'ֱֹֽ׃ÚֲÊ־װÛְָּׂÙִֻֿײÜֳױַׁביםףתגךמפûאטלעשהכןצüדץחסA@#$%¨&*()-_+=|\/?!{},.;:"<>[]''^~`´÷°×''', 'AEIOUAEIOUAEIOUAEIOUAOCNaeiouaeiouaeiouaeuouaocnA'))),(COD_ESTADO))

*/
