DECLARE
	CURSOR C_ALUNO IS
		SELECT A.COD_ALUNO, a.cod_tpo_entrada
		  FROM DBSIAF.ALUNO      A,
			   DBVESTIB.CONCURSO CON
		 WHERE A.CODCONC = CON.CODCONC
			   AND CON.COD_TPO_CONCURSO = 69
			   AND A.COD_TPO_ENTRADA <> 93;
	CURSOR C_CONC IS
	
		SELECT *
		  FROM DBVESTIB.CONCURSO C
		 WHERE C.COD_TPO_CONCURSO = 69;
	CURSOR C_CAND IS
		SELECT CAN.*
		  FROM DBVESTIB.CANDIDATO CAN,
			   DBVESTIB.CONCURSO  CON
		 WHERE CAN.CODCONC = CON.CODCONC
			   AND CON.COD_TPO_CONCURSO = 69
			   AND CAN.FORMA_INGRESSO <> 93;
BEGIN
	FOR R_ALUNO IN C_ALUNO LOOP
		UPDATE DBSIAF.ALUNO A
		   SET A.COD_TPO_ENTRADA = 93
		 WHERE A.COD_ALUNO = R_ALUNO.COD_ALUNO;
	END LOOP;
	COMMIT;
	FOR R_CONC IN C_CONC LOOP
		UPDATE DBVESTIB.CONCURSO CON
		   SET CON.FORMA_INGRESSO = 93
		 WHERE CON.CODCONC = R_CONC.CODCONC;
	END LOOP;
	COMMIT;
	FOR R_CAN IN C_CAND LOOP
		UPDATE DBVESTIB.CANDIDATO CAN
		   SET CAN.FORMA_INGRESSO = 93
		 WHERE CAN.CODCONC = R_CAN.CODCONC
			   AND CAN.CODCAN = R_CAN.CODCAN;
	END LOOP;
	COMMIT;
END;
