DECLARE
	CONTA1 NUMBER;
	CONTA2 NUMBER;
	CURSOR C_PEG IS
	
		SELECT C.CODCONC
		  FROM DBVESTIB.PARAMETROS_CONCURSO C
		 WHERE C.IND_SELECIONA_POLO = 'S'
		
		UNION
		SELECT C.CODCONC
		  FROM DBVESTIB.CONCURSO C
		 WHERE C.COD_TPO_CONCURSO IN (1,
									  3,
									  64)
			   AND C.SEMCONC = '2'
			   AND C.ANOCONC = '2016';
BEGIN

	CONTA1 := 60;

	FOR R_PEG IN C_PEG LOOP
	
		SELECT COUNT(*)
		  INTO CONTA2
		  FROM DBVESTIB.PERGSOCECO PEG
		 WHERE CODCONC = R_PEG.CODCONC;
	
		IF CONTA1 > CONTA2 THEN
		
			DELETE FROM DBVESTIB.RESPSOCECO RES
			 WHERE RES.CODCONC = R_PEG.CODCONC;
		
			DELETE FROM DBVESTIB.PERGSOCECO
			 WHERE CODCONC = R_PEG.CODCONC;
		
			INSERT INTO DBVESTIB.PERGSOCECO
				(CODCONC,
				 CODPERG,
				 DSCPERG,
				 COD_COMPETENCIA)
				SELECT R_PEG.CODCONC,
					   CODPERG,
					   DSCPERG,
					   COD_COMPETENCIA
				  FROM DBVESTIB.PERGSOCECO PEG
				 WHERE PEG.CODCONC = '2575';
			COMMIT;
			INSERT INTO DBVESTIB.RESPSOCECO
				(CODCONC,
				 CODPERG,
				 CODRESP,
				 DSCRESP,
				 DSCRESPABERTA,
				 VALRESP)
				SELECT R_PEG.CODCONC,
					   CODPERG,
					   CODRESP,
					   DSCRESP,
					   DSCRESPABERTA,
					   VALRESP
				  FROM DBVESTIB.RESPSOCECO
				 WHERE CODCONC = '2575';
			COMMIT;
		END IF;
	END LOOP;
END;
