SELECT
    CCU.COD_CURSO CODCURSO,
    CCU.COD_COORDENADOR_CURSO CODCOORDENADORCURSO,
    CCU.COD_PROFESSOR CODPROFESSOR,
    CCU.DAT_INI_MANDATO DATINIMANDATO,
    CCU.IDT_ATUACAO AS IDTATUACAO,
    CCU.DAT_FIM_MANDATO DATFIMMANDATO,
    CUR.NOM_CURSO NOMCURSO,
    CCU.COD_QUALIFICACAO CODQUALIFICACAO,
CUR.NOM_CURSO || ' ' || (SELECT ' - ' || DSC_QUALIFICADOR FROM DBSIAF.QUALIFICADOR QUR, DBSIAF.QUALIFICACAO QUA WHERE QUA.COD_QUALIFICADOR = QUR.COD_QUALIFICADOR AND QUA.COD_QUALIFICACAO = CCU.COD_QUALIFICACAO) AS DSCCURSOQUALIFICACAO,
    CAM.COD_CAMPUS CODCAMPUS,
    cam.nom_campus NOMCAMPUS,
    cam.nom_campus
FROM 
    DBSIAF.COORDENADOR_CURSO CCU,
    DBSIAF.PROFESSOR PRO,
    DBSIAF.CURSO CUR,
    DBSIAF.CAMPUS CAM
WHERE
    PRO.COD_PROFESSOR = 26504 AND
    PRO.COD_PROFESSOR = CCU.COD_PROFESSOR AND
CCU.IDT_ATUACAO = 'C' AND
    CCU.COD_CURSO = CUR.COD_CURSO AND
     CCU.cod_coordenador_curso = DBSIAF.PC_PROFESSOR.F_COORDENADOR_CURSO(cur.cod_curso,CCU.COD_QUALIFICACAO,PRO.cod_professor,CAM.COD_CAMPUS) AND
    CAM.COD_CAMPUS (+)= CCU.COD_CAMPUS 
UNION
SELECT
    CCU.COD_CURSO CODCURSO,
    CCU.COD_COORDENADOR_CURSO CODCOORDENADORCURSO,
    CCU.COD_PROFESSOR CODPROFESSOR,
    CCU.DAT_INI_MANDATO DATINIMANDATO,
    CCU.IDT_ATUACAO AS IDTATUACAO,
    CCU.DAT_FIM_MANDATO DATFIMMANDATO,
    CUR.NOM_CURSO NOMCURSO,
    CCU.COD_QUALIFICACAO CODQUALIFICACAO,
CUR.NOM_CURSO || ' ' || (SELECT ' - ' || DSC_QUALIFICADOR FROM DBSIAF.QUALIFICADOR QUR, DBSIAF.QUALIFICACAO QUA WHERE QUA.COD_QUALIFICADOR = QUR.COD_QUALIFICADOR AND QUA.COD_QUALIFICACAO = CCU.COD_QUALIFICACAO) AS DSCCURSOQUALIFICACAO,
    CAM.COD_CAMPUS CODCAMPUS,
    cam.nom_campus NOMCAMPUS,
    cam.nom_campus
FROM 
    DBSIAF.COORDENADOR_CURSO CCU,
    DBSIAF.PROFESSOR PRO,
    DBSIAF.CURSO CUR,
    DBSIAF.CAMPUS CAM
WHERE
    PRO.COD_PROFESSOR = 26504 AND
    PRO.COD_PROFESSOR = CCU.COD_PROFESSOR AND
CCU.IDT_ATUACAO = 'D' AND
    CCU.COD_CURSO = CUR.COD_CURSO AND
     CCU.cod_coordenador_curso = DBSIAF.PC_PROFESSOR.F_DIRETOR_CURSO(cur.cod_curso,CCU.COD_QUALIFICACAO,PRO.cod_professor,CAM.COD_CAMPUS) AND
    CAM.COD_CAMPUS (+)= CCU.COD_CAMPUS ;
    
