SELECT AL.NUM_CPF NUMCPF,al.dat_nascimento,
    AL.COD_ALUNO CODALUNO,
    AL.NOM_ALUNO NOMALUNO, 
    AL.COD_PESSOA CODPESSOA,
    ST.DSC_STA_ALUNO DSCSTAALUNO,
    AL.NUM_MATRICULA NUMMATRICULA, 
    AL.COD_OCORRENCIA CODOCORRENCIA,
    CU.NOM_CURSO NOMCURSO, 
    CU.COD_CURSO CODCURSO, 
    TU.DSC_TURNO DSCTURNO, 
    AL.IND_REG_FINANCEIRO INDREGFINANCEIRO,
    TU.COD_TURNO CODTURNO, 
    CA.NOM_CAMPUS NOMCAMPUS,
    CA.COD_CAMPUS CODCAMPUS,
    AL.EML_ALUNO EMLALUNO,
    AL.NUM_CREDITO NUMCREDITO,
    AL.COD_TPO_FORMATO CODTPOFORMATO,
    AL.COD_STA_ALUNO CODSTAALUNO,
    AL.IND_FORMANDO INDFORMANDO,
    AL.COD_TPO_SAIDA CODTPOSAIDA,
    AL.NUM_CPF NUMCPF,
    PC_RELATORIO_EDITOR.F_RETORNA_CURSO(AL.cod_aluno) AS NOMCURSODESTINO,
  INS.NOM_INSTITUICAO NOMINSTITUICAO,
  INS.SGL_INSTITUICAO SGLINSTITUICAO,
                        INS.COD_INSTITUICAO CODINSTITUICAO
FROM 
  DBSIAF.ALUNO AL, 
  DBSIAF.CAMPUS CA, 
  DBSIAF.CURSO CU,
  DBSIAF.STATUS_ALUNO ST,
  DBSIAF.TURNO TU,
  DBSIAF.INSTITUICAO_ENSINO INS
WHERE   
  ST.COD_STA_ALUNO = AL.COD_STA_ALUNO AND
  AL.COD_CURSO = CU.COD_CURSO AND 
  AL.COD_TURNO = TU.COD_TURNO AND 
  AL.COD_CAMPUS = CA.COD_CAMPUS AND
  INS.COD_INSTITUICAO = CA.COD_INSTITUICAO 
--  and al.cod_instituicao =
  --and TRIM(REPLACE(REPLACE(AL.NUM_CPF,'.'), '-')) = TRIM(REPLACE(REPLACE('941.551.006-49','.'), '-')) AND AL.DAT_NASCIMENTO = to_date('22/11/1973','DD/MM/YYYY')  
  AND AL.COD_TPO_SAIDA NOT IN (14) AND AL.COD_STA_ALUNO IN (2,3,4,7,8) AND AL.DAT_SAIDA IS NOT NULL AND  AL.COD_TPO_SAIDA IS NOT NULL AND dbsiaf.pc_funcoes.F_INSTITUICOES_ASSOCIADAS(CA.COD_INSTITUICAO,5) = 'S' 
                                                AND EXISTS (SELECT 1 FROM DBSIAF.DOCUM_ALUNO DAL
                                                     INNER JOIN DBSIAF.TIPO_DOCUMENTO TDO
                                                        ON TDO.COD_TPO_DOCUMENTO = DAL.COD_TPO_DOCUMENTO
                                                           AND TDO.COD_TPO_DOCUMENTO IN (8,16)
                                                           AND DAL.IND_ENTREGA_DOC = 'N'
                                                           AND ((DAL.DAT_PRAZO_ENTREGA IS NULL) OR (DAL.DAT_PRAZO_ENTREGA < SYSDATE))
                                                     WHERE DAL.COD_ALUNO = AL.COD_ALUNO)
ORDER BY 
  NOM_ALUNO 
