DECLARE

	CURSOR C_FUNCIONARIO IS
	
		SELECT FUN.CPF_FUNCIONARIO,
			   BAS.COD_EMPRESA,
			   EMF.COD_INSTITUICAO,
			   FUN.COD_FUNCIONARIO
		  FROM DBSIAF.FUNCIONARIO              FUN,
			   DBSIAF.BASE_FUNCIONARIO         BAS,
			   DBSIAF.BASE_EMPRESA_FUNCIONARIO EMF
		 WHERE FUN.CPF_FUNCIONARIO = BAS.CPF_FUNCIONARIO
			   AND BAS.IND_ATIVO = 'S'
			   AND EMF.COD_EMPRESA = BAS.COD_EMPRESA;

	CURSOR C_INSTITUICAO(CODIES DBSIAF.INSTITUICAO_ASSOCIADA.COD_INSTITUICAO%TYPE) IS
		SELECT TIT.COD_INSTITUICAO,
			   TIT.COD_INSTITUICAO_ASSOCIADA
		  FROM DBSIAF.INSTITUICAO_ASSOCIADA TIT
		 WHERE TIT.COD_INSTITUICAO = NVL(CODIES,
										 TIT.COD_INSTITUICAO);

	CURSOR C_CAMPUS(COD_IES DBSIAF.CAMPUS.COD_INSTITUICAO%TYPE) IS
		SELECT CAM.COD_CAMPUS
		  FROM DBSIAF.CAMPUS CAM
		 WHERE CAM.COD_INSTITUICAO = COD_IES;

	EXISTE NUMBER;
BEGIN
	FOR R_FUNCIONARIO IN C_FUNCIONARIO LOOP
	
		FOR R_INSTITUICAO IN C_INSTITUICAO(R_FUNCIONARIO.COD_INSTITUICAO) LOOP
		
			FOR R_CAMPUS IN C_CAMPUS(R_INSTITUICAO.COD_INSTITUICAO) LOOP
			
				SELECT COUNT(1)
				  INTO EXISTE
				  FROM DBSIAF.CAMPUS_FUNCIONARIO FUN
				 WHERE FUN.COD_FUNCIONARIO = R_FUNCIONARIO.COD_FUNCIONARIO
					   AND FUN.COD_CAMPUS = R_CAMPUS.COD_CAMPUS;
			
				IF EXISTE = 0 THEN
				
					INSERT INTO DBSIAF.CAMPUS_FUNCIONARIO
						(COD_FUNCIONARIO,
						 COD_CAMPUS)
					VALUES
						(R_FUNCIONARIO.COD_FUNCIONARIO,
						 R_CAMPUS.COD_CAMPUS);
				
				END IF;
			
			END LOOP;
		
			FOR R_CAMPUS IN C_CAMPUS(R_INSTITUICAO.COD_INSTITUICAO_ASSOCIADA) LOOP
			
				SELECT COUNT(1)
				  INTO EXISTE
				  FROM DBSIAF.CAMPUS_FUNCIONARIO FUN
				 WHERE FUN.COD_FUNCIONARIO = R_FUNCIONARIO.COD_FUNCIONARIO
					   AND FUN.COD_CAMPUS = R_CAMPUS.COD_CAMPUS;
			
				IF EXISTE = 0 THEN
				
					INSERT INTO DBSIAF.CAMPUS_FUNCIONARIO
						(COD_FUNCIONARIO,
						 COD_CAMPUS)
					VALUES
						(R_FUNCIONARIO.COD_FUNCIONARIO,
						 R_CAMPUS.COD_CAMPUS);
				
				END IF;
			
			END LOOP;
		END LOOP;
	
	END LOOP;

END;
