SELECT PR.COD_PROFESSOR    CODPROFESSOR,
	   PR.LOG_PROFESSOR    "LOGIN",
	   PR.NOM_PROFESSOR,
       STP.DSC_STA_PROFESSOR "STATUS",
	   INS.COD_INSTITUICAO
  FROM DBSIAF.PROFESSOR PR
 INNER JOIN DBSIAF.DEPARTAMENTO_ENSINO DEP
	ON DEP.COD_DEPARTAMENTO = PR.COD_DEPARTAMENTO
 INNER JOIN DBSIAF.INSTITUICAO_ENSINO INS
	ON INS.COD_INSTITUICAO = DEP.COD_INSTITUICAO
  LEFT JOIN DBADM.USUARIO USU
	ON USU.COD_PESSOA = PR.COD_PESSOA
  LEFT JOIN DBSIAF.CODIGO_SEGURANCA_PESSOA CSP
	ON CSP.COD_PESSOA = PR.COD_PESSOA
  LEFT JOIN DBSIAF.VW_BIBLIOTECA_EMP_INST BEI
	ON BEI.COD_INSTITUICAO = INS.COD_INSTITUICAO
 INNER JOIN DBSIAF.STATUS_PROFESSOR STP
	ON STP.COD_STA_PROFESSOR = PR.COD_STA_PROFESSOR 
 WHERE INS.COD_INSTITUICAO = 8
	   AND PR.COD_STA_PROFESSOR = 2
       AND PR.COD_PESSOA IS NOT NULL
       AND EXISTS (SELECT 1
		  FROM DBSIAF.DIARIO_CLASSE DIC
          INNER JOIN DBSIAF.PERIODO_LETIVO PLT    ON PLT.COD_INSTITUICAO = 8 AND DIC.COD_PERIODO_LETIVO = PLT.COD_PERIODO_LETIVO AND PLT.IND_LIBERADO = 'N'
		 WHERE DIC.COD_PROFESSOR = PR.COD_PROFESSOR)
