DECLARE
	CURSOR C_INSC IS
		SELECT CODINSC,
			   CODCONC,
			   COD_STATUS_INSCRICAO,
			   I.DATPGTO,
			   I.VALPAGO
		  FROM DBVESTIB.INSCRICAO I
		 WHERE CODCONC = '2994'
			   AND COD_STATUS_INSCRICAO = 1
			   AND CODINSC = '629391'
			   AND  EXISTS (SELECT 1
				  FROM DBVESTIB.CANDIDATO C
				 WHERE C.CODCONC = I.CODCONC
					   AND C.CODCAN = I.CODINSC)
			   AND EXISTS (SELECT 1
				  FROM DBVESTIB.OPCAOCANDIDATO O
				 WHERE O.CODCONC = I.CODCONC
					   AND O.CODINSC = I.CODINSC);

	NVALIDA NUMBER;
BEGIN
	FOR R_INSC IN C_INSC LOOP
	
		SELECT COUNT(1)
		  INTO NVALIDA
		  FROM DBVESTIB.RCANDCURTUROPC R
		 WHERE R.CODCONC = R_INSC.CODCONC
			   AND R.CODCAN = R_INSC.CODINSC;
	
		IF NVALIDA > 0 THEN
			DELETE FROM DBVESTIB.RCANDCURTUROPC R
			 WHERE R.CODCONC = R_INSC.CODCONC
				   AND R.CODCAN = R_INSC.CODINSC;
			COMMIT;
		END IF;
	
		UPDATE DBVESTIB.INSCRICAO I
		   SET I.DATPGTO = SYSDATE
		 WHERE I.CODCONC = R_INSC.CODCONC
			   AND I.CODINSC = R_INSC.CODINSC;
	
		/*DBVESTIB.SP_CONFIRMA_INSC_INTERNET(R_INSC.CODCONC,
                                               R_INSC.CODINSC);
        */
		DBVESTIB.PC_EXTENSAO.SP_ATUALIZA_STATUS(R_INSC.CODCONC,
												R_INSC.CODINSC,
												2);
		COMMIT;
	END LOOP;
END;
