-- Add/modify columns 
alter table DBVESTIB.CAMPUS_LOG add CODINSTITUICAO NUMBER(10);


-- Add/modify columns 
alter table DBVESTIB.CURSO_CAMPUS_LOG add COD_PERIODO_LETIVO NUMBER(10);
alter table DBVESTIB.CURSO_CAMPUS_LOG add COD_CURSO_SIAF NUMBER(10);
alter table DBVESTIB.CURSO_CAMPUS_LOG add COD_CURSO_SIAF_TURMA NUMBER(10);
