CREATE OR REPLACE PROCEDURE DBVESTIB.SP_IMPORTA_CANDIDATO(
    -- DADOS PESSOAIS
    P_CODCONC DBVESTIB.CANDIDATO.CODCONC%TYPE,
    P_NOMCAN DBVESTIB.CANDIDATO.NOMCAN%TYPE,
    P_SEXCAN DBVESTIB.CANDIDATO.SEXCAN%TYPE,
    P_DATNASCAN  DBVESTIB.CANDIDATO.DATNASCAN%TYPE,
    P_CODTPODEF  DBVESTIB.CANDIDATO.CODTPODEF%TYPE,
    P_CANHOTO  DBVESTIB.CANDIDATO.CANHOTO%TYPE,
    P_IND_TREINANTE  DBVESTIB.CANDIDATO.IND_TREINANTE%TYPE,
    P_INDLEESCREVE  DBVESTIB.CANDIDATO.INDLEESCREVE%TYPE,

    -- DOCUMENTOS
    P_IDECAN  DBVESTIB.CANDIDATO.IDECAN%TYPE,
    P_NOMIDECAN  DBVESTIB.CANDIDATO.NOMIDECAN%TYPE,
    P_EXPIDECAN  DBVESTIB.CANDIDATO.EXPIDECAN%TYPE,
    P_CPFCAN  DBVESTIB.CANDIDATO.CPFCAN%TYPE,

    -- CONTATO
    P_TELCAN  DBVESTIB.CANDIDATO.TELCAN%TYPE,
    P_EMAIL  DBVESTIB.CANDIDATO.EMAIL%TYPE,
    P_CELCAN  DBVESTIB.CANDIDATO.CELCAN%TYPE,

    -- ENDERECO
    P_ENDCAN  DBVESTIB.CANDIDATO.ENDCAN%TYPE,
    P_NUMEND  DBVESTIB.CANDIDATO.NUMEND%TYPE,
    P_COMPLEMENTO  DBVESTIB.CANDIDATO.COMPLEMENTO%TYPE,
    P_BAICAN  DBVESTIB.CANDIDATO.BAICAN%TYPE,
    P_CIDCAN  DBVESTIB.CANDIDATO.CIDCAN%TYPE,
    P_ESTCAN  DBVESTIB.CANDIDATO.ESTCAN%TYPE,
    P_CEPCAN  DBVESTIB.CANDIDATO.CEPCAN%TYPE,

    -- DATA DE INSCRICAO
    P_DATINSCAN  DBVESTIB.CANDIDATO.DATINSCAN%TYPE,

    -- DATA DE PAGAMENTO
    P_DATPAGCAN  DBVESTIB.CANDIDATO.DATPAGCAN%TYPE,

    -- LOCAL DE PAGAMENTO
    P_CODLOCPAG  DBVESTIB.CANDIDATO.CODLOCPAG%TYPE,

    -- PARENTES
    P_NOM_PAI  DBVESTIB.CANDIDATO.NOM_PAI%TYPE,
    P_NOM_MAE  DBVESTIB.CANDIDATO.NOM_MAE%TYPE,

    -- ESCOLA
    P_NOMEESC  DBVESTIB.CANDIDATO.NOMEESC%TYPE,
    P_ENDESC  DBVESTIB.CANDIDATO.ENDESC%TYPE,
    P_NUM_ESCOLA  DBVESTIB.CANDIDATO.NUM_ESCOLA%TYPE,
    P_COMPLEMENTO_ESCOLA  DBVESTIB.CANDIDATO.COMPLEMENTO_ESCOLA%TYPE,
    P_BAIESC  DBVESTIB.CANDIDATO.BAIESC%TYPE,
    P_CEPESC  DBVESTIB.CANDIDATO.CEPESC%TYPE,
    P_CIDESC  DBVESTIB.CANDIDATO.CIDESC%TYPE,
    P_TELESC  DBVESTIB.CANDIDATO.TELESC%TYPE,

    -- EMPREGADO
    P_REG_EMPREGADO  DBVESTIB.CANDIDATO.REG_EMPREGADO%TYPE,
    P_NOM_EMPREGADO  DBVESTIB.CANDIDATO.NOM_EMPREGADO%TYPE,
    P_RAMAL  DBVESTIB.CANDIDATO.RAMAL%TYPE,
    P_DSCCRESP  DBVESTIB.CANDIDATO.DSCCRESP%TYPE,
    P_DSCEQUIPE  DBVESTIB.CANDIDATO.DSCEQUIPE%TYPE,
    P_CODEMP  DBVESTIB.CANDIDATO.CODEMP%TYPE,
    P_INDUSATRANS  DBVESTIB.CANDIDATO.INDUSATRANS%TYPE,
    P_CODCAMPROXRESIDENCIA  DBVESTIB.CANDIDATO.CODCAMPROXRESIDENCIA%TYPE,

    -- LOCAL E FISCAL DE INSCRICAO
    P_COD_LOC_INSCRICAO  DBVESTIB.CANDIDATO.COD_LOC_INSCRICAO%TYPE,
    P_COD_FIS_INSCRICAO  DBVESTIB.CANDIDATO.COD_FIS_INSCRICAO%TYPE,

    -- OPCAO DE CURSO
    P_CODCUR  DBVESTIB.RCANDCURTUROPC.CODCUR%TYPE,
    P_CODTUR  DBVESTIB.RCANDCURTUROPC.CODTUR%TYPE,
    P_OPCLIN  DBVESTIB.RCANDCURTUROPC.OPCLIN%TYPE

) IS
  N_CODCAN DBVESTIB.CANDIDATO.CODCAN%TYPE;
  N_FORMA_INGRASSO DBVESTIB.CONCURSO.FORMA_INGRESSO%TYPE;
  V_DSC_LOG_ERRO VARCHAR2(4000);
BEGIN

     -- OBTENDO FORMA DE INGRESSO
     SELECT CON.FORMA_INGRESSO
     INTO N_FORMA_INGRASSO
     FROM DBVESTIB.CONCURSO CON
     WHERE CON.CODCONC = P_CODCONC;

     -- CODIGO DE INSCRICAO
     SELECT DBVESTIB.INSCRICAO_S.NEXTVAL
     INTO N_CODCAN
     FROM DUAL;

     -- INSERINDO CANDIDATO
     INSERT INTO DBVESTIB.CANDIDATO(
      CODCONC,
      CODCAN,
      NOMCAN,
      SEXCAN,
      CANHOTO,
      TAG,
      REGFCH,
      FLGMAT,
      DATINCCAN,
      CODTPODEF,
      IND_TREINANTE,
      DATNASCAN,
      IDECAN,
      NOMIDECAN,
      EXPIDECAN,
      TELCAN,
      ENDCAN,
      BAICAN,
      CIDCAN,
      ESTCAN,
      CEPCAN,
      DATINSCAN,
      DATPAGCAN,
      CODLOCPAG,
      EMAIL,
      NOM_PAI,
      NOM_MAE,
      REG_EMPREGADO,
      NOM_EMPREGADO,
      CELCAN,
      CPFCAN,
      NOMEESC,
      RAMAL,
      TELESC,
      DSCCRESP,
      DSCEQUIPE,
      INDUSATRANS,
      CODEMP,
      INDLEESCREVE,
      ENDESC,
      COMPLEMENTO,
      NUMEND,
      COD_LOC_INSCRICAO,
      COD_FIS_INSCRICAO,
      BAIESC,
      CEPESC,
      CIDESC,
      NUM_ESCOLA,
      COMPLEMENTO_ESCOLA,
      CODCAMPROXRESIDENCIA
    )
    VALUES(
      P_CODCONC,
      N_CODCAN,
      P_NOMCAN,
      P_SEXCAN,
      P_CANHOTO,
      'N',
      'N',
      'N',
      SYSDATE,
      P_CODTPODEF,
      P_IND_TREINANTE,
      P_DATNASCAN,
      P_IDECAN,
      P_NOMIDECAN,
      P_EXPIDECAN,
      P_TELCAN,
      P_ENDCAN,
      P_BAICAN,
      P_CIDCAN,
      P_ESTCAN,
      P_CEPCAN,
      NVL( P_DATINSCAN, SYSDATE),
      NVL( P_DATPAGCAN, SYSDATE),
      NVL(P_CODLOCPAG, '002'),
      P_EMAIL,
      P_NOM_PAI,
      P_NOM_MAE,
      P_REG_EMPREGADO,
      P_NOM_EMPREGADO,
      P_CELCAN,
      P_CPFCAN,
      P_NOMEESC,
      P_RAMAL,
      P_TELESC,
      P_DSCCRESP,
      P_DSCEQUIPE,
      P_INDUSATRANS,
      P_CODEMP,
      P_INDLEESCREVE,
      P_ENDESC,
      P_COMPLEMENTO,
      P_NUMEND,
      P_COD_LOC_INSCRICAO,
      P_COD_FIS_INSCRICAO,
      P_BAIESC,
      P_CEPESC,
      P_CIDESC,
      P_NUM_ESCOLA,
      P_COMPLEMENTO_ESCOLA,
      P_CODCAMPROXRESIDENCIA
    );

    -- 1ª OPÇÃO DE CURSO
    INSERT INTO DBVESTIB.RCANDCURTUROPC(CODCONC,CODCAN,CODCUR,CODTUR,OPCLIN,NROOPC)
    VALUES(
        P_CODCONC,
        N_CODCAN,
        P_CODCUR,
        P_CODTUR,
        nvl(P_OPCLIN,'0'),
        '1'
    );

EXCEPTION
         WHEN OTHERS THEN              
              
              V_DSC_LOG_ERRO:= 'Candidato: '||P_NOMCAN|| '. Erro: '||SQLERRM;           
              INSERT INTO DBVESTIB.LOG_ERRO_IMPORT(COD_LOG_ERRO,DSC_LOG_ERRO)
              VALUES(DBVESTIB.LOG_ERRO_IMPORT_S.NEXTVAL, V_DSC_LOG_ERRO);

END;
/
