CREATE OR REPLACE TRIGGER "DBSIAF"."TAI_CAMPUS"
	AFTER INSERT ON DBSIAF.CAMPUS
DECLARE

	CURSOR C_USUARIO(P_CODIES DBSIAF.CAMPUS.COD_INSTITUICAO%TYPE) IS
	
		SELECT DISTINCT USI.COD_USUARIO,
						USI.COD_INSTITUICAO,
						BAS.COD_FUNCIONARIO
		  FROM DBADM.USUARIO             USU,
			   DBSIAF.BASE_FUNCIONARIO   BAS,
			   DBSIAF.PESSOA             PES,
			   DBADM.USUARIO_INSTITUICAO USI
		 WHERE BAS.COD_PESSOA = PES.COD_PESSOA
			   AND USU.COD_PESSOA = BAS.COD_PESSOA
			   AND USI.COD_USUARIO = USU.COD_USUARIO
			   AND BAS.IND_ATIVO = 'S'
			   AND USI.COD_INSTITUICAO = CODIES;

	CURSOR C_CAMPUS(P_CODIES DBSIAF.CAMPUS.COD_INSTITUICAO%TYPE) IS
		SELECT CAM.COD_CAMPUS
		  FROM DBSIAF.CAMPUS CAM
		 WHERE CAM.COD_INSTITUICAO = P_CODIES;

	CODIES DBSIAF.CAMPUS.COD_INSTITUICAO%TYPE;
BEGIN
	CODIES := DBADM.F_SELECT_AUTONOMOUS('SELECT DISTINCT CAM.COD_INSTITUICAO FROM DBSIAF.CAMPUS CAM
		  WHERE CAM.COD_CAMPUS = ' || NEW.COD_CAMPUS);
	FOR R_USUARIO IN C_USUARIO(CODIES) LOOP
		INSERT INTO DBSIAF.CAMPUS_FUNCIONARIO
			(COD_FUNCIONARIO,
			 COD_CAMPUS)
		VALUES
			(R_USUARIO.COD_USUARIO,
			 NEW.COD_CAMPUS);
	END LOOP;
	COMMIT;
END;
EXCEPTION
	WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20500, SQLERRM); END;
