
SELECT AGE.COD_AGENDAMENTO CODAGENDAMENTO,
	   INS.NOMCAN AS "Candidato",
	   INS.DATNASCAN,
	   INS.CODCAN,
	   (SELECT CUR.NOMCUR || ' (' || TUR.DSCTUR || ')'
		  FROM DBVESTIB.CURSO CUR,
			   DBVESTIB.TURNO TUR
		 WHERE CUR.CODCONC = INS.CODCONC
			   AND CUR.CODCUR = OPC.CODCUR
			   AND TUR.CODTUR = OPC.CODTUR) AS "1 Curso/Turno",
	   NOMCONC,
	   INS.IDECAN,
	   TO_CHAR(DIP.DAT_HORA_INICIO,
			   'DD/MM/YYYY') AS DATINICIO,
	   TO_CHAR(DIP.DAT_HORA_INICIO,
			   'HH24:MI') AS HORA_INICIO,
	   EST.DSC_ESTRUTURA "Local",
	   EST.COD_ESTRUTURA,
	   OPC.CODINSTITUICAO COD_INSTITUICAO
  FROM DBSAG.AGENDAMENTO                  AGE,
	   DBSAG.DISPONIBILIDADE_PESSOA       DIP,
	   DBSAG.PESSOA_PROCESSO              PEP,
	   DBSAG.MAPEAMENTO_PES_PESSOA        MPP,
	   DBSAG.LOCAL_PROCESSO               LOP,
	   DBSAG.MAPEAMENTO_LOC_ESTRUTURA     MLE,
	   DBSIAF.ESTRUTURA_ORGANIZACIONAL    EST,
	   DBSAG.MAPEAMENTO_CLI_INSCRICAO     MCI,
	   DBVESTIB.CANDIDATO                 INS,
	   DBVESTIB.CONC_PROCESSO_AGENDAMENTO CPA,
	   DBVESTIB.CONCURSO                  CON,
	   DBVESTIB.RCANDCURTUROPC            OPC,
	   DBVESTIB.CAMPUS                    CMP
 WHERE AGE.COD_DISPONIBILIDADE = DIP.COD_DISPONIBILIDADE
	   AND CON.CODCONC = INS.CODCONC
	   AND PEP.COD_MAPEAMENTO_PESSOA = MPP.COD_MAPEAMENTO_PESSOA
	   AND CPA.COD_PROCESSO = LOP.COD_PROCESSO
	   AND LOP.COD_MAPEAMENTO_LOCAL = MLE.COD_MAPEAMENTO_LOCAL
	   AND MLE.COD_ESTRUTURA = EST.COD_ESTRUTURA
	   AND AGE.COD_MAPEAMENTO_CLIENTE = MCI.COD_MAPEAMENTO_CLIENTE
	   AND MCI.CODINSC = INS.CODCAN
	   AND MCI.CODCONC = INS.CODCONC
	   AND DIP.COD_PESSOA_PROCESSO = PEP.COD_PESSOA_PROCESSO
	   AND PEP.COD_PROCESSO = CPA.COD_PROCESSO
	   AND CPA.CODCONC = '1522' --:P_CODCONC
	   AND LOP.COD_LOCAL_PROCESSO = DIP.COD_LOCAL_PROCESSO
	   AND OPC.NROOPC = '1'
	   AND OPC.CODCONC = INS.CODCONC
	   AND OPC.CODCAN = INS.CODCAN
	   AND ((DIP.DAT_HORA_INICIO = TO_DATE( :P_DATINICI || :P_HORA, 'DD/MM/YY HH24:MI')) OR ((TRUNC(DIP.DAT_HORA_INICIO) = TO_DATE( :P_DATINICI || ' 00:00','DD/MM/YY HH24:MI') AND ( :P_HORA IS NULL))))
	   AND CMP.CODCAM = OPC.CODCAM
	   AND CMP.COD_CAMPUS_SIAF IN (SELECT CPU.COD_CAMPUS
									 FROM DBADM.USUARIO             USU,
										  DBSIAF.CAMPUS_FUNCIONARIO CAM,
										  DBSIAF.CAMPUS             CPU
									WHERE CAM.COD_FUNCIONARIO = USU.COD_USUARIO
										  AND USU.COD_USUARIO = 13391
										  AND CPU.COD_CAMPUS = CAM.COD_CAMPUS
										  AND CPU.IND_ATIVO = 'S'
										  AND CPU.COD_INSTITUICAO = 1)

UNION

SELECT NULL CODAGENDAMENTO,
	   NULL "Candidato",
	   NULL DATNASCAN,
	   NULL CODCAN,
	   NULL "1 Curso/Turno",
	   NULL NOMCONC,
	   NULL IDECAN,
	   NULL DATINICIO,
	   NULL HORA_INICIO,
	   NULL "Local",
	   NULL COD_ESTRUTURA,
	   NULL COD_INSTITUICAO
  FROM DBADM.USUARIO       USU,
	   DBADM.USUARIO_GRUPO USG,
	   DBADM.GRP_USUARIO   UGR
 WHERE UGR.COD_GRP_USUARIO IN (235,
							   294,
							   2)
	   AND UGR.COD_GRP_USUARIO = USG.COD_GRP_USUARIO
	   AND USU.COD_USUARIO = USG.COD_USUARIO
	   AND USU.COD_USUARIO = 13391;
       
       GRANT SELECT ON DBVESTIB.VW_LOCAL_EAD TO desenv WITH GRANT OPTION
              GRANT SELECT ON DBADM.USUARIO_GRUPO TO DBVESTIB WITH GRANT OPTION
              
              
              SELECT * FROM DBVESTIB.VW_LOCAL_EAD loc
              where loc.cod_instituicao = 6;
              
              
select * from dbsiaf.aluno a
where a.codconc = '1965'              
and num_cpf = '26855881831'
select * from dbvestib.registro_deferimento
codcan = '132408'


select * from dbvestib.tmp_dados_import
