CREATE OR REPLACE VIEW DBVESTIB.VW_INSCRICOES_PROCESSO AS
SELECT
  INSCRICAO.NOMCAN NOME,
  INSCRICAO.CODINSC INSCRICAO,
  INSCRICAO.CPFCAN CPF,
  TO_CHAR(INSCRICAO.DATINSCAN,'DD/MM/YY HH24:MI') DATA_INSCRICAO,
  DBVESTIB.F_STATUS_INSCRICAO_PROCESSO(INSCRICAO.CODINSC,INSCRICAO.CODCONC) AS STATUS_GERAL,
  DBVESTIB.F_STATUS_INSCRICAO_PROCESSOCOD(INSCRICAO.CODINSC,INSCRICAO.CODCONC) AS STATUS_GERAL_CODIGO,
  INSCRICAO.DATPGTO DATA_PAGAMENTO,
  'R$ '||DBVESTIB.PC_CONCURSO.F_VALOR_INSCRICAO(INSCRICAO.CODCONC,INSCRICAO.CODINSC) VALOR_INSCRICAO,
  TIPENT.DSC_TPO_ENTRADA AS TIPO_ENTRADA,
  INSCRICAO.OBSINSC OBSERVACAO,
  INSCRICAO.MATRICULA MATRICULA_RA,
/*  (SELECT '1 - '||NOMCUR||' - '||DSCTUR||' - '||NOMCAM||' / ' FROM
  DBVESTIB.INSCRICAO INC, DBVESTIB.OPCAOCANDIDATO OPC, DBVESTIB.CURSO CUR, DBVESTIB.CAMPUS CAM, DBVESTIB.TURNO TUR
  WHERE   INC.CODCONC = INSCRICAO.CODCONC AND   INC.CODINSC = INSCRICAO.CODINSC AND   OPC.CODCONC = INC.CODCONC AND
  OPC.CODINSC = INC.CODINSC AND   OPC.CODCUR = CUR.CODCUR AND   OPC.CODCONC = CUR.CODCONC AND   OPC.CODTUR = TUR.CODTUR AND
  CAM.CODCAM = OPC.CODCAM AND   OPC.NROOPC = 1)||
  (SELECT '2 - '||NOMCUR||' - '||DSCTUR||' - '||NOMCAM||' / ' FROM
  DBVESTIB.INSCRICAO INC, DBVESTIB.OPCAOCANDIDATO OPC, DBVESTIB.CURSO CUR, DBVESTIB.CAMPUS CAM, DBVESTIB.TURNO TUR
  WHERE   INC.CODCONC = INSCRICAO.CODCONC AND   INC.CODINSC = INSCRICAO.CODINSC AND   OPC.CODCONC = INC.CODCONC AND
  OPC.CODINSC = INC.CODINSC AND   OPC.CODCUR = CUR.CODCUR AND   OPC.CODCONC = CUR.CODCONC AND   OPC.CODTUR = TUR.CODTUR AND
  CAM.CODCAM = OPC.CODCAM AND   OPC.NROOPC = 2)||
  (SELECT '3 - '||NOMCUR||' - '||DSCTUR||' - '||NOMCAM||' / ' FROM
  DBVESTIB.INSCRICAO INC, DBVESTIB.OPCAOCANDIDATO OPC, DBVESTIB.CURSO CUR, DBVESTIB.CAMPUS CAM, DBVESTIB.TURNO TUR
  WHERE   INC.CODCONC = INSCRICAO.CODCONC AND   INC.CODINSC = INSCRICAO.CODINSC AND   OPC.CODCONC = INC.CODCONC AND
  OPC.CODINSC = INC.CODINSC AND   OPC.CODCUR = CUR.CODCUR AND   OPC.CODCONC = CUR.CODCONC AND   OPC.CODTUR = TUR.CODTUR AND
  CAM.CODCAM = OPC.CODCAM AND   OPC.NROOPC = 3)
  AS OPCOES_DE_CURSO,*/
  OPCAO1.NOMCUR NOMCUR_1,
  OPCAO1.DSCTUR DSCTUR_1,
  OPCAO1.NOMCAM NOMCAM_1,
  OPCAO2.NOMCUR NOMCUR_2,
  OPCAO2.DSCTUR DSCTUR_2,
  OPCAO2.NOMCAM NOMCAM_2,
  OPCAO3.NOMCUR NOMCUR_3,
  OPCAO3.DSCTUR DSCTUR_3,
  OPCAO3.NOMCAM NOMCAM_3,

  (SELECT COUNT(TCD.COD_TPO_DOCUMENTO)
  FROM DBVESTIB.TIPO_CONCURSO_DOCUMENTO TCD
   WHERE  TCD.COD_TPO_CONCURSO = CON.COD_TPO_CONCURSO
   AND TCD.COD_TPO_ENTRADA = TIPENT.COD_TPO_ENTRADA
   AND TCD.COD_TPO_DOCUMENTO NOT IN (SELECT REG.COD_TPO_DOCUMENTO FROM DBVESTIB.REGISTRO_DOCUMENTO REG
                                      WHERE REG.CODINSC =  INSCRICAO.CODINSC
                                        AND REG.CODCONC = INSCRICAO.CODCONC)) AS DOCUMENTOS_A_ENTREGAR,

  (SELECT MAX(REG.DATRECEBIMENTO)
     FROM DBVESTIB.REGISTRO_DOCUMENTO REG
     WHERE REG.CODCONC = INSCRICAO.CODCONC
       AND REG.CODINSC = INSCRICAO.CODINSC) AS ULTIMA_DATA_ENTREGA_DOCUMENTO,


   (SELECT MAX(REG.DATRECEBIMENTO)
      FROM DBVESTIB.REGISTRO_DOCUMENTO REG,
           DBVESTIB.CONCURSO_DOCUMENTO CD
     WHERE REG.CODINSC = INSCRICAO.CODINSC
       AND REG.CODCONC = INSCRICAO.CODCONC
       AND CD.CODCONC = REG.CODCONC
       AND CD.COD_TPO_DOCUMENTO = REG.COD_TPO_DOCUMENTO
       AND CD.IND_OBRIGATORIO = 'S') ULTIMA_DATA_DOC_OBRIGATORIA,

  DECODE(REGDEF.INDDEFERIDO,'S','Sim','N','Não','Não avaliado') AS DEFERIDO,
  
  REGDEF.DATDEFERIMENTO AS DATA_DEFERIMENTO,
  
  (SELECT MIN(REG.DATDEFERIMENTO)
           FROM DBVESTIB.REGISTRO_DEFERIMENTO_LOG REG
          WHERE REG.CODCONC = INSCRICAO.CODCONC
            AND REG.CODINSC = INSCRICAO.CODINSC
            AND REG.IDT_OPERACAO_LOG = 'I')DATA_1_DEFERIMENTO,

  
  DBVESTIB.F_CAMINHO_ARQUIVO_DEFERIMENTO(INSCRICAO.CODINSC,INSCRICAO.CODCONC,'S') AS ARQUIVO_DEFERIMENTO,
  REGDEF.OBSDEFERIMENTO AS OBSERVACAO_DEFERIMENTO,
  REGDEF.DSCDISCIPLINA AS DISCIPLINAS_DISPENSADAS,
  REPLACE(REGDEF.DSCMOTIVO,';', ' ') AS MOTIVO_INDEFERIMENTO,
  INSCRICAO.EMAILCAN||DECODE(INSCRICAO.EMAIL_ALTERNATIVO,NULL,NULL,'<br>'||EMAIL_ALTERNATIVO) as EMAILS,
  INSCRICAO.EMAILCAN as EMAIL,
  INSCRICAO.EMAIL_ALTERNATIVO as EMAILALTERNATIVO,
  INSCRICAO.TELCAN||DECODE(INSCRICAO.CELCAN,NULL,NULL,'<BR>'||INSCRICAO.CELCAN) TELEFONES,
  INSCRICAO.TELCAN,
  INSCRICAO.CELCAN,
  INSCRICAO.TELCOMERCIAL,
  REPLACE(INSCRICAO.ENDCAN,';',' ') ENDERECO,
  INSCRICAO.NUMERO NUMERO,
  REPLACE(INSCRICAO.COMPLEMENTO, ';', ' ') COMPLEMENTO,
  REPLACE(INSCRICAO.BAICAN, ';',' ') BAIRRO,
  INSCRICAO.CEPCAN CEP,
  CID.NOM_CIDADE AS CIDADE,
  EST.NOM_ESTADO AS ESTADO,
  INSCRICAO.CODCONC CODCONC,
  REGDEF.DATCADASTROALUNO AS DATA_CADASTRO_ALUNO,

  REGDEF.DATGERACAOBOLETA AS DATA_GERACAO_BOLETA,

  /*(SELECT REGDEF.DATGERACAOBOLETA
     FROM DBVESTIB.REGISTRO_DEFERIMENTO REGDEF,
          DBSIAF.TITULO_RECEBER TIT,
          DBSIAF.MAPEAMENTO_INSCRICAO MIS,
          DBSIAF.MAPEAMENTO_TITULO MTI
    WHERE MIS.CODCONC = INSCRICAO.CODINSC
    AND MIS.CODINSC = INSCRICAO.CODCONC
    AND MIS.CODINSC = REGDEF.CODINSC
    AND MIS.CODCONC = REGDEF.CODCONC
    AND MIS.COD_MAPEAMENTO = MTI.COD_MAPEAMENTO
    AND MTI.COD_TITULO_RECEBER = TIT.COD_TITULO_RECEBER
    AND TIT.COD_SITUACAO_TITULO = 1) AS DATA_DISP_BOLETA,*/

  REGDEF.DATLIQUIDACAOBOLETA AS DATA_LIQUIDACAO_BOLETA,
  OPC.INDPROUNI,
  DECODE(OPC.INDPROUNI, 'S', 'Possui PROUNI', 'N', 'Não Possui PROUNI', 'Não Informado') DSCPROUNI,
  INSCRICAO.INDANALISEDISPENSA,
  DECODE(INSCRICAO.INDANALISEDISPENSA, 'S', 'Desejo analise de disciplinas', 'N', 'Não desejo analise de disciplina', 'Não Informado') DSCANALISEDISCIPLINAS,
  OPC.INDFIES,
  DECODE(OPC.INDFIES, 'S', 'Possui FIES', 'N', 'Não Possui FIES', 'Não Informado') DSCFIES,  
  PRE.ORIGEMACESSO,
 (SELECT TRUNC(INSCRICAO.DATPGTO)-TRUNC(INSCRICAO.DATINSCAN)FROM DUAL) PAGAMENTO_INSCRICAO,
 
 (SELECT TRUNC((SELECT MAX(REG.DATRECEBIMENTO)
      FROM DBVESTIB.REGISTRO_DOCUMENTO REG,
           DBVESTIB.CONCURSO_DOCUMENTO CD
     WHERE REG.CODINSC = INSCRICAO.CODINSC
       AND REG.CODCONC = INSCRICAO.CODCONC
       AND CD.CODCONC = REG.CODCONC
       AND CD.COD_TPO_DOCUMENTO = REG.COD_TPO_DOCUMENTO
       AND CD.IND_OBRIGATORIO = 'S'))-TRUNC(INSCRICAO.DATPGTO)FROM DUAL) RECEBIMENTO_PAGAMENTO,
       
   (SELECT TRUNC((SELECT MIN(REG.DATDEFERIMENTO)
                   FROM DBVESTIB.REGISTRO_DEFERIMENTO_LOG REG
                  WHERE REG.CODCONC = INSCRICAO.CODCONC
                    AND REG.CODINSC = INSCRICAO.CODINSC
                    AND REG.IDT_OPERACAO_LOG = 'I'))
          - TRUNC((SELECT MAX(REG.DATRECEBIMENTO)
                     FROM DBVESTIB.REGISTRO_DOCUMENTO REG,
                          DBVESTIB.CONCURSO_DOCUMENTO CD
                    WHERE REG.CODINSC = INSCRICAO.CODINSC
                      AND REG.CODCONC = INSCRICAO.CODCONC
                      AND CD.CODCONC = REG.CODCONC
                      AND CD.COD_TPO_DOCUMENTO = REG.COD_TPO_DOCUMENTO
                      AND CD.IND_OBRIGATORIO = 'S'))FROM DUAL)DEFERIMENTO_ULT_DOC_OBR,
    (SELECT 
        CASE 
           WHEN REGDEF.DATDEFERIMENTO > TRUNC((SELECT MAX (TR.DAT_GERACAO)
           FROM DBSIAF.ALUNO AL,
                DBSIAF.TITULO_RECEBER TR,
                DBSIAF.ASS_CONTRATO ASS,
                DBSIAF.TIPO_CONTRATO TCO ,
                DBVESTIB.CURSO_CAMPUS CCA,
                DBVESTIB.RCANDCURTUROPC RCA, 
                DBSIAF.SITUACAO_TITULO SIT
          WHERE AL.COD_ALUNO = TR.COD_ALUNO
            AND ASS.COD_ASS_CONTRATO = TR.COD_ASS_CONTRATO
            AND ASS.COD_TPO_CONTRATO = TCO.COD_TPO_CONTRATO
            AND AL.CODCONC = INSCRICAO.CODCONC            
            AND AL.CODCAN = INSCRICAO.CODINSC
            AND TR.NUM_PARCELA = 1            
            AND CCA.CODCONC = INSCRICAO.CODCONC
            AND TCO.COD_PERIODO_LETIVO = CCA.COD_PERIODO_LETIVO
            AND CCA.COD_CURSO_SIAF = AL.COD_CURSO
            AND RCA.CODCUR = CCA.CODCUR
            AND RCA.CODCONC = AL.CODCONC
            AND RCA.CODCAM = CCA.CODCAM 
            AND RCA.CODCAN = AL.CODCAN
            AND SIT.COD_SITUACAO_TITULO = 1
            AND TR.COD_SITUACAO_TITULO = SIT.COD_SITUACAO_TITULO
            )) THEN REGDEF.DATDEFERIMENTO
         ELSE REGDEF.DATGERACAOBOLETA
           END FROM DUAL) DATA_DISPONIBILIZACAO,
    
    (SELECT TRUNC ((SELECT 
        CASE 
           WHEN REGDEF.DATDEFERIMENTO > TRUNC((SELECT MAX (TR.DAT_GERACAO)
           FROM DBSIAF.ALUNO AL,
                DBSIAF.TITULO_RECEBER TR,
                DBSIAF.ASS_CONTRATO ASS,
                DBSIAF.TIPO_CONTRATO TCO ,
                DBVESTIB.CURSO_CAMPUS CCA,
                DBVESTIB.RCANDCURTUROPC RCA, 
                DBSIAF.SITUACAO_TITULO SIT
          WHERE AL.COD_ALUNO = TR.COD_ALUNO
            AND ASS.COD_ASS_CONTRATO = TR.COD_ASS_CONTRATO
            AND ASS.COD_TPO_CONTRATO = TCO.COD_TPO_CONTRATO
            AND AL.CODCONC = INSCRICAO.CODCONC            
            AND AL.CODCAN = INSCRICAO.CODINSC
            AND TR.NUM_PARCELA = 1            
            AND CCA.CODCONC = INSCRICAO.CODCONC
            AND TCO.COD_PERIODO_LETIVO = CCA.COD_PERIODO_LETIVO
            AND CCA.COD_CURSO_SIAF = AL.COD_CURSO
            AND RCA.CODCUR = CCA.CODCUR
            AND RCA.CODCONC = AL.CODCONC
            AND RCA.CODCAM = CCA.CODCAM 
            AND RCA.CODCAN = AL.CODCAN
            AND SIT.COD_SITUACAO_TITULO = 1
            AND TR.COD_SITUACAO_TITULO = SIT.COD_SITUACAO_TITULO
            )) THEN REGDEF.DATDEFERIMENTO
         ELSE REGDEF.DATGERACAOBOLETA
           END FROM DUAL))       
         - TRUNC (REGDEF.DATDEFERIMENTO) FROM DUAL) DIPONIBILIZA_DEFERIMENTO,
       
       (SELECT TRUNC((SELECT 
        CASE 
           WHEN REGDEF.DATDEFERIMENTO > TRUNC((SELECT MAX (TR.DAT_GERACAO)
           FROM DBSIAF.ALUNO AL,
                DBSIAF.TITULO_RECEBER TR,
                DBSIAF.ASS_CONTRATO ASS,
                DBSIAF.TIPO_CONTRATO TCO ,
                DBVESTIB.CURSO_CAMPUS CCA,
                DBVESTIB.RCANDCURTUROPC RCA, 
                DBSIAF.SITUACAO_TITULO SIT
          WHERE AL.COD_ALUNO = TR.COD_ALUNO
            AND ASS.COD_ASS_CONTRATO = TR.COD_ASS_CONTRATO
            AND ASS.COD_TPO_CONTRATO = TCO.COD_TPO_CONTRATO
            AND AL.CODCONC = INSCRICAO.CODCONC            
            AND AL.CODCAN = INSCRICAO.CODINSC
            AND TR.NUM_PARCELA = 1            
            AND CCA.CODCONC = INSCRICAO.CODCONC
            AND TCO.COD_PERIODO_LETIVO = CCA.COD_PERIODO_LETIVO
            AND CCA.COD_CURSO_SIAF = AL.COD_CURSO
            AND RCA.CODCUR = CCA.CODCUR
            AND RCA.CODCONC = AL.CODCONC
            AND RCA.CODCAM = CCA.CODCAM 
            AND RCA.CODCAN = AL.CODCAN
            AND SIT.COD_SITUACAO_TITULO = 1
            AND TR.COD_SITUACAO_TITULO = SIT.COD_SITUACAO_TITULO
            )) THEN REGDEF.DATDEFERIMENTO
         ELSE REGDEF.DATGERACAOBOLETA
           END FROM DUAL))
          - TRUNC ((SELECT MAX(REG.DATRECEBIMENTO)
      FROM DBVESTIB.REGISTRO_DOCUMENTO REG,
           DBVESTIB.CONCURSO_DOCUMENTO CD
     WHERE REG.CODINSC = INSCRICAO.CODINSC
       AND REG.CODCONC = INSCRICAO.CODCONC
       AND CD.CODCONC = REG.CODCONC
       AND CD.COD_TPO_DOCUMENTO = REG.COD_TPO_DOCUMENTO
       AND CD.IND_OBRIGATORIO = 'S'))FROM DUAL) DISPONIVEL_DOCUMENTO,   
   
    (SELECT TRUNC (REGDEF.DATLIQUIDACAOBOLETA )
         -  TRUNC ((SELECT 
        CASE 
           WHEN REGDEF.DATDEFERIMENTO > TRUNC((SELECT MAX (TR.DAT_GERACAO)
           FROM DBSIAF.ALUNO AL,
                DBSIAF.TITULO_RECEBER TR,
                DBSIAF.ASS_CONTRATO ASS,
                DBSIAF.TIPO_CONTRATO TCO ,
                DBVESTIB.CURSO_CAMPUS CCA,
                DBVESTIB.RCANDCURTUROPC RCA, 
                DBSIAF.SITUACAO_TITULO SIT
          WHERE AL.COD_ALUNO = TR.COD_ALUNO
            AND ASS.COD_ASS_CONTRATO = TR.COD_ASS_CONTRATO
            AND ASS.COD_TPO_CONTRATO = TCO.COD_TPO_CONTRATO
            AND AL.CODCONC = INSCRICAO.CODCONC            
            AND AL.CODCAN = INSCRICAO.CODINSC
            AND TR.NUM_PARCELA = 1            
            AND CCA.CODCONC = INSCRICAO.CODCONC
            AND TCO.COD_PERIODO_LETIVO = CCA.COD_PERIODO_LETIVO
            AND CCA.COD_CURSO_SIAF = AL.COD_CURSO
            AND RCA.CODCUR = CCA.CODCUR
            AND RCA.CODCONC = AL.CODCONC
            AND RCA.CODCAM = CCA.CODCAM 
            AND RCA.CODCAN = AL.CODCAN
            AND SIT.COD_SITUACAO_TITULO = 1
            AND TR.COD_SITUACAO_TITULO = SIT.COD_SITUACAO_TITULO
            )) THEN REGDEF.DATDEFERIMENTO
         ELSE REGDEF.DATGERACAOBOLETA
           END FROM DUAL))FROM DUAL)LIQUIDACAO_DISPONIVEL   
                            
FROM   
  DBVESTIB.INSCRICAO INSCRICAO,
  DBVESTIB.PREINSCRICAO PRE,
  DBVESTIB.FORMA_PROVA FORMA,
  DBVESTIB.REGISTRO_DEFERIMENTO REGDEF,
  DBSIAF.TIPO_ENTRADA TIPENT,
  DBSIAF.CIDADE CID,
  DBSIAF.ESTADO EST,
  DBVESTIB.CONCURSO CON,
  DBVESTIB.OPCAOCANDIDATO OPC,
  (SELECT
      CUR.NOMCUR,
      TUR.DSCTUR,
      CAM.NOMCAM,
      INC.CODCONC,
      INC.CODINSC
   FROM
      DBVESTIB.INSCRICAO INC,
      DBVESTIB.OPCAOCANDIDATO OPC,
      DBVESTIB.CURSO CUR,
      DBVESTIB.CAMPUS CAM,
      DBVESTIB.TURNO TUR
   WHERE
      OPC.CODCONC = INC.CODCONC AND
      OPC.CODINSC = INC.CODINSC AND
      OPC.CODCUR = CUR.CODCUR AND
      OPC.CODCONC = CUR.CODCONC AND
      OPC.CODTUR = TUR.CODTUR AND
      CAM.CODCAM = OPC.CODCAM AND
      OPC.NROOPC = 1
  ) OPCAO1,
  (SELECT
      CUR.NOMCUR,
      TUR.DSCTUR,
      CAM.NOMCAM,
      INC.CODCONC,
      INC.CODINSC
   FROM
      DBVESTIB.INSCRICAO INC,
      DBVESTIB.OPCAOCANDIDATO OPC,
      DBVESTIB.CURSO CUR,
      DBVESTIB.CAMPUS CAM,
      DBVESTIB.TURNO TUR
   WHERE
      OPC.CODCONC = INC.CODCONC AND
      OPC.CODINSC = INC.CODINSC AND
      OPC.CODCUR = CUR.CODCUR AND
      OPC.CODCONC = CUR.CODCONC AND
      OPC.CODTUR = TUR.CODTUR AND
      CAM.CODCAM = OPC.CODCAM AND
      OPC.NROOPC = 2
  ) OPCAO2,
  (SELECT
      CUR.NOMCUR,
      TUR.DSCTUR,
      CAM.NOMCAM,
      INC.CODCONC,
      INC.CODINSC
   FROM
      DBVESTIB.INSCRICAO INC,
      DBVESTIB.OPCAOCANDIDATO OPC,
      DBVESTIB.CURSO CUR,
      DBVESTIB.CAMPUS CAM,
      DBVESTIB.TURNO TUR
   WHERE
      OPC.CODCONC = INC.CODCONC AND
      OPC.CODINSC = INC.CODINSC AND
      OPC.CODCUR = CUR.CODCUR AND
      OPC.CODCONC = CUR.CODCONC AND
      OPC.CODTUR = TUR.CODTUR AND
      CAM.CODCAM = OPC.CODCAM AND
      OPC.NROOPC = 3
  ) OPCAO3

WHERE
  PRE.CODINSC (+) = INSCRICAO.CODINSC AND
  PRE.CODCONC (+) = INSCRICAO.CODCONC AND
  FORMA.CODFORMAPROVA (+)= INSCRICAO.CODFORMAPROVA AND
  REGDEF.CODINSC (+)= INSCRICAO.CODINSC AND
  REGDEF.CODCONC (+)= INSCRICAO.CODCONC AND
  TIPENT.COD_TPO_ENTRADA (+)= INSCRICAO.FORMA_INGRESSO AND
  CID.COD_CIDADE (+)= INSCRICAO.CODCIDADE AND
  EST.COD_ESTADO (+)= CID.COD_ESTADO AND
  CON.CODCONC = INSCRICAO.CODCONC AND
  OPC.CODCONC = INSCRICAO.CODCONC AND
  OPC.CODINSC = INSCRICAO.CODINSC AND
  OPC.NROOPC = '1' AND
  OPCAO1.CODCONC (+) = INSCRICAO.CODCONC AND
  OPCAO1.CODINSC (+) = INSCRICAO.CODINSC AND
  OPCAO2.CODCONC (+) = INSCRICAO.CODCONC AND
  OPCAO2.CODINSC (+) = INSCRICAO.CODINSC AND
  OPCAO3.CODCONC (+) = INSCRICAO.CODCONC AND
  OPCAO3.CODINSC (+) = INSCRICAO.CODINSC;
