CREATE OR REPLACE PROCEDURE dbvestib.SP_ATUALIZA_OPCAO(P_CODCONC  DBVESTIB.RCANDCURTUROPC.CODCONC%TYPE,
													   P_CODCAN   DBVESTIB.RCANDCURTUROPC.CODCAN%TYPE,
													   P_NROOPC   DBVESTIB.RCANDCURTUROPC.NROOPC%TYPE,
													   N_NROOPC   DBVESTIB.RCANDCURTUROPC.NROOPC%TYPE,
													   P_IDT_ACAO CHAR) IS

	CURSOR C_OPCAO IS
		SELECT OPC.*
		  FROM DBVESTIB.RCANDCURTUROPC OPC,
			   DBVESTIB.CONCURSO       CON
		 WHERE OPC.CODCONC = P_CODCONC
			   AND OPC.CODCAN = P_CODCAN
			   AND OPC.NROOPC = P_NROOPC
			   AND CON.CODCONC = OPC.CODCONC
			   AND CON.COD_TPO_CONCURSO <> 67; -- concurso outras avaliações não temos inscrições	NVALIDA NUMBER;

BEGIN

	IF P_IDT_ACAO = 'D' THEN
	
		DELETE FROM DBVESTIB.OPCAOCANDIDATO
		 WHERE CODCONC = P_CODCONC
			   AND CODINSC = P_CODCAN
			   AND NROOPC = N_NROOPC;
	
	ELSE
		FOR R_OPCAO IN C_OPCAO LOOP
			IF P_IDT_ACAO = 'I' THEN
			
				INSERT INTO DBVESTIB.OPCAOCANDIDATO
					(CODCONC,
					 CODINSC,
					 NROOPC,
					 CODCUR,
					 CODTUR,
					 OPCLIN,
					 CODCAM,
					 CODINSTITUICAO,
					 INDPRINCIPAL,
					 INDFORMACAOAMPLIADA,
					 INDPROUNI,
					 INDFIES,
                     IND_DESEJA_PROUNI,
					 IND_DESEJA_FIES)
				VALUES
					(R_OPCAO.CODCONC,
					 R_OPCAO.CODCAN,
					 R_OPCAO.NROOPC,
					 R_OPCAO.CODCUR,
					 R_OPCAO.CODTUR,
					 R_OPCAO.OPCLIN,
					 R_OPCAO.CODCAM,
					 R_OPCAO.CODINSTITUICAO,
					 R_OPCAO.INDPRINCIPAL,
					 R_OPCAO.INDFORMACAOAMPLIADA,
					 R_OPCAO.INDPROUNI,
					 R_OPCAO.INDFIES,
                     R_OPCAO.IND_DESEJA_PROUNI,
					 R_OPCAO.IND_DESEJA_FIES);
			ELSIF P_IDT_ACAO = 'U' THEN
			   
					UPDATE DBVESTIB.OPCAOCANDIDATO
					   SET CODCUR              = R_OPCAO.CODCUR,
						   CODTUR              = R_OPCAO.CODTUR,
						   OPCLIN              = R_OPCAO.OPCLIN,
						   CODCAM              = R_OPCAO.CODCAM,
						   CODINSTITUICAO      = R_OPCAO.CODINSTITUICAO,
						   INDPRINCIPAL        = R_OPCAO.INDPRINCIPAL,
						   INDFORMACAOAMPLIADA = R_OPCAO.INDFORMACAOAMPLIADA,
						   INDPROUNI           = R_OPCAO.INDPROUNI,
                           INDFIES             = R_OPCAO.INDFIES,
						   NROOPC              = P_NROOPC,
                           IND_DESEJA_PROUNI   = R_OPCAO.IND_DESEJA_PROUNI,
                           IND_DESEJA_FIES     = R_OPCAO.IND_DESEJA_FIES
					 WHERE CODCONC = R_OPCAO.CODCONC
						   AND CODINSC = R_OPCAO.CODCAN
						   AND NROOPC = N_NROOPC;
			END IF;
		END LOOP;
	END IF;
EXCEPTION
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-20500,
								SQLERRM);
	
END;
/
