CREATE OR REPLACE PROCEDURE dbvestib.SP_CONFIRMA_INSC_INTERNET(P_CODCONC IN CONCURSO.CODCONC%TYPE,
                                                               P_CODCAN  IN CANDIDATO.CODCAN%TYPE)

 IS
  VCODCAN               INSCRICAO.CODINSC%TYPE;
  VNOMCAN               CANDIDATO.NOMCAN%TYPE;
  VSEXCAN               CANDIDATO.SEXCAN%TYPE;
  VCODCUR               RCANDCURTUROPC.CODCUR%TYPE;
  VCODTUR               RCANDCURTUROPC.CODTUR%TYPE;
  VOPCLIN               RCANDCURTUROPC.OPCLIN%TYPE;
  VNROOPC               RCANDCURTUROPC.NROOPC%TYPE;
  VCANHOTO              CANDIDATO.CANHOTO%TYPE;
  VDEFCAN               TIPO_DEFICIENCIA.CODTPODEF%TYPE;
  VEMAILCAN             CANDIDATO.EMAIL%TYPE;
  VTIPDOC               CANDIDATO.ESTCAN%TYPE;
  VIDECAN               CANDIDATO.IDECAN%TYPE;
  VESTDOC               DBSIAF.ESTADO.SGL_ESTADO%TYPE;
  VSTRSOCECO            CANDIDATO.STR_SOCECO%TYPE;
  VDATNASCAN            CANDIDATO.DATNASCAN%TYPE;
  VDATINSCAN            CANDIDATO.DATINSCAN%TYPE;
  VORGEXPDOC            CANDIDATO.IDECAN%TYPE;
  VENDCAN               CANDIDATO.ENDCAN%TYPE;
  VBAICAN               CANDIDATO.BAICAN%TYPE;
  VCIDCAN               DBSIAF.CIDADE.NOM_CIDADE%TYPE;
  VCEPCAN               CANDIDATO.CEPCAN%TYPE;
  VTELCAN               CANDIDATO.TELCAN%TYPE;
  VESTCAN               DBSIAF.ESTADO.SGL_ESTADO%TYPE;
  VNOMIDECAN            TIPODOCUMENTO.DSCTIPDOC%TYPE;
  VIND_TREINANTE        CANDIDATO.IND_TREINANTE%TYPE;
  VDATPGTO              INSCRICAO.DATPGTO%TYPE;
  VCODCARTA             INSCRICAO.CODCARTA%TYPE;
  VCELCAN               INSCRICAO.CELCAN%TYPE;
  VCPFCAN               INSCRICAO.CPFCAN%TYPE;
  X                     NUMBER;
  VCODLOCPAG            string(3);
  VFORMAINGRESSO        INSCRICAO.FORMA_INGRESSO%TYPE;
  VESCOLAORIGEM         INSCRICAO.ESCOLA_ORIGEM%TYPE;
  VMATRICULA            INSCRICAO.MATRICULA%TYPE;
  VTIPOINSCRICAO        INSCRICAO.TIPO_INSCRICAO%TYPE;
  VNUMEND               INSCRICAO.NUMERO%TYPE;
  VCOMPLEMENTO          INSCRICAO.COMPLEMENTO%TYPE;
  NVALPAGO              INSCRICAO.VALPAGO%TYPE;
  NCODLOCINSCRICAO      INSCRICAO.COD_LOC_INSCRICAO%TYPE;
  VCODFISINSCRICAO      DBVESTIB.INSCRICAO.COD_FIS_INSCRICAO%TYPE;
  VPAICAN               DBVESTIB.INSCRICAO.PAICAN%TYPE;
  VMAECAN               DBVESTIB.INSCRICAO.MAECAN%TYPE;
  VCODINSTITEXTERNA     DBVESTIB.INSCRICAO.COD_INSTIT_EXTERNA%TYPE;
  NCODTPOCONCURSO       DBVESTIB.CONCURSO.COD_TPO_CONCURSO%TYPE;
  NINDDISPTAUTOMATICA   DBVESTIB.PARAMETROS_CONCURSO.INDDISPTAUTOMATICA%TYPE;
  NCODFORMAPROVA        DBVESTIB.INSCRICAO.CODFORMAPROVA%TYPE;
  VANOENEM              DBVESTIB.INSCRICAO.ANOENEM%TYPE;
  VNUMINSCENEM          DBVESTIB.INSCRICAO.NUMINSCENEM%TYPE;
  DDATPROVAAGENDADA     DBVESTIB.INSCRICAO.DATPROVAAGENDADA%TYPE;
  VCODCAM               RCANDCURTUROPC.CODCAM%TYPE;
  NCODINSTITUICAO       RCANDCURTUROPC.CODINSTITUICAO%TYPE;
  V_EMAILALTERNATIVO    DBVESTIB.CANDIDATO.EMAIL_ALTERNATIVO%TYPE;
  V_INDFORMACAOAMPLIADA DBVESTIB.OPCAOCANDIDATO.INDFORMACAOAMPLIADA%TYPE;
  V_INDPROUNI           DBVESTIB.OPCAOCANDIDATO.INDPROUNI%TYPE;
  V_INDFIES             DBVESTIB.OPCAOCANDIDATO.INDFIES%TYPE;
  V_NOMCURSOGRADUACAO   DBVESTIB.INSCRICAO.NOMCURSOGRADUACAO%TYPE;
  N_ANOCONCLUSAOEM      DBVESTIB.INSCRICAO.ANOCONCLUSAOEM%TYPE;
  N_COD_ESCOLA_ORIGEM   DBVESTIB.INSCRICAO.COD_ESCOLA_ORIGEM%TYPE;
  N_COD_CURSINHO        DBVESTIB.INSCRICAO.COD_CURSINHO%TYPE;
  V_NOMCURSINHOOUTRO    DBVESTIB.INSCRICAO.NOMCURSINHOOUTRO%TYPE;
  N_COD_EMP_CONVENIADAS DBVESTIB.INSCRICAO.COD_EMP_CONVENIADAS%TYPE;
  NCODESTADOCIVIL       DBVESTIB.CANDIDATO.CODESTADOCIVIL%TYPE;
  NCODPAISNC            DBVESTIB.CANDIDATO.CODPAISNC%TYPE;
  NCODCIDADENAT         DBVESTIB.CANDIDATO.CODCIDADENAT%TYPE;
  NCODINSTITUICAOPSVS   DBVESTIB.INSCRICAO.COD_INSTITUICAO_PSVS%TYPE;
  NCODMAPEAMENTO        DBSIAF.MAPEAMENTO.COD_MAPEAMENTO%TYPE;
  NFORMAPGTO            DBVESTIB.INSCRICAO.FORMAPGTO%TYPE;
  NCODTITULORECEBER     DBSIAF.MAPEAMENTO_TITULO.COD_TITULO_RECEBER%TYPE;
  NCODSTATITULO         DBSIAF.TITULO_RECEBER.COD_STA_TITULO%TYPE;
  NCOD_COR_RACA         DBVESTIB.INSCRICAO.COD_COR_RACA%TYPE;
  V_IND_DESEJA_PROUNI   DBVESTIB.OPCAOCANDIDATO.IND_DESEJA_PROUNI%TYPE;
  V_IND_DESEJA_FIES     DBVESTIB.OPCAOCANDIDATO.IND_DESEJA_FIES%TYPE;
  
  CURSOR C_INSCRICAO IS
    SELECT INSC.CODCONC,
           INSC.CODINSC,
           INSC.CODTIPDOC,
           INSC.CODTPODEF,
           INSC.NOMCAN,
           INSC.SEXCAN,
           INSC.DATNASCAN,
           INSC.ENDCAN,
           INSC.BAICAN,
           INSC.CEPCAN,
           INSC.TELCAN,
           INSC.FLGCANHOTO,
           INSC.EMAILCAN,
           INSC.DATINSCAN,
           INSC.IND_TREINANTE,
           INSC.DATPGTO,
           INSC.LOGCAN,
           INSC.SENCAN,
           INSC.NRODOC,
           INSC.CODESTADO,
           INSC.CODCIDADE,
           INSC.FORMAPGTO,
           INSC.LOGREF,
           INSC.CODTRANS,
           INSC.CODAUT,
           INSC.DSCTPOTRANS,
           INSC.NUMCV,
           INSC.NUMPED,
           OPC.CODCUR,
           OPC.CODTUR,
           OPC.OPCLIN,
           TD.DSCTIPDOC,
           ESTDOC.SGL_ESTADO         ESTDOC,
           CID.NOM_CIDADE            CIDCAN,
           ES.SGL_ESTADO             ESTCAN,
           OPC.NROOPC,
           TD.ORGEXPDOC,
           INSC.CODCARTA,
           INSC.CELCAN,
           INSC.CPFCAN,
           INSC.MATRICULA,
           INSC.ESCOLA_ORIGEM,
           INSC.FORMA_INGRESSO,
           INSC.TIPO_INSCRICAO,
           INSC.NUMERO,
           INSC.COMPLEMENTO,
           INSC.VALPAGO,
           INSC.CODLOCPAG,
           INSC.COD_LOC_INSCRICAO,
           INSC.PAICAN,
           INSC.MAECAN,
           INSC.COD_FIS_INSCRICAO,
           INSC.EMAIL_ALTERNATIVO,
           INSC.COD_INSTIT_EXTERNA,
           CODFORMAPROVA,
           ANOENEM,
           NUMINSCENEM,
           DATPROVAAGENDADA,
           OPC.CODCAM,
           OPC.CODINSTITUICAO,
           INSC.CODESCOLA,
           OPC.INDFORMACAOAMPLIADA,
           OPC.INDPROUNI,
           OPC.INDFIES,
           INSC.NOMCURSOGRADUACAO,
           INSC.ANOCONCLUSAOEM,
           INSC.COD_ESCOLA_ORIGEM,
           INSC.COD_CURSINHO,
           INSC.NOMCURSINHOOUTRO,
           INSC.COD_EMP_CONVENIADAS,
           INSC.CODESTADOCIVIL,
           INSC.CODPAISNC,
           INSC.CODCIDADENAT,
           INSC.COD_INSTITUICAO_PSVS,
           INSC.COD_COR_RACA,
           OPC.IND_DESEJA_PROUNI,
           OPC.IND_DESEJA_FIES
    
      FROM INSCRICAO        INSC,
           OPCAOCANDIDATO   OPC,
           TIPODOCUMENTO    TD,
           TIPO_DEFICIENCIA TDE,
           ESTADO           ES,
           DBSIAF.ESTADO    ESTDOC,
           CIDADE           CID
    
     WHERE INSC.CODCONC = P_CODCONC
       AND INSC.CODINSC = P_CODCAN
       AND INSC.CODCONC = OPC.CODCONC
       AND INSC.CODINSC = OPC.CODINSC
       AND TD.CODTIPDOC = INSC.CODTIPDOC
       AND INSC.CODTPODEF = TDE.CODTPODEF
       AND INSC.CODCIDADE = CID.COD_CIDADE
       AND ES.COD_ESTADO = CID.COD_ESTADO
       AND INSC.CODESTADO = ESTDOC.COD_ESTADO(+)
       AND INSC.CODINSC = OPC.CODINSC;

  CURSOR C_INSC_FIAT IS
    SELECT IFI.CODEMP,
           DBVESTIB.F_FORMATA_CAMPO(IFI.NOMEESC) NOMEESC,
           DBVESTIB.F_FORMATA_CAMPO(IFI.ENDESC) ENDESC,
           DBVESTIB.F_FORMATA_CAMPO(IFI.NUM_ESCOLA) NUM_ESCOLA,
           DBVESTIB.F_FORMATA_CAMPO(IFI.COMPLEMENTO_ESCOLA) COMPLEMENTO_ESCOLA,
           DBVESTIB.F_FORMATA_CAMPO(IFI.BAIESC) BAIESC,
           DBVESTIB.F_FORMATA_CAMPO(IFI.CEPESC) CEPESC,
           IFI.COD_CIDADE_ESC,
           DBVESTIB.F_FORMATA_CAMPO(IFI.TELESC) TELESC,
           DBVESTIB.F_FORMATA_CAMPO(IFI.REG_EMPREGADO) REG_EMPREGADO,
           DBVESTIB.F_FORMATA_CAMPO(IFI.NOM_EMPREGADO) NOM_EMPREGADO,
           DBVESTIB.F_FORMATA_CAMPO(IFI.RAMAL) RAMAL,
           DBVESTIB.F_FORMATA_CAMPO(IFI.DSCCRESP) DSCCRESP,
           DBVESTIB.F_FORMATA_CAMPO(IFI.DSCEQUIPE) DSCEQUIPE,
           IFI.INDLERESCREVER,
           IFI.INDUSATRANS,
           IFI.COD_CAMPUS_PROX_RESIDENCIA,
           DBVESTIB.F_FORMATA_CAMPO(CID.NOM_CIDADE) NOM_CIDADE
      FROM DBVESTIB.INSCRICAO_FIAT IFI, DBSIAF.CIDADE CID
     WHERE IFI.CODCONC = P_CODCONC
       AND IFI.CODINSC = P_CODCAN
       AND CID.COD_CIDADE(+) = IFI.COD_CIDADE_ESC;

  NCODESCOLA DBVESTIB.CANDIDATO.CODESCOLA%TYPE;
BEGIN

  -- buscando tipo de concurso
  SELECT CON.COD_TPO_CONCURSO, PAR.INDDISPTAUTOMATICA
    INTO NCODTPOCONCURSO, NINDDISPTAUTOMATICA
    FROM DBVESTIB.CONCURSO CON, DBVESTIB.PARAMETROS_CONCURSO PAR
   WHERE CON.CODCONC = P_CODCONC
     AND CON.CODCONC = PAR.CODCONC;

  FOR R_INSCRICAO IN C_INSCRICAO LOOP
    BEGIN
      IF (NCODTPOCONCURSO = 8) THEN
        VCODCAN               := R_INSCRICAO.CODINSC;
        VNOMCAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.NOMCAN);
        VSEXCAN               := R_INSCRICAO.SEXCAN;
        VCODCUR               := R_INSCRICAO.CODCUR;
        VCODTUR               := R_INSCRICAO.CODTUR;
        VOPCLIN               := R_INSCRICAO.OPCLIN;
        VNROOPC               := R_INSCRICAO.NROOPC;
        VDEFCAN               := R_INSCRICAO.CODTPODEF;
        VEMAILCAN             := R_INSCRICAO.EMAILCAN;
        VCANHOTO              := R_INSCRICAO.FLGCANHOTO;
        VTIPDOC               := R_INSCRICAO.CODTIPDOC;
        VIDECAN               := R_INSCRICAO.NRODOC;
        VORGEXPDOC            := R_INSCRICAO.ORGEXPDOC;
        VESTDOC               := R_INSCRICAO.ESTDOC;
        VSTRSOCECO            := '';
        VDATNASCAN            := R_INSCRICAO.DATNASCAN;
        VDATINSCAN            := R_INSCRICAO.DATINSCAN;
        VENDCAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.ENDCAN);
        VBAICAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.BAICAN);
        VCIDCAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.CIDCAN);
        VIND_TREINANTE        := R_INSCRICAO.IND_TREINANTE;
        VCELCAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.CELCAN);
        VCPFCAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.CPFCAN);
        VMATRICULA            := R_INSCRICAO.MATRICULA;
        VFORMAINGRESSO        := R_INSCRICAO.FORMA_INGRESSO;
        VESCOLAORIGEM         := R_INSCRICAO.ESCOLA_ORIGEM;
        VTIPOINSCRICAO        := R_INSCRICAO.TIPO_INSCRICAO;
        VCODLOCPAG            := R_INSCRICAO.CODLOCPAG;
        VNUMEND               := R_INSCRICAO.NUMERO;
        VCOMPLEMENTO          := R_INSCRICAO.COMPLEMENTO;
        NVALPAGO              := R_INSCRICAO.VALPAGO;
        NCODLOCINSCRICAO      := R_INSCRICAO.COD_LOC_INSCRICAO;
        VCODFISINSCRICAO      := R_INSCRICAO.COD_FIS_INSCRICAO;
        VPAICAN               := R_INSCRICAO.PAICAN;
        VMAECAN               := R_INSCRICAO.MAECAN;
        VCODINSTITEXTERNA     := R_INSCRICAO.COD_INSTIT_EXTERNA;
        VCEPCAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.CEPCAN);
        VTELCAN               := DBVESTIB.F_FORMATA_CAMPO(R_INSCRICAO.TELCAN);
        VESTCAN               := R_INSCRICAO.ESTCAN;
        VNOMIDECAN            := R_INSCRICAO.DSCTIPDOC;
        VDATPGTO              := R_INSCRICAO.DATPGTO;
        VCODCARTA             := R_INSCRICAO.CODCARTA;
        NCODFORMAPROVA        := R_INSCRICAO.CODFORMAPROVA;
        VANOENEM              := R_INSCRICAO.ANOENEM;
        VNUMINSCENEM          := R_INSCRICAO.NUMINSCENEM;
        DDATPROVAAGENDADA     := R_INSCRICAO.DATPROVAAGENDADA;
        VCODCAM               := R_INSCRICAO.CODCAM;
        NCODINSTITUICAO       := R_INSCRICAO.CODINSTITUICAO;
        NCODESCOLA            := R_INSCRICAO.CODESCOLA;
        V_INDFORMACAOAMPLIADA := R_INSCRICAO.INDFORMACAOAMPLIADA;
        V_INDPROUNI           := R_INSCRICAO.INDPROUNI;
        V_INDFIES             := R_INSCRICAO.INDFIES;
        NCODINSTITUICAOPSVS   := R_INSCRICAO.COD_INSTITUICAO_PSVS;
        NFORMAPGTO            := R_INSCRICAO.FORMAPGTO;
        NCOD_COR_RACA         := R_INSCRICAO.COD_COR_RACA;
        V_IND_DESEJA_PROUNI   := R_INSCRICAO.IND_DESEJA_PROUNI;
        V_IND_DESEJA_FIES     := R_INSCRICAO.IND_DESEJA_FIES;
        IF VCODLOCPAG IS NULL THEN
          VCODLOCPAG := '002';
        END IF;
      
      ELSE
      
        VCODCAN             := R_INSCRICAO.CODINSC;
        VNOMCAN             := R_INSCRICAO.NOMCAN;
        VSEXCAN             := R_INSCRICAO.SEXCAN;
        VCODCUR             := R_INSCRICAO.CODCUR;
        VCODTUR             := R_INSCRICAO.CODTUR;
        VOPCLIN             := R_INSCRICAO.OPCLIN;
        VNROOPC             := R_INSCRICAO.NROOPC;
        VDEFCAN             := R_INSCRICAO.CODTPODEF;
        VEMAILCAN           := R_INSCRICAO.EMAILCAN;
        V_EMAILALTERNATIVO  := R_INSCRICAO.EMAIL_ALTERNATIVO;
        VCANHOTO            := R_INSCRICAO.FLGCANHOTO;
        VTIPDOC             := R_INSCRICAO.CODTIPDOC;
        VIDECAN             := R_INSCRICAO.NRODOC;
        VORGEXPDOC          := R_INSCRICAO.ORGEXPDOC;
        VESTDOC             := R_INSCRICAO.ESTDOC;
        VSTRSOCECO          := '';
        VDATNASCAN          := R_INSCRICAO.DATNASCAN;
        VDATINSCAN          := R_INSCRICAO.DATINSCAN;
        VENDCAN             := R_INSCRICAO.ENDCAN;
        VBAICAN             := R_INSCRICAO.BAICAN;
        VCIDCAN             := R_INSCRICAO.CIDCAN;
        VIND_TREINANTE      := R_INSCRICAO.IND_TREINANTE;
        VCELCAN             := R_INSCRICAO.CELCAN;
        VCPFCAN             := R_INSCRICAO.CPFCAN;
        VMATRICULA          := R_INSCRICAO.MATRICULA;
        VFORMAINGRESSO      := R_INSCRICAO.FORMA_INGRESSO;
        VESCOLAORIGEM       := R_INSCRICAO.ESCOLA_ORIGEM;
        VTIPOINSCRICAO      := R_INSCRICAO.TIPO_INSCRICAO;
        VCODLOCPAG          := R_INSCRICAO.CODLOCPAG;
        VNUMEND             := R_INSCRICAO.NUMERO;
        VCOMPLEMENTO        := R_INSCRICAO.COMPLEMENTO;
        NVALPAGO            := R_INSCRICAO.VALPAGO;
        NCODLOCINSCRICAO    := R_INSCRICAO.COD_LOC_INSCRICAO;
        VCODFISINSCRICAO    := R_INSCRICAO.COD_FIS_INSCRICAO;
        VPAICAN             := R_INSCRICAO.PAICAN;
        VMAECAN             := R_INSCRICAO.MAECAN;
        VCODINSTITEXTERNA   := R_INSCRICAO.COD_INSTIT_EXTERNA;
        NCODESTADOCIVIL     := R_INSCRICAO.CODESTADOCIVIL;
        NCODPAISNC          := R_INSCRICAO.CODPAISNC;
        NCODCIDADENAT       := R_INSCRICAO.CODCIDADENAT;
        NCODINSTITUICAOPSVS := R_INSCRICAO.COD_INSTITUICAO_PSVS;
        NFORMAPGTO          := R_INSCRICAO.FORMAPGTO;
        NCOD_COR_RACA       := R_INSCRICAO.COD_COR_RACA;
      
        IF LENGTH(TRIM(R_INSCRICAO.CEPCAN)) < 9 THEN
          VCEPCAN := SUBSTR(R_INSCRICAO.CEPCAN, 1, 5) || '-' ||
                     SUBSTR(R_INSCRICAO.CEPCAN, 6, 3);
        ELSE
          VCEPCAN := R_INSCRICAO.CEPCAN;
        END IF;
      
        VTELCAN    := R_INSCRICAO.TELCAN;
        VESTCAN    := R_INSCRICAO.ESTCAN;
        VNOMIDECAN := R_INSCRICAO.DSCTIPDOC;
        VDATPGTO   := R_INSCRICAO.DATPGTO;
        VCODCARTA  := R_INSCRICAO.CODCARTA;
      
        NCODFORMAPROVA        := R_INSCRICAO.CODFORMAPROVA;
        VANOENEM              := R_INSCRICAO.ANOENEM;
        VNUMINSCENEM          := R_INSCRICAO.NUMINSCENEM;
        DDATPROVAAGENDADA     := R_INSCRICAO.DATPROVAAGENDADA;
        VCODCAM               := R_INSCRICAO.CODCAM;
        NCODINSTITUICAO       := R_INSCRICAO.CODINSTITUICAO;
        V_INDFORMACAOAMPLIADA := R_INSCRICAO.INDFORMACAOAMPLIADA;
        V_INDPROUNI           := R_INSCRICAO.INDPROUNI;
        V_INDFIES             := R_INSCRICAO.INDFIES;
        V_NOMCURSOGRADUACAO   := R_INSCRICAO.NOMCURSOGRADUACAO;
      
        N_ANOCONCLUSAOEM      := R_INSCRICAO.ANOCONCLUSAOEM;
        N_COD_ESCOLA_ORIGEM   := R_INSCRICAO.COD_ESCOLA_ORIGEM;
        N_COD_CURSINHO        := R_INSCRICAO.COD_CURSINHO;
        V_NOMCURSINHOOUTRO    := R_INSCRICAO.NOMCURSINHOOUTRO;
        N_COD_EMP_CONVENIADAS := R_INSCRICAO.COD_EMP_CONVENIADAS;
        V_IND_DESEJA_PROUNI   := R_INSCRICAO.IND_DESEJA_PROUNI;
        V_IND_DESEJA_FIES     := R_INSCRICAO.IND_DESEJA_FIES;
      
        IF VCODLOCPAG IS NULL THEN
          VCODLOCPAG := '002';
        END IF;
      END IF;
    
    END;
  
    -- Troca os dados do arquivo texto para o que existe no Banco de Dados
  
    -- Converte para o formato data
    BEGIN
      VDATNASCAN := TO_DATE(VDATNASCAN, 'DDMMRRRR');
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  
    -- Verifica se o candidato existe na base de dados
    X := 0;
    SELECT COUNT(*)
      INTO X
      FROM CANDIDATO
     WHERE CODCONC = P_CODCONC
       AND CODCAN = P_CODCAN;
  
    IF (X = 0) THEN
      -- Insere o candidato na tabela de candidatos
      INSERT INTO CANDIDATO
        (CODCONC,
         CODCAN,
         NOMCAN,
         SEXCAN,
         DATNASCAN,
         IDECAN,
         NOMIDECAN,
         EXPIDECAN,
         TELCAN,
         ENDCAN,
         BAICAN,
         CIDCAN,
         ESTCAN,
         CEPCAN,
         DATINSCAN,
         DATPAGCAN,
         CODLOCPAG,
         EMAIL,
         CANHOTO,
         DATINCCAN,
         str_soceco,
         CODTPODEF,
         IND_TREINANTE,
         CELCAN,
         CPFCAN,
         FORMA_INGRESSO,
         MATRICULA,
         ESCOLA_ORIGEM,
         NUMEND,
         COMPLEMENTO,
         VALPAGO,
         COD_LOC_INSCRICAO,
         NOM_PAI,
         NOM_MAE,
         COD_FIS_INSCRICAO,
         COD_INSTIT_EXTERNA,
         CODFORMAPROVA,
         ANOENEM,
         NUMINSCENEM,
         DATPROVAAGENDADA,
         CODESCOLA,
         EMAIL_ALTERNATIVO,
         NOMCURSOGRADUACAO,
         ANOCONCLUSAOEM,
         COD_ESCOLA_ORIGEM,
         COD_CURSINHO,
         NOMCURSINHOOUTRO,
         COD_EMP_CONVENIADAS,
         CODESTADOCIVIL,
         CODPAISNC,
         CODCIDADENAT,
         COD_INSTITUICAO_PSVS,
         COD_COR_RACA)
      VALUES
        (P_CODCONC,
         VCODCAN,
         UPPER(TRIM(VNOMCAN)),
         UPPER(VSEXCAN),
         VDATNASCAN,
         VIDECAN,
         UPPER(VNOMIDECAN),
         TRIM(VORGEXPDOC),
         VTELCAN,
         UPPER(VENDCAN),
         UPPER(VBAICAN),
         UPPER(VCIDCAN),
         UPPER(VESTCAN),
         VCEPCAN,
         VDATINSCAN,
         VDATPGTO,
         VCODLOCPAG,
         TRIM(VEMAILCAN),
         NVL(VCANHOTO, 'N'),
         SYSDATE,
         TRIM(VSTRSOCECO),
         VDEFCAN,
         VIND_TREINANTE,
         VCELCAN,
         VCPFCAN,
         VFORMAINGRESSO,
         VMATRICULA,
         VESCOLAORIGEM,
         VNUMEND,
         VCOMPLEMENTO,
         NVALPAGO,
         NCODLOCINSCRICAO,
         VPAICAN,
         VMAECAN,
         VCODFISINSCRICAO,
         VCODINSTITEXTERNA,
         NCODFORMAPROVA,
         VANOENEM,
         VNUMINSCENEM,
         DDATPROVAAGENDADA,
         NCODESCOLA,
         V_EMAILALTERNATIVO,
         V_NOMCURSOGRADUACAO,
         N_ANOCONCLUSAOEM,
         N_COD_ESCOLA_ORIGEM,
         N_COD_CURSINHO,
         V_NOMCURSINHOOUTRO,
         N_COD_EMP_CONVENIADAS,
         R_INSCRICAO.CODESTADOCIVIL,
         R_INSCRICAO.CODPAISNC,
         R_INSCRICAO.CODCIDADENAT,
         NCODINSTITUICAOPSVS,
         NCOD_COR_RACA);
    
      -- gerando codigo de barras       
      BEGIN
        DBVESTIB.SP_GERA_CODBARRAS(P_CODCONC, VCODCAN);
      EXCEPTION
        WHEN OTHERS THEN
          NULL;
      END;
    
      IF (NCODTPOCONCURSO = 8) THEN
        FOR R_INSC_FIAT IN C_INSC_FIAT LOOP
          UPDATE DBVESTIB.CANDIDATO C
             SET CODEMP               = R_INSC_FIAT.CODEMP,
                 NOMEESC              = R_INSC_FIAT.NOMEESC,
                 ENDESC               = R_INSC_FIAT.ENDESC,
                 NUM_ESCOLA           = R_INSC_FIAT.NUM_ESCOLA,
                 COMPLEMENTO_ESCOLA   = R_INSC_FIAT.COMPLEMENTO_ESCOLA,
                 BAIESC               = R_INSC_FIAT.BAIESC,
                 CEPESC               = R_INSC_FIAT.CEPESC,
                 CIDESC               = R_INSC_FIAT.NOM_CIDADE,
                 TELESC               = R_INSC_FIAT.TELESC,
                 REG_EMPREGADO        = R_INSC_FIAT.REG_EMPREGADO,
                 NOM_EMPREGADO        = R_INSC_FIAT.NOM_EMPREGADO,
                 RAMAL                = R_INSC_FIAT.RAMAL,
                 DSCCRESP             = R_INSC_FIAT.DSCCRESP,
                 DSCEQUIPE            = R_INSC_FIAT.DSCEQUIPE,
                 INDLEESCREVE         = R_INSC_FIAT.INDLERESCREVER,
                 INDUSATRANS          = R_INSC_FIAT.INDUSATRANS,
                 CODCAMPROXRESIDENCIA = R_INSC_FIAT.COD_CAMPUS_PROX_RESIDENCIA
           WHERE CODCONC = P_CODCONC
             AND CODCAN = VCODCAN;
        END LOOP;
      END IF;
    
    END IF;
  
    INSERT INTO RCANDCURTUROPC
      (CODCONC,
       CODCAN,
       CODCUR,
       CODTUR,
       OPCLIN,
       NROOPC,
       CODCAM,
       CODINSTITUICAO,
       INDFORMACAOAMPLIADA,
       INDPROUNI,
       INDFIES,
       IND_DESEJA_PROUNI,
       IND_DESEJA_FIES)
    VALUES
      (P_CODCONC,
       VCODCAN,
       VCODCUR,
       VCODTUR,
       VOPCLIN,
       VNROOPC,
       VCODCAM,
       NCODINSTITUICAO,
       V_INDFORMACAOAMPLIADA,
       V_INDPROUNI,
       V_INDFIES,
       V_IND_DESEJA_PROUNI,
       V_IND_DESEJA_FIES);
  
  END LOOP;

  --insere log de registro de baixa 
  INSERT INTO DBVESTIB.REGISTRO_BAIXA
    (COD_USUARIO, CODINSC, CODCONC, DAT_BAIXA)
  VALUES
    (DBADM.F_BUSCA_USUARIO(USER), VCODCAN, P_CODCONC, SYSDATE);

  -- ALOCANDO CANDIDATO NUMA SALA
  IF NCODTPOCONCURSO = 1 AND NINDDISPTAUTOMATICA = 'S' THEN
    DBVESTIB.PC_DISTRIBUICAO.SP_DISTRIBUIR_CANDIDATO(P_CODCONC, VCODCAN);
  END IF;

  --Realiza a baixa do pagamento caso exista mapeamento
  BEGIN
    SELECT MI.COD_MAPEAMENTO
      INTO NCODMAPEAMENTO
      FROM DBSIAF.MAPEAMENTO_INSCRICAO MI
     WHERE MI.CODCONC = P_CODCONC
       AND MI.CODINSC = VCODCAN;
  
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  IF NCODMAPEAMENTO IS NOT NULL THEN
  
    -- BAIXAS MANUAIS
    IF NFORMAPGTO = '1' THEN
      -- DINHEIRO
      DBSIAF.PC_MAPEAMENTO_TITULO.SP_BAIXA_MAPEAMENTO_DINHEIRO(NCODMAPEAMENTO,
                                                               VDATPGTO,
                                                               NVALPAGO);
    ELSIF NFORMAPGTO = 'B' THEN
      -- BOLETO
      DBSIAF.PC_MAPEAMENTO_TITULO.SP_BAIXA_TITULO_MAPEADO(NCODMAPEAMENTO,
                                                          VDATPGTO,
                                                          NVALPAGO);
    ELSIF (NFORMAPGTO = '4' OR NFORMAPGTO = '5') THEN
      -- GRATUITO
      DBSIAF.PC_MAPEAMENTO_TITULO.SP_BAIXA_TITULO_MAPEADO(NCODMAPEAMENTO,
                                                          VDATPGTO,
                                                          0);
    END IF;
  
    -- BUSCANDO SITUACAO DO TITULO
    SELECT TR.COD_STA_TITULO, MT.COD_TITULO_RECEBER
      INTO NCODSTATITULO, NCODTITULORECEBER
      FROM DBSIAF.MAPEAMENTO_INSCRICAO MI,
           DBSIAF.MAPEAMENTO_TITULO    MT,
           DBVESTIB.INSCRICAO          IC,
           DBSIAF.TITULO_RECEBER       TR
     WHERE TR.COD_TITULO_RECEBER = MT.COD_TITULO_RECEBER
       AND MI.CODCONC = P_CODCONC
       AND MI.CODINSC = VCODCAN
       AND MI.COD_MAPEAMENTO = MT.COD_MAPEAMENTO
       AND IC.CODCONC = MI.CODCONC
       AND IC.CODINSC = MI.CODINSC;
  
    IF NFORMAPGTO = '4' AND NCODSTATITULO = 3 THEN
      -- Se for pagamento gratuido atualiza baixa
    
      UPDATE TITULO_RECEBER
         SET COD_STA_TITULO            = 6,
             DAT_BAIXA                 = SYSDATE,
             DAT_ALTERACAO_PAGOPARCIAL = TRUNC(SYSDATE),
             VAL_PAGO_PARCIAL          = VAL_TITULO
       WHERE COD_TITULO_RECEBER = NCODTITULORECEBER;
    END IF;
  ELSE
    IF NVALPAGO > 0 THEN
       RAISE_APPLICATION_ERROR(-20500, 'Boleto não encontrado.');
    END IF;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    --rollback;
    RAISE_APPLICATION_ERROR(-20500, SQLERRM);
  
END SP_CONFIRMA_INSC_INTERNET;
/
