DECLARE
	CURSOR C_CORRIGI IS
SELECT DISTINCT LIM.COD_ALUNO,
				SOL.COD_SOLICITACAO,
				LIM.COD_SOLICITACAO_ERRO "SOLICITACAO PARA CANCELAR",
				SOL.DSC_MOTIVO,
				LIM.COD_LIMPEZA_BASE,Cod_Sta_Solicitacao
  FROM DBSIAF.LIMPEZA_BASE LIM
 INNER JOIN DBSIAF.SOLICITACAO SOL
	ON (SOL.COD_ALUNO = LIM.COD_ALUNO /*AND LIM.COD_SOLICITACAO_erro = SOL.COD_SOLICITACAO */
	   AND SOL.COD_TPO_SOLICITACAO = 1334 AND (DBSIAF.F_BUSCA_PROCESSO_JUDICIAL(SOL.COD_ALUNO,
																				 'S',
																				 'N')) IS NULL)
 INNER JOIN DBSIAF.TITULO_RECEBER TRE
	ON (TRE.COD_ALUNO = LIM.COD_ALUNO AND TRE.COD_ASS_CONTRATO = LIM.COD_ASS_CONTRATO AND (DBSIAF.PC_SITUACAO_FINANCEIRA.F_TITULO_COBRANCA(TRE.COD_TITULO_RECEBER) = 'N' OR DBSIAF.PC_SITUACAO_FINANCEIRA.F_TITULO_COBRANCA(TRE.COD_TITULO_RECEBER) = NULL))
 WHERE /* LIM.COD_ALUNO = 1169349
                       AND*/
 --LIM.COD_SOLICITACAO_ERRO IS NOT NULL
 
  TRUNC(LIM.DAT_LIMPEZA_BASE) >= '10/11/2015'
  AND SOL.COD_STA_SOLICITACAO = 1;
  /*and sol.Cod_Sta_Solicitacao = 1
 AND SOL.COD_SOLICITACAO IN (4972289),
							 4972292,
							 4972293,
							 4974795,
							 4972288,
							 4974793,
							 4974794);*\*/
	NMAPEAMENTO DBSISPEX.MAPEAMENTO_SOLICITACAO.COD_MAPEAMENTO%TYPE;

BEGIN
	FOR R_LIM IN C_CORRIGI LOOP
		UPDATE DBSIAF.LIMPEZA_BASE LIM
		   SET LIM.DAT_LIMPEZA_BASE     = NULL,
			   LIM.COD_SOLICITACAO_ERRO = NULL
		 WHERE LIM.COD_LIMPEZA_BASE = R_LIM.COD_LIMPEZA_BASE;
	
	
		DBSIAF.PC_SITUACAO_FINANCEIRA.SP_LIMPEZA_BASE(R_LIM.COD_LIMPEZA_BASE);
	
		UPDATE DBSIAF.SOLICITACAO
		   SET COD_STA_SOLICITACAO = 2 -- CONCLUIDO
		 WHERE COD_SOLICITACAO = R_LIM.COD_SOLICITACAO;  
	COMMIT;
		
	END LOOP;
END; 
