DECLARE
	CURSOR C_COB IS
		SELECT TRE.COD_TITULO_RECEBER,
			   TRE.COD_FUNCIONARIO,
			   TRE.COD_ALUNO               
		  FROM DBSIAF.TITULO_RECEBER TRE
		 INNER JOIN DBSIAF.TITULO_ORIGEM_DESTINO TOD
			ON (TOD.COD_TITULO_ORIGEM = TRE.COD_TITULO_RECEBER)
		 INNER JOIN DBSIAF.TITULO_RECEBER TIT
			ON (TIT.COD_TITULO_RECEBER = TOD.COD_TITULO_DESTINO)
		 WHERE TRE.COD_STA_TITULO = 4
			   AND TRE.COD_MOT_ALTERACAO = 408
			   AND TIT.COD_STA_TITULO <> 4;
S_MSG_ERRO clob;
BEGIN
	FOR R_COB IN C_COB LOOP
		DBSIAF.PC_OPERACAO_TITULO.SP_OPERACAO_TITULO(R_COB.COD_ALUNO,
													 R_COB.COD_TITULO_RECEBER,
													 4,
													 408,
													 'N',
													 'N',
													 S_MSG_ERRO,
													 'S');
		COMMIT;
	END LOOP;
END;
