SELECT DISTINCT IES.NOM_INSTITUICAO PRESTADOR,
				NFE.COD_TITULO_RECEBER,
				FAT.COD_CLIENTE,
				TDS.COD_INTEGRACAO,
				DPC.NOM_PESSOA TOMADOR,
				DPC.COD_ID_FEDER,
				LPAD(NFE.COD_CAMPUS_INTEGRADOR,
					 3,
					 '0') ESTABELECIMENTO,
				NFE.NUM_SERIE_DATASUL SERIE,
				NFE.NUM_NF_DATASUL NUMERO_RPS,
				NFE.NUM_NF_PREFEITURA NUM_NFE,
				NFE.NUM_SERIE_PREFEITURA SERIE_PREFEITURA,
				NFE.DAT_EMISSAO DATA_EMISSAO,
				NFE.COD_AUTENTICACAO_NF COD_AUTENTICACAO,
				FAT.VAL_FATURAMENTO VALOR_NFE,
				FAT.VAL_DESCONTO VALOR_DESCONTO_NFE,
				FAT.DSC_TIT_FATURAMENTO DESCRICAO_SERVICO,
				NFE.DAT_CANCELAMENTO DATA_CANCELAMENTO

  FROM DBINTEGRACAO.MV_ESP_NOTA_FISCAL NFE
 INNER JOIN DBINTEGRACAO.DADOS_IMP_FATURAMENTO FAT
	ON (FAT.COD_TITULO_RECEBER = NFE.COD_TITULO_RECEBER)
 INNER JOIN DBINTEGRACAO.TITULO_DATASUL_SIAF TDS
	ON (TDS.COD_TITULO_RECEBER = FAT.COD_TITULO_RECEBER)
 INNER JOIN DBSIAF.CAMPUS CAM
	ON (CAM.COD_CAMPUS_INTEGRADOR = FAT.COD_CAMPUS_INTEGRADOR)
 INNER JOIN DBINTEGRACAO.PESSOA_CLIENTE_DATASUL PCD
	ON (PCD.COD_CLIENTE = FAT.COD_CLIENTE AND PCD.COD_INSTITUICAO_INTEGRADOR = FAT.COD_INSTITUICAO_INTEGRADOR)
 INNER JOIN DBINTEGRACAO.DADOS_PESSOA_CLIENTE DPC
	ON (DPC.COD_PESSOA = PCD.COD_PESSOA AND DPC.COD_INSTITUICAO = CAM.COD_INSTITUICAO)
 INNER JOIN DBSIAF.INSTITUICAO_ENSINO IES
	ON (IES.COD_INSTITUICAO = CAM.COD_INSTITUICAO)
 WHERE FAT.DAT_FATURAMENTO ='01/09/2015'
       AND NFE.COD_TITULO_RECEBER = 21563843
       
--1568,00 valor NFE

SELECT * FROM DBSIAF.TITULO_RECEBER WHERE COD_TITULO_RECEBER = 21563843
SELECT * FROM DBSIAF.TITULO_RECEBER WHERE COD_TITULO_RECEBER = 21563844
SELECT * FROM DBSIAF.TITULO_ORIGEM_DESTINO TOD WHERE TOD.COD_TITULO_ORIGEM = 21563843

SELECT TLA.COD_ESP_LANCAMENTO, TLA.DSC_TPO_LANCAMENTO, TLA.IDT_TPO_LANCAMENTO, FFI.* 
  FROM DBSIAF.FICHA_FINANCEIRA FFI
                                    INNER JOIN DBSIAF.TIPO_LANCAMENTO TLA ON FFI.COD_TPO_LANCAMENTO = TLA.COD_TPO_LANCAMENTO
 WHERE COD_TITULO_RECEBER = 21563843

SELECT *
  FROM DBINTEGRACAO.TITULO_DATASUL_SIAF
 WHERE COD_TITULO_RECEBER = 21563844

SELECT *
  FROM DBINTEGRACAO.APROPRIACAO_CONTABIL APC
 WHERE APC.COD_INTEGRACAO = 12607236
   AND APC.COD_TPO_PROCESSO = 3
   AND APC.COD_TPO_PROCESSO_GER = 3
   AND APC.COD_STA_INTEGRACAO IN (1, 2)
 
SELECT TLA.DSC_TPO_LANCAMENTO, TLA.IDT_TPO_LANCAMENTO, FFI.* 
  FROM DBSIAF.FICHA_FINANCEIRA FFI
                                    INNER JOIN DBSIAF.TIPO_LANCAMENTO TLA ON FFI.COD_TPO_LANCAMENTO = TLA.COD_TPO_LANCAMENTO
 WHERE COD_TITULO_RECEBER = 21563844;
 
DBINTEGRACAO.PC_INTEGRACAO_DATASUL.SP_TITULO_FAT
