DECLARE
CURSOR C_ALUNO IS
SELECT-- COUNT(ALU.NUM_MATRICULA),
	   ALU.NUM_MATRICULA,
	   ALU.COD_STA_ALUNO,
	   SOL.COD_ALUNO, --TIT.NUM_PARCELA,
	   SOL.COD_SOLICITACAO,
	   SOL.DAT_SOLICITACAO,
	   LIM.DAT_LIMPEZA_BASE,
	   LIM.COD_LIMPEZA_BASE,
       TIT.DAT_PROG_ORIGINAL,
       TIT.DAT_PRORROGACAO
  FROM DBSIAF.TITULO_RECEBER TIT
  JOIN DBSIAF.SOLICITACAO SOL
	ON (TIT.COD_ALUNO = SOL.COD_ALUNO AND TIT.COD_INSTITUICAO = SOL.COD_INSTITUICAO)
  JOIN DBSIAF.TIPO_SOLICITACAO_ETAPA TSE
	ON (TSE.COD_TPO_SOLICITACAO = SOL.COD_TPO_SOLICITACAO)
  JOIN DBSIAF.ETAPA_STATUS_SOLICITACAO ESS
	ON (ESS.COD_ETAPA_SOLICITACAO = TSE.COD_ETAPA_SOLICITACAO AND ESS.COD_STA_SOLICITACAO = SOL.COD_STA_SOLICITACAO)
  JOIN DBSIAF.ACAO_PROTOCOLO APR
	ON (APR.COD_ACAO_PROTOCOLO = ESS.COD_ACAO_PROTOCOLO AND APR.COD_TPO_SERVICO IN (2,3))
  JOIN DBSIAF.TIPO_TITULO TTL
	ON (TTL.COD_TPO_TITULO = TIT.COD_TPO_TITULO AND TTL.IND_FINANCEIRO = 'S' AND TTL.IND_MENSALIDADE = 'S')
  JOIN DBSIAF.LIMPEZA_BASE LIM
	ON (LIM.COD_INSTITUICAO = SOL.COD_INSTITUICAO AND
     LIM.COD_ALUNO = SOL.COD_ALUNO AND LIM.COD_SOLICITACAO = SOL.COD_SOLICITACAO 
     )
 JOIN DBSIAF.ALUNO ALU
	ON (ALU.COD_ALUNO = TIT.COD_ALUNO AND ALU.COD_INSTITUICAO = SOL.COD_INSTITUICAO)
 WHERE TIT.COD_INSTITUICAO = 8
	   AND TIT.COD_STA_TITULO = 1
	   AND TIT.DAT_PROG_ORIGINAL > SOL.DAT_SOLICITACAO
	   AND (TIT.VAL_TITULO > 0 OR TIT.VAL_TITULO = 0 AND TIT.COD_STA_TITULO = 1)
      AND dbsiaf.pc_cobranca.F_TITULO_COBRANCA(TIT.COD_TITULO_RECEBER) = 'N'
     -- and lim.cod_limpeza_base = 973317
     /*  GROUP BY ALU.NUM_MATRICULA,
		  ALU.COD_STA_ALUNO,
		  SOL.COD_ALUNO, --TIT.NUM_PARCELA,
		  SOL.COD_SOLICITACAO,
		  SOL.DAT_SOLICITACAO,
		  LIM.DAT_LIMPEZA_BASE,
		  LIM.COD_LIMPEZA_BASE;*/
--HAVING count(ALU.NUM_MATRICULA) =1


select * from dbsiaf.limpeza_base l
where l.cod_aluno = 843602
BEGIN
  FOR R_ALUNO IN C_ALUNO LOOP
    UPDATE DBSIAF.LIMPEZA_BASE LIM
    SET LIM.DAT_LIMPEZA_BASE = NULL
    WHERE LIM.COD_LIMPEZA_BASE =1145992;
   /* -- SELECT NUM_MATRICULA
    FROM DBSIAF.ALUNO
    WHERE COD_ALUNO = 843602*/
  END LOOP;
COMMIT;
END;    



