--- inserir na títulos Mira
INSERT INTO DBSIAF.TITULO_MIRA (COD_TITULO_RECEBER, VAL_PAGO, VAL_ENTRADA, DAT_PAGAMENTO, COD_COND_PGTO)
SELECT IMP.COD_TITULO_RECEBER, IMP.VAL_FATURAMENTO, IMP.VAL_DESCONTO, IMP.DAT_FATURAMENTO, IMP.COD_LOG_INTEGRACAO
  FROM  DBINTEGRACAO.DADOS_IMP_FATURAMENTO IMP
     WHERE IMP.Dat_Faturamento = TRUNC (TO_DATE('01/10/2015'));
     
-- deleta a integração antiga
DELETE
   FROM  DBINTEGRACAO.DADOS_IMP_FATURAMENTO imp
    WHERE IMP.DAT_FATURAMENTO = TRUNC(TO_DATE('01/10/2015', 'dd/mm/yyyy'))
     
-- Executa a integração

BEGIN
     DBINTEGRACAO.PC_INTEGRACAO_DATASUL.SP_TITULO_FAT(to_date('01/10/2015', 'DD/MM/YYYY'),
                                                      'N',
                                                      1);
 END;
      
-- após compilação, verifica se houve modificação nos valores

    SELECT mir.COD_TITULO_RECEBER "TITULO",
       MIR.VAL_PAGO "MIRA_FATURAMENTO" ,
	   MIR.VAL_ENTRADA "MIRA_DESCONTO",
	   IMP.VAL_FATURAMENTO,
       IMP.VAL_DESCONTO
  FROM DBINTEGRACAO.DADOS_IMP_FATURAMENTO IMP,
	   DBSIAF.TITULO_MIRA                 MIR
 WHERE IMP.COD_TITULO_RECEBER = MIR.COD_TITULO_RECEBER 
	   AND MIR.VAL_PAGO <> IMP.VAL_FATURAMENTO
       AND  IMP.COD_TITULO_RECEBER = 22166515--21563843;

---- Executar Job SP_LIQ_CHEQUE_DTSUL_JOB
     
